/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeIdioma } from './empregabilidadeIdioma'
import type { EmpregabilidadeNivelIdioma } from './empregabilidadeNivelIdioma'

export interface EmpregabilidadeCurriculoIdioma {
  cpf?: string
  created_at?: string
  id?: string
  id_idioma?: string
  id_nivel?: string
  /** Relationships */
  idioma?: EmpregabilidadeIdioma
  nivel?: EmpregabilidadeNivelIdioma
  updated_at?: string
}
