/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeEscolaridade } from './empregabilidadeEscolaridade'
import type { EmpregabilidadeStatusFormacao } from './empregabilidadeStatusFormacao'

export interface EmpregabilidadeCurriculoFormacao {
  ano_conclusao?: string
  cpf?: string
  created_at?: string
  /** Relationships */
  escolaridade?: EmpregabilidadeEscolaridade
  id?: string
  id_escolaridade?: string
  nome_curso?: string
  nome_instituicao?: string
  status?: EmpregabilidadeStatusFormacao
  updated_at?: string
}
