/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeIdioma } from './empregabilidadeIdioma'

/**
 * Dados do idioma
 */
export type EmpregabilidadeIdiomaBody = EmpregabilidadeIdioma
