/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export interface EmpregabilidadeRespostaInfoComplementar {
  id_info?: string
  resposta?: string
  titulo?: string
}
