/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export interface EmpregabilidadeCurriculoItensReplaceAll {
  area_atuacao_habilidade_ids?: number[]
  comportamento_atitudes_ids?: number[]
}
