/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeDisponibilidade } from './empregabilidadeDisponibilidade'
import type { EmpregabilidadeSituacaoAtual } from './empregabilidadeSituacaoAtual'

export interface EmpregabilidadeCurriculoSituacaoInteresses {
  cpf?: string
  created_at?: string
  disponibilidade?: EmpregabilidadeDisponibilidade
  id_disponibilidade?: string
  id_situacao?: string
  ids_tipos_vinculo_preferencia?: string[]
  /** Relationships */
  situacao?: EmpregabilidadeSituacaoAtual
  tempo_procurando_emprego?: string
  updated_at?: string
}
