/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeHabilidade } from './empregabilidadeHabilidade'

export interface EmpregabilidadeAreaAtuacao {
  created_at?: string
  habilidades?: EmpregabilidadeHabilidade[]
  id?: number
  nome?: string
  updated_at?: string
}
