/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export interface EmpregabilidadeCurriculoCursoComplementar {
  ano_conclusao?: string
  cpf?: string
  created_at?: string
  id?: string
  nome_curso?: string
  nome_instituicao?: string
  updated_at?: string
}
