/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export interface EmpregabilidadeSituacaoAtual {
  created_at?: string
  descricao?: string
  id?: string
  updated_at?: string
}
