/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type EmpregabilidadeStatusVaga =
  (typeof EmpregabilidadeStatusVaga)[keyof typeof EmpregabilidadeStatusVaga]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmpregabilidadeStatusVaga = {
  StatusVagaEmEdicao: 'em_edicao',
  StatusVagaEmAprovacao: 'em_aprovacao',
  StatusVagaPublicadoAtivo: 'publicado_ativo',
  StatusVagaPublicadoExpirado: 'publicado_expirado',
  StatusVagaCongelada: 'vaga_congelada',
  StatusVagaDescontinuada: 'vaga_descontinuada',
} as const
