/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type EmpregabilidadeTipoCampo =
  (typeof EmpregabilidadeTipoCampo)[keyof typeof EmpregabilidadeTipoCampo]

export const EmpregabilidadeTipoCampo = {
  TipoCampoRespostaCurta: 'resposta_curta',
  TipoCampoRespostaNumerica: 'resposta_numerica',
  TipoCampoSelecaoUnica: 'selecao_unica',
  TipoCampoSelecaoMultipla: 'selecao_multipla',
} as const
