/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EmpregabilidadeComportamentosAtitudesParams = {
  /**
   * Termo de busca
   */
  q?: string
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 20, max: 100)
   */
  pageSize?: number
}
