/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EmpregabilidadeCandidaturasParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  pageSize?: number
  /**
   * Filtrar por CPF (apenas admin)
   */
  cpf?: string
  /**
   * Filtrar por ID da vaga
   */
  vagaId?: string
  /**
   * Filtrar por status
   */
  status?: string
  /**
   * Busca parcial por CPF, nome ou email (apenas admin)
   */
  search?: string
  /**
   * Filtrar por ID da etapa atual
   */
  etapa_id?: string
}
