/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1UsersUserIdCourses200 = { [key: string]: unknown }
