/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EmpregosParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  pageSize?: number
  /**
   * Filtrar por ID do órgão (external reference)
   */
  orgao_id?: string
  /**
   * Filtrar por ID da empresa
   */
  empresa_id?: number
  /**
   * Filtrar por ID da escolaridade
   */
  escolaridade_id?: number
  /**
   * Filtrar por status
   */
  status?: string
  /**
   * Filtrar por tipo de contratação
   */
  tipo_contratacao?: string
  /**
   * Filtrar por jornada de trabalho
   */
  jornada_trabalho?: string
}
