/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EmpregabilidadeCandidaturaBloqueiosParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  pageSize?: number
  /**
   * Filtrar por CPF
   */
  cpf?: string
  /**
   * Filtrar por ID da vaga
   */
  id_vaga?: string
}
