/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EmpregabilidadeEmpresasParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  pageSize?: number
  /**
   * Busca parcial em razão social ou nome fantasia
   */
  search?: string
  /**
   * Filtrar por CNPJ exato
   */
  cnpj?: string
}
