/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1CategoriasParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  pageSize?: number
  /**
   * Filtrar apenas categorias com cursos abertos
   */
  onlyWithCourses?: boolean
  /**
   * Dias de tolerância após vencimento da inscrição (default: 30)
   */
  daysTolerance?: number
  /**
   * Filtrar cursos visíveis (default: true)
   */
  isVisible?: boolean
}
