/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1UsersUserIdCoursesParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  limit?: number
  /**
   * Filtrar por status
   */
  status?: string
  /**
   * Filtrar por modalidade
   */
  modalidade?: string
  /**
   * Filtrar por categoria
   */
  categoria_id?: number
  /**
   * Filtrar por acessibilidade
   */
  acessibilidade_id?: number
  /**
   * Filtrar por zona do bairro
   */
  neighborhood_zone?: string
}
