/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1CoursesCourseIdEnrollmentsParams = {
/**
 * Número da página (default: 1)
 */
page?: number;
/**
 * Tamanho da página (default: 20)
 */
limit?: number;
/**
 * Filtrar por status
 */
status?: string;
/**
 * Buscar por CPF, nome ou email
 */
search?: string;
};
