/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EscolaridadesParams = {
/**
 * Nu00famero da pu00e1gina (default: 1)
 */
page?: number;
/**
 * Tamanho da pu00e1gina (default: 10)
 */
pageSize?: number;
};
