/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1OportunidadesMeiIdPropostasParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10, max: 1000)
   */
  pageSize?: number
  /**
   * Buscar por nome da empresa (case-insensitive)
   */
  nomeEmpresa?: string
  /**
   * Buscar por CNPJ
   */
  cnpj?: string
  /**
   * Filtrar por status (submitted, approved, rejected)
   */
  status?: string
}
