/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { GetApiPublicCoursesSort } from './getApiPublicCoursesSort'

export type GetApiPublicCoursesParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 10)
   */
  limit?: number
  /**
   * Filtrar por status (CSV, ex: draft,published,in_review)
   */
  status?: string
  /**
   * Filtrar por modalidade
   */
  modalidade?: string
  /**
   * Filtrar por organização (provedor do curso)
   */
  organization?: string
  /**
   * Buscar no título
   */
  search?: string
  /**
   * Filtrar por categoria
   */
  categoria_id?: number
  /**
   * Filtrar por acessibilidade
   */
  acessibilidade_id?: number
  /**
   * Filtrar por zona do bairro
   */
  neighborhood_zone?: string
  /**
   * Ordenação opcional. 'availability': cursos com inscrição disponível primeiro; os sem inscrição (status final, prazo vencido ou vagas esgotadas — inclusive accepting_enrollments sem vagas) vão para o final. A ordenação é aplicada antes da paginação. Omitido = ordem padrão (id desc).
   */
  sort?: GetApiPublicCoursesSort
}
