/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsPropostaMEIStatusAdmin =
  (typeof ModelsPropostaMEIStatusAdmin)[keyof typeof ModelsPropostaMEIStatusAdmin]

export const ModelsPropostaMEIStatusAdmin = {
  draft: 'draft',
  active: 'active',
  expired: 'expired',
} as const
