/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsStatusInscricao } from './modelsStatusInscricao';

export interface ModelsEnrollmentStatusUpdateRequest {
  admin_notes?: string;
  enrollment_ids: string[];
  reason?: string;
  status: ModelsStatusInscricao;
}
