/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsTipoContratacao =
  (typeof ModelsTipoContratacao)[keyof typeof ModelsTipoContratacao]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsTipoContratacao = {
  TipoContratacaoCLT: 'CLT',
  TipoContratacaoEstagio: 'ESTAGIO',
  TipoContratacaoMEI: 'MEI',
  TipoContratacaoPJ: 'PJ',
} as const
