/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsEmprego } from './modelsEmprego'

export interface ModelsEscolaridade {
  /** Relacionamentos */
  empregos?: ModelsEmprego[]
  id?: number
  nivel?: string
}
