/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsEmprego } from './modelsEmprego';

export interface ModelsEmpresa {
  /** Relacionamentos */
  empregos?: ModelsEmprego[];
  id?: number;
  nome?: string;
}
