/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsCurso } from './modelsCurso';

export interface ModelsLocationClass {
  address?: string;
  class_days?: string;
  class_end_date?: string;
  class_start_date?: string;
  class_time?: string;
  created_at?: string;
  /** Relacionamentos */
  curso?: ModelsCurso;
  curso_id?: number;
  id?: string;
  neighborhood?: string;
  updated_at?: string;
  vacancies?: number;
}
