/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsSearchDocumentsResponse } from './modelsSearchDocumentsResponse'

/**
 * Mapa de resultados por coleção
 */
export type ModelsMultiCollectionSearchResponseResults = {
  [key: string]: ModelsSearchDocumentsResponse
}
