/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsTurno = (typeof ModelsTurno)[keyof typeof ModelsTurno]

export const ModelsTurno = {
  TurnoManha: 'MANHA',
  TurnoTarde: 'TARDE',
  TurnoNoite: 'NOITE',
  TurnoIntegral: 'INTEGRAL',
  TurnoLivre: 'LIVRE',
} as const
