/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsMultiCollectionSearchResponseResults } from './modelsMultiCollectionSearchResponseResults'

export interface ModelsMultiCollectionSearchResponse {
  /** Mapa de resultados por coleção */
  results?: ModelsMultiCollectionSearchResponseResults
  total_found?: number
}
