/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsStatusOportunidadeMEI =
  (typeof ModelsStatusOportunidadeMEI)[keyof typeof ModelsStatusOportunidadeMEI]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsStatusOportunidadeMEI = {
  StatusOportunidadeDraft: 'draft',
  StatusOportunidadeActive: 'active',
  StatusOportunidadeExpired: 'expired',
} as const
