/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsAcessibilidade } from './modelsAcessibilidade';
import type { ModelsCategoria } from './modelsCategoria';
import type { ModelsCustomField } from './modelsCustomField';
import type { ModelsInscricao } from './modelsInscricao';
import type { ModelsFormatoAula } from './modelsFormatoAula';
import type { ModelsInstituicaoEnsino } from './modelsInstituicaoEnsino';
import type { ModelsLocationClass } from './modelsLocationClass';
import type { ModelsModalidade } from './modelsModalidade';
import type { ModelsOrgao } from './modelsOrgao';
import type { ModelsRemoteClass } from './modelsRemoteClass';
import type { ModelsStatusCurso } from './modelsStatusCurso';
import type { ModelsTurno } from './modelsTurno';

export interface ModelsCurso {
  acessibilidades?: ModelsAcessibilidade[];
  carga_horaria?: number;
  categorias?: ModelsCategoria[];
  certificacao_oferecida?: boolean;
  contato_duvidas?: string;
  cover_image?: string;
  created_at?: string;
  /** New relationships for enrollment system */
  custom_fields?: ModelsCustomField[];
  data_inicio?: string;
  data_limite_inscricoes?: string;
  data_termino?: string;
  description?: string;
  enrollment_end_date?: string;
  enrollment_start_date?: string;
  enrollments?: ModelsInscricao[];
  expected_results?: string;
  facilitator?: string;
  formato_aula?: ModelsFormatoAula;
  has_certificate?: boolean;
  id?: number;
  instituicao?: ModelsInstituicaoEnsino;
  instituicao_id?: number;
  institutional_logo?: string;
  link_inscricao?: string;
  local_realizacao?: string;
  locations?: ModelsLocationClass[];
  material_used?: string;
  methodology?: string;
  modalidade?: ModelsModalidade;
  numero_vagas?: number;
  objectives?: string;
  organization?: string;
  /** Relacionamentos */
  orgao?: ModelsOrgao;
  /** Legacy and additional fields */
  orgao_id?: number;
  /** Legacy compatibility - kept for backwards compatibility */
  pre_requisitos?: string;
  /** Optional fields matching specification */
  prerequisites?: string;
  program_content?: string;
  remote_class?: ModelsRemoteClass;
  resources_used?: string;
  status?: ModelsStatusCurso;
  target_audience?: string;
  teaching_material?: string;
  theme?: string;
  /** Core fields (always required) */
  title?: string;
  turno?: ModelsTurno;
  updated_at?: string;
  workload?: string;
}
