/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsEnrolledUnitSchedule } from './modelsEnrolledUnitSchedule'

export interface ModelsEnrolledUnit {
  address?: string
  created_at?: string
  curso_id?: number
  id?: string
  neighborhood?: string
  neighborhood_zone?: string
  schedules?: ModelsEnrolledUnitSchedule[]
  updated_at?: string
}
