/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsJobErrorsItem } from './modelsJobErrorsItem'
import type { ModelsJobMetadata } from './modelsJobMetadata'
import type { ModelsJobResult } from './modelsJobResult'
import type { ModelsJobStatus } from './modelsJobStatus'
import type { ModelsJobType } from './modelsJobType'

export interface ModelsJob {
  /** Data/hora de conclusão */
  completed_at?: string
  /** Data/hora de criação */
  created_at?: string
  /** Quantidade de registros com erro */
  error_count?: number
  /** Lista de erros detalhados por linha */
  errors?: ModelsJobErrorsItem[]
  /** ID único do job */
  id?: string
  /** Metadata adicional (curso_id, file_name, etc) */
  metadata?: ModelsJobMetadata
  /** Progresso em porcentagem (0-100) */
  progress?: number
  /** Resultado final do processamento */
  result?: ModelsJobResult
  /** Status: pending, processing, completed, failed */
  status?: ModelsJobStatus
  /** Quantidade de registros processados com sucesso */
  success_count?: number
  /** Total de registros a processar */
  total_records?: number
  /** Tipo de job (enrollment_import, etc) */
  type?: ModelsJobType
  /** Data/hora da última atualização */
  updated_at?: string
}
