/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsFormatoAula =
  (typeof ModelsFormatoAula)[keyof typeof ModelsFormatoAula]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsFormatoAula = {
  FormatoAulaGravado: 'GRAVADO',
  FormatoAulaAoVivo: 'AO_VIVO',
} as const
