/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsPropostaMEIStatusAdmin } from './modelsPropostaMEIStatusAdmin'
import type { ModelsPropostaMEIStatusCidadao } from './modelsPropostaMEIStatusCidadao'

export interface ModelsPropostaMEI {
  aceita_custos_integrais?: boolean
  celular_pessoa_fisica?: string
  created_at?: string
  deleted_at?: string
  /** Computed fields from RMI API (not persisted to database) */
  email_pessoa_fisica?: string
  id?: string
  mei_empresa_id?: string
  oportunidade_mei_id?: number
  prazo_execucao?: string
  status_admin?: ModelsPropostaMEIStatusAdmin
  status_cidadao?: ModelsPropostaMEIStatusCidadao
  updated_at?: string
  valor_proposta?: number
}
