/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsPropostaStatusUpdateRequestStatus =
  (typeof ModelsPropostaStatusUpdateRequestStatus)[keyof typeof ModelsPropostaStatusUpdateRequestStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsPropostaStatusUpdateRequestStatus = {
  submitted: 'submitted',
  approved: 'approved',
  rejected: 'rejected',
} as const
