/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type PostApiV1CoursesCourseIdEnrollmentsImport202 = {
  [key: string]: unknown
}
