/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type PutApiV1EmpregabilidadeCandidaturasIdStatus500 = {
  [key: string]: string
}
