/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeComportamentoAtitudes } from './empregabilidadeComportamentoAtitudes'

export interface ResponseListComportamentoAtitudesPaginatedResponse {
  data?: EmpregabilidadeComportamentoAtitudes[]
  page?: number
  pageSize?: number
  total?: number
}
