/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * app-catalogo
 * Discovery layer unificada da Prefeitura do Rio de Janeiro. Indexa serviços públicos, cursos, vagas e oportunidades MEI com busca full-text e recomendação personalizada por perfil de cidadão.
 * OpenAPI spec version: 1.0
 */

export type GetApiPublicCatalogId400 = { [key: string]: string }
