/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * app-catalogo
 * Discovery layer unificada da Prefeitura do Rio de Janeiro. Indexa serviços públicos, cursos, vagas e oportunidades MEI com busca full-text e recomendação personalizada por perfil de cidadão.
 * OpenAPI spec version: 1.0
 */

export type ModelsItemSource =
  (typeof ModelsItemSource)[keyof typeof ModelsItemSource]

export const ModelsItemSource = {
  SourceSalesForce: 'salesforce',
  SourceCourses: 'courses',
  SourceJobs: 'jobs',
  SourceMEI: 'mei',
  /** fonte composta: courses + jobs + mei */
  SourceAppGoAPI: 'app-go-api',
  /** temporário: Carta de Serviços até migração para SalesForce */
  SourceTypesense: 'typesense',
} as const
