/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * app-catalogo
 * Discovery layer unificada da Prefeitura do Rio de Janeiro. Indexa serviços públicos, cursos, vagas e oportunidades MEI com busca full-text e recomendação personalizada por perfil de cidadão.
 * OpenAPI spec version: 1.0
 */
import type { ModelsItemSource } from './modelsItemSource'
import type { ModelsItemType } from './modelsItemType'
import type { ModelsSearchItemMetadata } from './modelsSearchItemMetadata'

export interface ModelsSearchItem {
  bairros?: string[]
  highlights?: string[]
  id?: string
  image_url?: string
  metadata?: ModelsSearchItemMetadata
  modalidade?: string
  organization?: string
  relevance_score?: number
  short_desc?: string
  source?: ModelsItemSource
  tags?: string[]
  title?: string
  type?: ModelsItemType
  url?: string
}
