/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1CategoriasId200,
  GetApiV1Categorias200,
  GetApiV1CategoriasParams,
  ModelsCategoria,
  ModelsErrorResponse,
} from '../models'

import { customFetch } from '../../../custom-fetch-course'

export type getApiV1CategoriasResponse200 = {
  data: GetApiV1Categorias200
  status: 200
}

export type getApiV1CategoriasResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type getApiV1CategoriasResponseSuccess =
  getApiV1CategoriasResponse200 & {
    headers: Headers
  }
export type getApiV1CategoriasResponseError = getApiV1CategoriasResponse500 & {
  headers: Headers
}

export type getApiV1CategoriasResponse =
  | getApiV1CategoriasResponseSuccess
  | getApiV1CategoriasResponseError

export const getGetApiV1CategoriasUrl = (params?: GetApiV1CategoriasParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/categorias?${stringifiedParams}`
    : `/api/v1/categorias`
}

/**
 * Retorna lista paginada de categorias. Use onlyWithCourses=true para filtrar apenas categorias com cursos com status aberto (opened/ABERTO).
 * @summary Listar categorias
 */
export const getApiV1Categorias = async (
  params?: GetApiV1CategoriasParams,
  options?: RequestInit
): Promise<getApiV1CategoriasResponse> => {
  return customFetch<getApiV1CategoriasResponse>(
    getGetApiV1CategoriasUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type postApiV1CategoriasResponse201 = {
  data: ModelsCategoria
  status: 201
}

export type postApiV1CategoriasResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type postApiV1CategoriasResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type postApiV1CategoriasResponseSuccess =
  postApiV1CategoriasResponse201 & {
    headers: Headers
  }
export type postApiV1CategoriasResponseError = (
  | postApiV1CategoriasResponse400
  | postApiV1CategoriasResponse500
) & {
  headers: Headers
}

export type postApiV1CategoriasResponse =
  | postApiV1CategoriasResponseSuccess
  | postApiV1CategoriasResponseError

export const getPostApiV1CategoriasUrl = () => {
  return `/api/v1/categorias`
}

/**
 * Cria uma nova categoria de curso
 * @summary Criar categoria
 */
export const postApiV1Categorias = async (
  modelsCategoria: ModelsCategoria,
  options?: RequestInit
): Promise<postApiV1CategoriasResponse> => {
  return customFetch<postApiV1CategoriasResponse>(getPostApiV1CategoriasUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modelsCategoria),
  })
}

export type deleteApiV1CategoriasIdResponse200 = {
  data: DeleteApiV1CategoriasId200
  status: 200
}

export type deleteApiV1CategoriasIdResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type deleteApiV1CategoriasIdResponse404 = {
  data: ModelsErrorResponse
  status: 404
}

export type deleteApiV1CategoriasIdResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type deleteApiV1CategoriasIdResponseSuccess =
  deleteApiV1CategoriasIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1CategoriasIdResponseError = (
  | deleteApiV1CategoriasIdResponse400
  | deleteApiV1CategoriasIdResponse404
  | deleteApiV1CategoriasIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1CategoriasIdResponse =
  | deleteApiV1CategoriasIdResponseSuccess
  | deleteApiV1CategoriasIdResponseError

export const getDeleteApiV1CategoriasIdUrl = (id: number) => {
  return `/api/v1/categorias/${id}`
}

/**
 * Remove uma categoria pelo ID
 * @summary Excluir categoria
 */
export const deleteApiV1CategoriasId = async (
  id: number,
  options?: RequestInit
): Promise<deleteApiV1CategoriasIdResponse> => {
  return customFetch<deleteApiV1CategoriasIdResponse>(
    getDeleteApiV1CategoriasIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getApiV1CategoriasIdResponse200 = {
  data: ModelsCategoria
  status: 200
}

export type getApiV1CategoriasIdResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type getApiV1CategoriasIdResponse404 = {
  data: ModelsErrorResponse
  status: 404
}

export type getApiV1CategoriasIdResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type getApiV1CategoriasIdResponseSuccess =
  getApiV1CategoriasIdResponse200 & {
    headers: Headers
  }
export type getApiV1CategoriasIdResponseError = (
  | getApiV1CategoriasIdResponse400
  | getApiV1CategoriasIdResponse404
  | getApiV1CategoriasIdResponse500
) & {
  headers: Headers
}

export type getApiV1CategoriasIdResponse =
  | getApiV1CategoriasIdResponseSuccess
  | getApiV1CategoriasIdResponseError

export const getGetApiV1CategoriasIdUrl = (id: number) => {
  return `/api/v1/categorias/${id}`
}

/**
 * Retorna uma categoria pelo ID
 * @summary Buscar categoria
 */
export const getApiV1CategoriasId = async (
  id: number,
  options?: RequestInit
): Promise<getApiV1CategoriasIdResponse> => {
  return customFetch<getApiV1CategoriasIdResponse>(
    getGetApiV1CategoriasIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1CategoriasIdResponse200 = {
  data: ModelsCategoria
  status: 200
}

export type putApiV1CategoriasIdResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type putApiV1CategoriasIdResponse404 = {
  data: ModelsErrorResponse
  status: 404
}

export type putApiV1CategoriasIdResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type putApiV1CategoriasIdResponseSuccess =
  putApiV1CategoriasIdResponse200 & {
    headers: Headers
  }
export type putApiV1CategoriasIdResponseError = (
  | putApiV1CategoriasIdResponse400
  | putApiV1CategoriasIdResponse404
  | putApiV1CategoriasIdResponse500
) & {
  headers: Headers
}

export type putApiV1CategoriasIdResponse =
  | putApiV1CategoriasIdResponseSuccess
  | putApiV1CategoriasIdResponseError

export const getPutApiV1CategoriasIdUrl = (id: number) => {
  return `/api/v1/categorias/${id}`
}

/**
 * Atualiza uma categoria existente
 * @summary Atualizar categoria
 */
export const putApiV1CategoriasId = async (
  id: number,
  modelsCategoria: ModelsCategoria,
  options?: RequestInit
): Promise<putApiV1CategoriasIdResponse> => {
  return customFetch<putApiV1CategoriasIdResponse>(
    getPutApiV1CategoriasIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsCategoria),
    }
  )
}
