/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Curriculo Agent API
 * API pública intermediária entre o frontend do SuperApp e o agente de currículo (kagent). Expõe um único endpoint de chat que recebe a mensagem do usuário, encaminha ao agente via protocolo A2A (JSON-RPC 2.0) e devolve a resposta em texto.
 * OpenAPI spec version: 1.0.0
 */

export * from './chatRequest'
export * from './chatResponse'
