/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeVagasIdEtapasEtapaId200,
  DeleteApiV1EmpregabilidadeVagasIdEtapasEtapaId400,
  DeleteApiV1EmpregabilidadeVagasIdEtapasEtapaId500,
  EmpregabilidadeEtapa,
  GetApiV1EmpregabilidadeVagasIdEtapas200,
  GetApiV1EmpregabilidadeVagasIdEtapas400,
  GetApiV1EmpregabilidadeVagasIdEtapas500,
  GetApiV1EmpregabilidadeVagasIdEtapasEtapaId400,
  GetApiV1EmpregabilidadeVagasIdEtapasEtapaId404,
  GetApiV1EmpregabilidadeVagasIdEtapasEtapaId500,
  PostApiV1EmpregabilidadeVagasIdEtapas400,
  PostApiV1EmpregabilidadeVagasIdEtapas500,
  PutApiV1EmpregabilidadeVagasIdEtapasEtapaId400,
  PutApiV1EmpregabilidadeVagasIdEtapasEtapaId500,
} from '../models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna todas as etapas de uma vaga
 * @summary Listar etapas da vaga
 */
export type getApiV1EmpregabilidadeVagasIdEtapasResponse200 = {
  data: GetApiV1EmpregabilidadeVagasIdEtapas200
  status: 200
}

export type getApiV1EmpregabilidadeVagasIdEtapasResponse400 = {
  data: GetApiV1EmpregabilidadeVagasIdEtapas400
  status: 400
}

export type getApiV1EmpregabilidadeVagasIdEtapasResponse500 = {
  data: GetApiV1EmpregabilidadeVagasIdEtapas500
  status: 500
}

export type getApiV1EmpregabilidadeVagasIdEtapasResponseSuccess =
  getApiV1EmpregabilidadeVagasIdEtapasResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeVagasIdEtapasResponseError = (
  | getApiV1EmpregabilidadeVagasIdEtapasResponse400
  | getApiV1EmpregabilidadeVagasIdEtapasResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeVagasIdEtapasResponse =
  | getApiV1EmpregabilidadeVagasIdEtapasResponseSuccess
  | getApiV1EmpregabilidadeVagasIdEtapasResponseError

export const getGetApiV1EmpregabilidadeVagasIdEtapasUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/etapas`
}

export const getApiV1EmpregabilidadeVagasIdEtapas = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeVagasIdEtapasResponse> => {
  return customFetch<getApiV1EmpregabilidadeVagasIdEtapasResponse>(
    getGetApiV1EmpregabilidadeVagasIdEtapasUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma nova etapa para uma vaga
 * @summary Criar etapa
 */
export type postApiV1EmpregabilidadeVagasIdEtapasResponse201 = {
  data: EmpregabilidadeEtapa
  status: 201
}

export type postApiV1EmpregabilidadeVagasIdEtapasResponse400 = {
  data: PostApiV1EmpregabilidadeVagasIdEtapas400
  status: 400
}

export type postApiV1EmpregabilidadeVagasIdEtapasResponse500 = {
  data: PostApiV1EmpregabilidadeVagasIdEtapas500
  status: 500
}

export type postApiV1EmpregabilidadeVagasIdEtapasResponseSuccess =
  postApiV1EmpregabilidadeVagasIdEtapasResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeVagasIdEtapasResponseError = (
  | postApiV1EmpregabilidadeVagasIdEtapasResponse400
  | postApiV1EmpregabilidadeVagasIdEtapasResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeVagasIdEtapasResponse =
  | postApiV1EmpregabilidadeVagasIdEtapasResponseSuccess
  | postApiV1EmpregabilidadeVagasIdEtapasResponseError

export const getPostApiV1EmpregabilidadeVagasIdEtapasUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/etapas`
}

export const postApiV1EmpregabilidadeVagasIdEtapas = async (
  id: string,
  empregabilidadeEtapa: EmpregabilidadeEtapa,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeVagasIdEtapasResponse> => {
  return customFetch<postApiV1EmpregabilidadeVagasIdEtapasResponse>(
    getPostApiV1EmpregabilidadeVagasIdEtapasUrl(id),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEtapa),
    }
  )
}

/**
 * Remove uma etapa pelo ID
 * @summary Excluir etapa
 */
export type deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeVagasIdEtapasEtapaId200
  status: 200
}

export type deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeVagasIdEtapasEtapaId400
  status: 400
}

export type deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeVagasIdEtapasEtapaId500
  status: 500
}

export type deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseSuccess =
  deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseError = (
  | deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse400
  | deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse =
  | deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseSuccess
  | deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseError

export const getDeleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdUrl = (
  id: string,
  etapaId: string
) => {
  return `/api/v1/empregabilidade/vagas/${id}/etapas/${etapaId}`
}

export const deleteApiV1EmpregabilidadeVagasIdEtapasEtapaId = async (
  id: string,
  etapaId: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse>(
    getDeleteApiV1EmpregabilidadeVagasIdEtapasEtapaIdUrl(id, etapaId),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

/**
 * Retorna uma etapa pelo ID
 * @summary Buscar etapa
 */
export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse200 = {
  data: EmpregabilidadeEtapa
  status: 200
}

export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse400 = {
  data: GetApiV1EmpregabilidadeVagasIdEtapasEtapaId400
  status: 400
}

export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse404 = {
  data: GetApiV1EmpregabilidadeVagasIdEtapasEtapaId404
  status: 404
}

export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse500 = {
  data: GetApiV1EmpregabilidadeVagasIdEtapasEtapaId500
  status: 500
}

export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseSuccess =
  getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseError = (
  | getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse400
  | getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse404
  | getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse =
  | getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseSuccess
  | getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseError

export const getGetApiV1EmpregabilidadeVagasIdEtapasEtapaIdUrl = (
  id: string,
  etapaId: string
) => {
  return `/api/v1/empregabilidade/vagas/${id}/etapas/${etapaId}`
}

export const getApiV1EmpregabilidadeVagasIdEtapasEtapaId = async (
  id: string,
  etapaId: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse>(
    getGetApiV1EmpregabilidadeVagasIdEtapasEtapaIdUrl(id, etapaId),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma etapa existente
 * @summary Atualizar etapa
 */
export type putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse200 = {
  data: EmpregabilidadeEtapa
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdEtapasEtapaId400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdEtapasEtapaId500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseSuccess =
  putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseError = (
  | putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse400
  | putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse =
  | putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseSuccess
  | putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponseError

export const getPutApiV1EmpregabilidadeVagasIdEtapasEtapaIdUrl = (
  id: string,
  etapaId: string
) => {
  return `/api/v1/empregabilidade/vagas/${id}/etapas/${etapaId}`
}

export const putApiV1EmpregabilidadeVagasIdEtapasEtapaId = async (
  id: string,
  etapaId: string,
  empregabilidadeEtapa: EmpregabilidadeEtapa,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdEtapasEtapaIdResponse>(
    getPutApiV1EmpregabilidadeVagasIdEtapasEtapaIdUrl(id, etapaId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEtapa),
    }
  )
}
