steps:
  # Create the .env file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "IDENTIDADE_CARIOCA_CLIENT_SECRET=${_IDENTIDADE_CARIOCA_CLIENT_SECRET}" > .env.production && \
        echo "NEXT_PUBLIC_IDENTIDADE_CARIOCA_BASE_URL=https://auth-idrio.apps.rio.gov.br/auth/realms/idrio_cidadao/protocol/openid-connect" >> .env.production && \
        echo "NEXT_PUBLIC_IDENTIDADE_CARIOCA_CLIENT_ID=superapp.apps.rio.gov.br" >> .env.production && \
        echo "NEXT_PUBLIC_IDENTIDADE_CARIOCA_REDIRECT_URI=https://superapp.dados.rio/api/auth/callback/keycloak" >> .env.production
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/superapp:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/superapp:$COMMIT_SHA"]
  # Kustomize: set the image in the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/prod"
    entrypoint: "kustomize"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/project-id/superapp=gcr.io/$PROJECT_ID/superapp:$COMMIT_SHA"
  # Kustomize: apply the kustomization.yaml file
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/prod"
    entrypoint: "kustomize"
    args: ["build", ".", "-o", "prod.yaml"]
  # Deploy the application to the GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: "k8s/prod"
    args:
      - "run"
      - "--filename=prod.yaml"
      - "--location=us-central1"
      - "--cluster=datario"
      - "--project=datario"

images:
  - "gcr.io/$PROJECT_ID/superapp:$COMMIT_SHA"
