/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeModelosTrabalhoId200,
  DeleteApiV1EmpregabilidadeModelosTrabalhoId400,
  DeleteApiV1EmpregabilidadeModelosTrabalhoId500,
  EmpregabilidadeModeloTrabalho,
  EmpregabilidadeModeloTrabalhoBody,
  GetApiV1EmpregabilidadeModelosTrabalho200,
  GetApiV1EmpregabilidadeModelosTrabalho500,
  GetApiV1EmpregabilidadeModelosTrabalhoId400,
  GetApiV1EmpregabilidadeModelosTrabalhoId404,
  GetApiV1EmpregabilidadeModelosTrabalhoParams,
  PostApiV1EmpregabilidadeModelosTrabalho400,
  PostApiV1EmpregabilidadeModelosTrabalho500,
  PutApiV1EmpregabilidadeModelosTrabalhoId400,
  PutApiV1EmpregabilidadeModelosTrabalhoId500,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna uma lista paginada de modelos de trabalho
 * @summary Listar modelos de trabalho
 */
export type getApiV1EmpregabilidadeModelosTrabalhoResponse200 = {
  data: GetApiV1EmpregabilidadeModelosTrabalho200
  status: 200
}

export type getApiV1EmpregabilidadeModelosTrabalhoResponse500 = {
  data: GetApiV1EmpregabilidadeModelosTrabalho500
  status: 500
}

export type getApiV1EmpregabilidadeModelosTrabalhoResponseComposite =
  | getApiV1EmpregabilidadeModelosTrabalhoResponse200
  | getApiV1EmpregabilidadeModelosTrabalhoResponse500

export type getApiV1EmpregabilidadeModelosTrabalhoResponse =
  getApiV1EmpregabilidadeModelosTrabalhoResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeModelosTrabalhoUrl = (
  params?: GetApiV1EmpregabilidadeModelosTrabalhoParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/modelos-trabalho?${stringifiedParams}`
    : `/api/v1/empregabilidade/modelos-trabalho`
}

export const getApiV1EmpregabilidadeModelosTrabalho = async (
  params?: GetApiV1EmpregabilidadeModelosTrabalhoParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeModelosTrabalhoResponse> => {
  return customFetch<getApiV1EmpregabilidadeModelosTrabalhoResponse>(
    getGetApiV1EmpregabilidadeModelosTrabalhoUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria um novo modelo de trabalho
 * @summary Criar modelo de trabalho
 */
export type postApiV1EmpregabilidadeModelosTrabalhoResponse201 = {
  data: EmpregabilidadeModeloTrabalho
  status: 201
}

export type postApiV1EmpregabilidadeModelosTrabalhoResponse400 = {
  data: PostApiV1EmpregabilidadeModelosTrabalho400
  status: 400
}

export type postApiV1EmpregabilidadeModelosTrabalhoResponse500 = {
  data: PostApiV1EmpregabilidadeModelosTrabalho500
  status: 500
}

export type postApiV1EmpregabilidadeModelosTrabalhoResponseComposite =
  | postApiV1EmpregabilidadeModelosTrabalhoResponse201
  | postApiV1EmpregabilidadeModelosTrabalhoResponse400
  | postApiV1EmpregabilidadeModelosTrabalhoResponse500

export type postApiV1EmpregabilidadeModelosTrabalhoResponse =
  postApiV1EmpregabilidadeModelosTrabalhoResponseComposite & {
    headers: Headers
  }

export const getPostApiV1EmpregabilidadeModelosTrabalhoUrl = () => {
  return `/api/v1/empregabilidade/modelos-trabalho`
}

export const postApiV1EmpregabilidadeModelosTrabalho = async (
  empregabilidadeModeloTrabalhoBody: EmpregabilidadeModeloTrabalhoBody,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeModelosTrabalhoResponse> => {
  return customFetch<postApiV1EmpregabilidadeModelosTrabalhoResponse>(
    getPostApiV1EmpregabilidadeModelosTrabalhoUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeModeloTrabalhoBody),
    }
  )
}

/**
 * Retorna um modelo de trabalho específico
 * @summary Buscar modelo de trabalho por ID
 */
export type getApiV1EmpregabilidadeModelosTrabalhoIdResponse200 = {
  data: EmpregabilidadeModeloTrabalho
  status: 200
}

export type getApiV1EmpregabilidadeModelosTrabalhoIdResponse400 = {
  data: GetApiV1EmpregabilidadeModelosTrabalhoId400
  status: 400
}

export type getApiV1EmpregabilidadeModelosTrabalhoIdResponse404 = {
  data: GetApiV1EmpregabilidadeModelosTrabalhoId404
  status: 404
}

export type getApiV1EmpregabilidadeModelosTrabalhoIdResponseComposite =
  | getApiV1EmpregabilidadeModelosTrabalhoIdResponse200
  | getApiV1EmpregabilidadeModelosTrabalhoIdResponse400
  | getApiV1EmpregabilidadeModelosTrabalhoIdResponse404

export type getApiV1EmpregabilidadeModelosTrabalhoIdResponse =
  getApiV1EmpregabilidadeModelosTrabalhoIdResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeModelosTrabalhoIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/modelos-trabalho/${id}`
}

export const getApiV1EmpregabilidadeModelosTrabalhoId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeModelosTrabalhoIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeModelosTrabalhoIdResponse>(
    getGetApiV1EmpregabilidadeModelosTrabalhoIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza um modelo de trabalho existente
 * @summary Atualizar modelo de trabalho
 */
export type putApiV1EmpregabilidadeModelosTrabalhoIdResponse200 = {
  data: EmpregabilidadeModeloTrabalho
  status: 200
}

export type putApiV1EmpregabilidadeModelosTrabalhoIdResponse400 = {
  data: PutApiV1EmpregabilidadeModelosTrabalhoId400
  status: 400
}

export type putApiV1EmpregabilidadeModelosTrabalhoIdResponse500 = {
  data: PutApiV1EmpregabilidadeModelosTrabalhoId500
  status: 500
}

export type putApiV1EmpregabilidadeModelosTrabalhoIdResponseComposite =
  | putApiV1EmpregabilidadeModelosTrabalhoIdResponse200
  | putApiV1EmpregabilidadeModelosTrabalhoIdResponse400
  | putApiV1EmpregabilidadeModelosTrabalhoIdResponse500

export type putApiV1EmpregabilidadeModelosTrabalhoIdResponse =
  putApiV1EmpregabilidadeModelosTrabalhoIdResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeModelosTrabalhoIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/modelos-trabalho/${id}`
}

export const putApiV1EmpregabilidadeModelosTrabalhoId = async (
  id: string,
  empregabilidadeModeloTrabalhoBody: EmpregabilidadeModeloTrabalhoBody,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeModelosTrabalhoIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeModelosTrabalhoIdResponse>(
    getPutApiV1EmpregabilidadeModelosTrabalhoIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeModeloTrabalhoBody),
    }
  )
}

/**
 * Remove um modelo de trabalho
 * @summary Excluir modelo de trabalho
 */
export type deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeModelosTrabalhoId200
  status: 200
}

export type deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeModelosTrabalhoId400
  status: 400
}

export type deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeModelosTrabalhoId500
  status: 500
}

export type deleteApiV1EmpregabilidadeModelosTrabalhoIdResponseComposite =
  | deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse200
  | deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse400
  | deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse500

export type deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse =
  deleteApiV1EmpregabilidadeModelosTrabalhoIdResponseComposite & {
    headers: Headers
  }

export const getDeleteApiV1EmpregabilidadeModelosTrabalhoIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/modelos-trabalho/${id}`
}

export const deleteApiV1EmpregabilidadeModelosTrabalhoId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeModelosTrabalhoIdResponse>(
    getDeleteApiV1EmpregabilidadeModelosTrabalhoIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
