/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  EmpregabilidadeTermosUso,
  GetApiV1EmpregabilidadeTermosUsoCpf200,
  GetApiV1EmpregabilidadeTermosUsoCpf500,
  GetApiV1EmpregabilidadeTermosUsoCpfDetails404,
  GetApiV1EmpregabilidadeTermosUsoCpfDetails500,
  PutApiV1EmpregabilidadeTermosUsoCpfAccept200,
  PutApiV1EmpregabilidadeTermosUsoCpfAccept500,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Verifica se o usuário aceitou os termos de uso
 * @summary Verificar aceite dos termos
 */
export type getApiV1EmpregabilidadeTermosUsoCpfResponse200 = {
  data: GetApiV1EmpregabilidadeTermosUsoCpf200
  status: 200
}

export type getApiV1EmpregabilidadeTermosUsoCpfResponse500 = {
  data: GetApiV1EmpregabilidadeTermosUsoCpf500
  status: 500
}

export type getApiV1EmpregabilidadeTermosUsoCpfResponseComposite =
  | getApiV1EmpregabilidadeTermosUsoCpfResponse200
  | getApiV1EmpregabilidadeTermosUsoCpfResponse500

export type getApiV1EmpregabilidadeTermosUsoCpfResponse =
  getApiV1EmpregabilidadeTermosUsoCpfResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeTermosUsoCpfUrl = (cpf: string) => {
  return `/api/v1/empregabilidade/termos-uso/${cpf}`
}

export const getApiV1EmpregabilidadeTermosUsoCpf = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeTermosUsoCpfResponse> => {
  return customFetch<getApiV1EmpregabilidadeTermosUsoCpfResponse>(
    getGetApiV1EmpregabilidadeTermosUsoCpfUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Registra o aceite dos termos de uso pelo usuário
 * @summary Aceitar termos de uso
 */
export type putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse200 = {
  data: PutApiV1EmpregabilidadeTermosUsoCpfAccept200
  status: 200
}

export type putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse500 = {
  data: PutApiV1EmpregabilidadeTermosUsoCpfAccept500
  status: 500
}

export type putApiV1EmpregabilidadeTermosUsoCpfAcceptResponseComposite =
  | putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse200
  | putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse500

export type putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse =
  putApiV1EmpregabilidadeTermosUsoCpfAcceptResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeTermosUsoCpfAcceptUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/termos-uso/${cpf}/accept`
}

export const putApiV1EmpregabilidadeTermosUsoCpfAccept = async (
  cpf: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse> => {
  return customFetch<putApiV1EmpregabilidadeTermosUsoCpfAcceptResponse>(
    getPutApiV1EmpregabilidadeTermosUsoCpfAcceptUrl(cpf),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Retorna os detalhes do aceite dos termos de uso
 * @summary Buscar detalhes dos termos
 */
export type getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse200 = {
  data: EmpregabilidadeTermosUso
  status: 200
}

export type getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse404 = {
  data: GetApiV1EmpregabilidadeTermosUsoCpfDetails404
  status: 404
}

export type getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse500 = {
  data: GetApiV1EmpregabilidadeTermosUsoCpfDetails500
  status: 500
}

export type getApiV1EmpregabilidadeTermosUsoCpfDetailsResponseComposite =
  | getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse200
  | getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse404
  | getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse500

export type getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse =
  getApiV1EmpregabilidadeTermosUsoCpfDetailsResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeTermosUsoCpfDetailsUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/termos-uso/${cpf}/details`
}

export const getApiV1EmpregabilidadeTermosUsoCpfDetails = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse> => {
  return customFetch<getApiV1EmpregabilidadeTermosUsoCpfDetailsResponse>(
    getGetApiV1EmpregabilidadeTermosUsoCpfDetailsUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}
