/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API Dívida Ativa Imobiliária - Pref.Rio (CONTRATO PROVISÓRIO)
 * Contrato **provisório** para os serviços de dívida ativa imobiliária do portal do cidadão:
 * cadastro de imóveis, consulta de débitos/CDAs, simulação de parcelamento, abertura de
 * requerimento e acompanhamento.
 *
 * ATENÇÃO: este documento **não** foi ratificado pela equipe da API (Quarkus). Foi escrito
 * unilateralmente pelo time de front para permitir desenvolvimento em paralelo ao back-end
 * (decisões D8 e D13 do plano do módulo). Cada campo, formato e código de erro aqui é uma
 * premissa registrada em `docs/divida-ativa.md`, e será reconciliado com o contrato oficial
 * na fase de integração.
 *
 * As regras fiscais continuam nos sistemas corporativos (DAM/PGM). Esta API é camada de
 * integração; o front apenas reflete os estados e erros que ela devolve.
 *
 * Identidade: o cidadão é derivado do Bearer token (Keycloak) pela própria API. Nenhum
 * endpoint recebe CPF por path, query ou body.
 *
 * OpenAPI spec version: 0.1.0-provisorio
 */
import type { SituacaoCda } from './situacaoCda'

/**
 * Uma Certidão de Dívida Ativa (CDA) do imóvel.
 */
export interface Debito {
  numeroCda: string
  /** Exercício (ano) a que o débito se refere. */
  exercicio?: number
  /** Tributo de origem do débito. */
  tributo?: string
  situacao?: SituacaoCda
  /** Elegibilidade para parcelamento, decidida pelo sistema fiscal. */
  parcelavel?: boolean
  dataVencimento?: string
  valorPrincipal?: number
  /** Valor consolidado com encargos na data de referência. */
  valorAtualizado?: number
  /** Data em que os valores foram calculados. */
  dataReferenciaValor?: string
}
