/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis
 * Cadastro local de inscricoes imobiliarias e servicos de IPTU / Divida Ativa.
 * OpenAPI spec version: 1.0.0
 */
import type { CdaResponse } from './cdaResponse'
import type { GuiaDamResponse } from './guiaDamResponse'
import type { ImovelResponse } from './imovelResponse'
import type { OpcaoDividaAtivaResponse } from './opcaoDividaAtivaResponse'

/**
 * Consulta de Divida Ativa de um imovel. Serve tanto a consulta do imovel cadastrado quanto a consulta avulsa por CDA, execucao fiscal ou guia.
 */
export interface DividaAtivaConsultaResponse {
  /** Imovel da consulta. No fluxo cadastrado vem do banco local (com id e dataInclusao); na consulta avulsa e montado com a inscricao encontrada e o endereco da Fazenda, sem id. Nulo na consulta avulsa cujo resultado abrange mais de um imovel (execucao fiscal): cada CDA traz a propria inscricaoImobiliaria. */
  imovel?: ImovelResponse
  /** Indica se o imovel ja esta em Meus Imoveis do CPF autenticado. Falso na consulta avulsa de imovel nao cadastrado: o parcelamento segue pelas CDAs (/divida-ativa/parcelamentos/simular e /divida-ativa/requerimentos), mas as guias exigem o cadastro, por isso opcoes traz so PARCELAMENTO, ACOMPANHAR_REQUERIMENTO e FAQ. */
  imovelCadastrado?: boolean
  /** CDAs nao parceladas (datagrid 1 do legado T04). */
  cdas?: CdaResponse[]
  /** Quantidade de CDAs nao parceladas. */
  totalCdas?: number
  /** Guias de liquidacao / CDAs parceladas (datagrid 2 do legado T04). */
  guiasParceladas?: GuiaDamResponse[]
  /** Quantidade de guias parceladas (sem duplicidade de numero). */
  totalParcelado?: number
  /** totalCdas + totalParcelado (compativel com totalCDAs do legado). */
  totalDebitos?: number
  /** Opcoes de servico do menu de Divida Ativa. */
  opcoes?: OpcaoDividaAtivaResponse[]
  /** Mensagem amigavel quando nao ha debitos ou quando a consulta e parcial. */
  mensagem?: string
}
