/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis
 * Cadastro local de inscricoes imobiliarias e servicos de IPTU / Divida Ativa.
 * OpenAPI spec version: 1.0.0
 */

export type GetImoveisInscricaoConsultaParams = {
  /**
   * Exercicio usado na geracao do token da segunda via. Para anos anteriores, informar explicitamente; se omitido, usa o ano corrente.
   */
  exercicio?: string
}
