/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis
 * Cadastro local de inscricoes imobiliarias e servicos de IPTU / Divida Ativa.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Opcao de servico de Divida Ativa (menu do portlet legado).
 */
export interface OpcaoDividaAtivaResponse {
  /** Codigo interno da opcao. */
  codigo?: string
  /** Titulo para exibicao. */
  titulo?: string
  /** Descricao da acao. */
  descricao?: string
  /** Indica se a opcao pode ser usada no momento. */
  disponivel?: boolean
  /** Mensagem de apoio ou indisponibilidade. */
  mensagem?: string
  /** URL externa quando o servico e redirecionamento (ex.: adiantamento, FAQ). */
  urlExterna?: string
}
