/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis
 * Cadastro local de inscricoes imobiliarias e servicos de IPTU / Divida Ativa.
 * OpenAPI spec version: 1.0.0
 */

export interface RequerimentoParcelamentoResponse {
  numProtocoloRequerimentoParcelamento?: string
  dataSolicitacao?: string
  datPrevisaoEntrega?: string
  datResposta?: string
  situacaoId?: string
  nomeContribuinte?: string
  requerimentoGuiaPagamentoId?: string
  txtMotivoRejeicao?: string
  numCpfRequerente?: string
  nomeComprovanteEntregaRequerimento?: string
  anoRequerimento?: string
  urlComprovante?: string
  mensagemErro?: string
}
