/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentoDamRequest } from './documentoDamRequest'

export interface RequerimentoParcelamentoRequest {
  cdas?: string[]
  qtdeParcelas?: string
  dtVencimento?: string
  valor1aParcela?: string
  descVinculoRequerente?: string
  nomRequerente?: string
  numTelefoneRequerente?: string
  txtEmailRequerente?: string
  nomeCorr?: string
  tipoDoc?: string
  numCPFCorr?: string
  numCEPCorr?: string
  txtLogradouroEnderecoCorr?: string
  numEnderecoCorr?: string
  txtComplementoEnderecoCorr?: string
  txtBairroEnderecoCorr?: string
  txtCidadeEnderecoCorr?: string
  txtUfEnderecoCorr?: string
  numTelefoneCorr?: string
  txtEmailCorr?: string
  ip?: string
  tipoAutenticacao?: string
  declaracaoAceita?: boolean
  senha?: string
  documentos?: DocumentoDamRequest[]
}
