/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis API
 * OpenAPI spec version: 1.0.0
 */

export interface RequerimentoCertidaoRequest {
  tipoPessoa?: string
  cpfCnpj?: string
  nomeContribuinte?: string
  inscricaoMunicipal?: string
  nomeRequerente?: string
  telefone?: string
  email?: string
  motivoCertidao?: string
  antigasDenominacoes?: string
  registradoJUCERJA?: string
  registradoRCPJ?: string
  dataNascimentoContribuinte?: string
  dataNascimentoRequerente?: string
  cep?: string
  logradouro?: string
  numero?: string
  complemento?: string
  bairro?: string
  cidade?: string
  uf?: string
}
