/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis
 * Cadastro local de inscricoes imobiliarias e servicos de IPTU / Divida Ativa.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do documento anexado ao requerimento de parcelamento.
 */
export type TipoDocumentoDam =
  (typeof TipoDocumentoDam)[keyof typeof TipoDocumentoDam]

export const TipoDocumentoDam = {
  IDENTIDADE: 'IDENTIDADE',
  CPF: 'CPF',
  IDENTIDADE_OUTORGANTE: 'IDENTIDADE_OUTORGANTE',
  CPF_OUTORGANTE: 'CPF_OUTORGANTE',
  PROCURACAO: 'PROCURACAO',
  ESCRITURA: 'ESCRITURA',
  CNPJ: 'CNPJ',
  REGISTRO_EMPRESA: 'REGISTRO_EMPRESA',
  ATA: 'ATA',
  OUTROS: 'OUTROS',
} as const
