import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// Lista completa de bairros do Rio de Janeiro
const BAIRROS_RIO = [
  'Abolição',
  'Acari',
  'Água Santa',
  'Alto da Boa Vista',
  'Anchieta',
  'Andaraí',
  'Anil',
  'Argentino',
  'Bancários',
  'Bangu',
  'Barra da Tijuca',
  'Barra de Guaratiba',
  'Barra Olímpica',
  'Barros Filho',
  'Benfica',
  'Bento Ribeiro',
  'Bonsucesso',
  'Botafogo',
  'Brás de Pina',
  'Cachambi',
  'Cacuia',
  'Caju',
  'Camorim',
  'Campinho',
  'Campo dos Afonsos',
  'Campo Grande',
  'Cascadura',
  'Catete',
  'Catumbi',
  'Cavalcanti',
  'Centro',
  'Cidade de Deus',
  'Cidade Nova',
  'Cidade Universitária',
  'Cocotá',
  'Coelho Neto',
  'Colégio',
  'Complexo do Alemão',
  'Copacabana',
  'Cordovil',
  'Cosme Velho',
  'Cosmos',
  'Costa Barros',
  'Curicica',
  'Del Castilho',
  'Deodoro',
  'Encantado',
  'Engenheiro Leal',
  'Engenho da Rainha',
  'Engenho de Dentro',
  'Engenho Novo',
  'Estácio',
  'Flamengo',
  'Freguesia (Ilha)',
  'Freguesia (Jacarepaguá)',
  'Galeão',
  'Gamboa',
  'Gardênia Azul',
  'Gávea',
  'Gericinó',
  'Glória',
  'Grajaú',
  'Grumari',
  'Guadalupe',
  'Guaratiba',
  'Higienópolis',
  'Honório Gurgel',
  'Humaitá',
  'Ilha de Guaratiba',
  'Imperial de São Cristóvão',
  'Inhaúma',
  'Inhoaíba',
  'Ipanema',
  'Irajá',
  'Itanhangá',
  'Jabour',
  'Jacaré',
  'Jacarepaguá',
  'Jacarezinho',
  'Jardim América',
  'Jardim Botânico',
  'Jardim Carioca',
  'Jardim Guanabara',
  'Jardim Sulacap',
  'Joá',
  'Lagoa',
  'Lapa',
  'Laranjeiras',
  'Leblon',
  'Leme',
  'Lins de Vasconcelos',
  'Madureira',
  'Magalhães Bastos',
  'Mangueira',
  'Manguinhos',
  'Maracanã',
  'Maré',
  'Marechal Hermes',
  'Maria da Graça',
  'Méier',
  'Moneró',
  'Olaria',
  'Osvaldo Cruz',
  'Paciência',
  'Padre Miguel',
  'Paquetá',
  'Parada de Lucas',
  'Parque Anchieta',
  'Parque Colúmbia',
  'Pavuna',
  'Pechincha',
  'Pedra de Guaratiba',
  'Penha',
  'Penha Circular',
  'Piedade',
  'Pilares',
  'Pitangueiras',
  'Portuguesa',
  'Praça da Bandeira',
  'Praça Seca',
  'Praia da Bandeira',
  'Quintino Bocaiúva',
  'Ramos',
  'Realengo',
  'Recreio dos Bandeirantes',
  'Riachuelo',
  'Ribeira',
  'Ricardo de Albuquerque',
  'Rio Comprido',
  'Rocha',
  'Rocha Miranda',
  'Rocinha',
  'Sampaio',
  'Santa Cruz',
  'Santa Teresa',
  'Santíssimo',
  'Santo Cristo',
  'São Conrado',
  'São Francisco Xavier',
  'Saúde',
  'Senador Camará',
  'Senador Vasconcelos',
  'Sepetiba',
  'Tanque',
  'Taquara',
  'Tauá',
  'Tijuca',
  'Todos os Santos',
  'Tomás Coelho',
  'Turiaçú',
  'Urca',
  'Vargem Grande',
  'Vargem Pequena',
  'Vasco da Gama',
  'Vaz Lobo',
  'Vicente de Carvalho',
  'Vidigal',
  'Vigário Geral',
  'Vila da Penha',
  'Vila Isabel',
  'Vila Kennedy',
  'Vila Kosmos',
  'Vila Militar',
  'Vila Valqueire',
  'Vista Alegre',
  'Zumbi',
].sort()

const PAGE_SIZE = 10

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl
  const search = searchParams.get('search')?.trim().toLowerCase() ?? ''
  const page = Math.max(1, Number(searchParams.get('page') ?? 1))

  const filtered = search
    ? BAIRROS_RIO.filter(b => b.toLowerCase().includes(search))
    : BAIRROS_RIO

  const total = filtered.length
  const offset = (page - 1) * PAGE_SIZE
  const data = filtered.slice(offset, offset + PAGE_SIZE)

  return NextResponse.json({
    data,
    meta: {
      page,
      page_size: PAGE_SIZE,
      total,
      has_more: offset + data.length < total,
    },
  })
}
