/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type {
  GetApiV1CategoriesCategorySubcategories400,
  GetApiV1CategoriesCategorySubcategories500,
  GetApiV1CategoriesCategorySubcategoriesParams,
  GetApiV1SubcategoriesSubcategoryServices400,
  GetApiV1SubcategoriesSubcategoryServices500,
  GetApiV1SubcategoriesSubcategoryServicesParams,
  ModelsSubcategoryResponse,
  ModelsSubcategoryServicesResponse,
} from '.././models'

import { customFetchBuscaSearch } from '../../../custom-fetch-busca-search'

/**
 * Retorna lista de subcategorias dentro de uma categoria pai, ordenadas por popularidade, quantidade de serviços ou ordem alfabética. Subcategorias são extraídas dinamicamente dos serviços via facet search no Typesense.

**Casos de Uso:**
1. Listar subcategorias: GET /api/v1/categories/Educação/subcategories
2. Ordenar por quantidade: GET /api/v1/categories/Educação/subcategories?sort_by=count&order=desc
3. Incluir vazias: GET /api/v1/categories/Educação/subcategories?include_empty=true
 * @summary Lista subcategorias de uma categoria específica
 */
export type getApiV1CategoriesCategorySubcategoriesResponse200 = {
  data: ModelsSubcategoryResponse
  status: 200
}

export type getApiV1CategoriesCategorySubcategoriesResponse400 = {
  data: GetApiV1CategoriesCategorySubcategories400
  status: 400
}

export type getApiV1CategoriesCategorySubcategoriesResponse500 = {
  data: GetApiV1CategoriesCategorySubcategories500
  status: 500
}

export type getApiV1CategoriesCategorySubcategoriesResponseComposite =
  | getApiV1CategoriesCategorySubcategoriesResponse200
  | getApiV1CategoriesCategorySubcategoriesResponse400
  | getApiV1CategoriesCategorySubcategoriesResponse500

export type getApiV1CategoriesCategorySubcategoriesResponse =
  getApiV1CategoriesCategorySubcategoriesResponseComposite & {
    headers: Headers
  }

export const getGetApiV1CategoriesCategorySubcategoriesUrl = (
  category: string,
  params?: GetApiV1CategoriesCategorySubcategoriesParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/categories/${category}/subcategories?${stringifiedParams}`
    : `/api/v1/categories/${category}/subcategories`
}

export const getApiV1CategoriesCategorySubcategories = async (
  category: string,
  params?: GetApiV1CategoriesCategorySubcategoriesParams,
  options?: RequestInit
): Promise<getApiV1CategoriesCategorySubcategoriesResponse> => {
  return customFetchBuscaSearch<getApiV1CategoriesCategorySubcategoriesResponse>(
    getGetApiV1CategoriesCategorySubcategoriesUrl(category, params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Retorna serviços filtrados por subcategoria, com paginação. Serviços são ordenados por última atualização (mais recentes primeiro).

**Casos de Uso:**
1. Listar serviços: GET /api/v1/subcategories/Ensino%20Fundamental/services
2. Paginar resultados: GET /api/v1/subcategories/Ensino%20Fundamental/services?page=2&per_page=20
3. Incluir inativos: GET /api/v1/subcategories/Ensino%20Fundamental/services?include_inactive=true
4. Filtrar por categoria pai: GET /api/v1/subcategories/Certidões/services?category=Documentos
 * @summary Lista serviços de uma subcategoria específica
 */
export type getApiV1SubcategoriesSubcategoryServicesResponse200 = {
  data: ModelsSubcategoryServicesResponse
  status: 200
}

export type getApiV1SubcategoriesSubcategoryServicesResponse400 = {
  data: GetApiV1SubcategoriesSubcategoryServices400
  status: 400
}

export type getApiV1SubcategoriesSubcategoryServicesResponse500 = {
  data: GetApiV1SubcategoriesSubcategoryServices500
  status: 500
}

export type getApiV1SubcategoriesSubcategoryServicesResponseComposite =
  | getApiV1SubcategoriesSubcategoryServicesResponse200
  | getApiV1SubcategoriesSubcategoryServicesResponse400
  | getApiV1SubcategoriesSubcategoryServicesResponse500

export type getApiV1SubcategoriesSubcategoryServicesResponse =
  getApiV1SubcategoriesSubcategoryServicesResponseComposite & {
    headers: Headers
  }

export const getGetApiV1SubcategoriesSubcategoryServicesUrl = (
  subcategory: string,
  params?: GetApiV1SubcategoriesSubcategoryServicesParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/subcategories/${subcategory}/services?${stringifiedParams}`
    : `/api/v1/subcategories/${subcategory}/services`
}

export const getApiV1SubcategoriesSubcategoryServices = async (
  subcategory: string,
  params?: GetApiV1SubcategoriesSubcategoryServicesParams,
  options?: RequestInit
): Promise<getApiV1SubcategoriesSubcategoryServicesResponse> => {
  return customFetchBuscaSearch<getApiV1SubcategoriesSubcategoryServicesResponse>(
    getGetApiV1SubcategoriesSubcategoryServicesUrl(subcategory, params),
    {
      ...options,
      method: 'GET',
    }
  )
}
