/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type {
  GetCnaesParams,
  HandlersErrorResponse,
  ModelsCNAEListResponse,
} from '.././models'

import { customFetch } from '../../../custom-fetch'

/**
 * Recupera a lista paginada de CNAEs (Classificação Nacional de Atividades Econômicas) com filtros opcionais
 * @summary Listar CNAEs
 */
export type getCnaesResponse200 = {
  data: ModelsCNAEListResponse
  status: 200
}

export type getCnaesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getCnaesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getCnaesResponseComposite =
  | getCnaesResponse200
  | getCnaesResponse400
  | getCnaesResponse500

export type getCnaesResponse = getCnaesResponseComposite & {
  headers: Headers
}

export const getGetCnaesUrl = (params?: GetCnaesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/cnaes?${stringifiedParams}` : `/cnaes`
}

export const getCnaes = async (
  params?: GetCnaesParams,
  options?: RequestInit
): Promise<getCnaesResponse> => {
  return customFetch<getCnaesResponse>(getGetCnaesUrl(params), {
    ...options,
    method: 'GET',
  })
}
