/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  EmpregabilidadeVaga,
  GetApiPublicEmpregabilidadeVagas200,
  GetApiPublicEmpregabilidadeVagas500,
  GetApiPublicEmpregabilidadeVagasId400,
  GetApiPublicEmpregabilidadeVagasId404,
  GetApiPublicEmpregabilidadeVagasId500,
  GetApiPublicEmpregabilidadeVagasParams,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna lista paginada de vagas publicadas (apenas vagas ativas)
 * @summary Listar vagas públicas
 */
export type getApiPublicEmpregabilidadeVagasResponse200 = {
  data: GetApiPublicEmpregabilidadeVagas200
  status: 200
}

export type getApiPublicEmpregabilidadeVagasResponse500 = {
  data: GetApiPublicEmpregabilidadeVagas500
  status: 500
}

export type getApiPublicEmpregabilidadeVagasResponseComposite =
  | getApiPublicEmpregabilidadeVagasResponse200
  | getApiPublicEmpregabilidadeVagasResponse500

export type getApiPublicEmpregabilidadeVagasResponse =
  getApiPublicEmpregabilidadeVagasResponseComposite & {
    headers: Headers
  }

export const getGetApiPublicEmpregabilidadeVagasUrl = (
  params?: GetApiPublicEmpregabilidadeVagasParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/public/empregabilidade/vagas?${stringifiedParams}`
    : `/api/public/empregabilidade/vagas`
}

export const getApiPublicEmpregabilidadeVagas = async (
  params?: GetApiPublicEmpregabilidadeVagasParams,
  options?: RequestInit
): Promise<getApiPublicEmpregabilidadeVagasResponse> => {
  return customFetch<getApiPublicEmpregabilidadeVagasResponse>(
    getGetApiPublicEmpregabilidadeVagasUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Retorna uma vaga publicada pelo ID (apenas se estiver ativa)
 * @summary Buscar vaga pública
 */
export type getApiPublicEmpregabilidadeVagasIdResponse200 = {
  data: EmpregabilidadeVaga
  status: 200
}

export type getApiPublicEmpregabilidadeVagasIdResponse400 = {
  data: GetApiPublicEmpregabilidadeVagasId400
  status: 400
}

export type getApiPublicEmpregabilidadeVagasIdResponse404 = {
  data: GetApiPublicEmpregabilidadeVagasId404
  status: 404
}

export type getApiPublicEmpregabilidadeVagasIdResponse500 = {
  data: GetApiPublicEmpregabilidadeVagasId500
  status: 500
}

export type getApiPublicEmpregabilidadeVagasIdResponseComposite =
  | getApiPublicEmpregabilidadeVagasIdResponse200
  | getApiPublicEmpregabilidadeVagasIdResponse400
  | getApiPublicEmpregabilidadeVagasIdResponse404
  | getApiPublicEmpregabilidadeVagasIdResponse500

export type getApiPublicEmpregabilidadeVagasIdResponse =
  getApiPublicEmpregabilidadeVagasIdResponseComposite & {
    headers: Headers
  }

export const getGetApiPublicEmpregabilidadeVagasIdUrl = (id: string) => {
  return `/api/public/empregabilidade/vagas/${id}`
}

export const getApiPublicEmpregabilidadeVagasId = async (
  id: string,
  options?: RequestInit
): Promise<getApiPublicEmpregabilidadeVagasIdResponse> => {
  return customFetch<getApiPublicEmpregabilidadeVagasIdResponse>(
    getGetApiPublicEmpregabilidadeVagasIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}
