export interface CountryCode {
  id: string
  name: string
  code: string
}

export const COUNTRY_CODES: CountryCode[] = [
  { id: 'af', name: 'Afeganistão', code: '+93' },
  { id: 'za', name: 'África do Sul', code: '+27' },
  { id: 'al', name: 'Albânia', code: '+355' },
  { id: 'de', name: 'Alemanha', code: '+49' },
  { id: 'ad', name: 'Andorra', code: '+376' },
  { id: 'ao', name: 'Angola', code: '+244' },
  { id: 'ar', name: 'Argentina', code: '+54' },
  { id: 'am', name: 'Armênia', code: '+374' },
  { id: 'au', name: 'Austrália', code: '+61' },
  { id: 'at', name: 'Áustria', code: '+43' },
  { id: 'az', name: 'Azerbaijão', code: '+994' },
  { id: 'bs', name: 'Bahamas', code: '+1' },
  { id: 'bd', name: 'Bangladesh', code: '+880' },
  { id: 'bb', name: 'Barbados', code: '+1' },
  { id: 'be', name: 'Bélgica', code: '+32' },
  { id: 'bz', name: 'Belize', code: '+501' },
  { id: 'bj', name: 'Benin', code: '+229' },
  { id: 'bm', name: 'Bermudas', code: '+1' },
  { id: 'bo', name: 'Bolívia', code: '+591' },
  { id: 'ba', name: 'Bósnia e Herzegovina', code: '+387' },
  { id: 'bw', name: 'Botsuana', code: '+267' },
  { id: 'br', name: 'Brasil', code: '+55' },
  { id: 'bn', name: 'Brunei', code: '+673' },
  { id: 'bg', name: 'Bulgária', code: '+359' },
  { id: 'bf', name: 'Burkina Faso', code: '+226' },
  { id: 'bi', name: 'Burundi', code: '+257' },
  { id: 'bt', name: 'Butão', code: '+975' },
  { id: 'cv', name: 'Cabo Verde', code: '+238' },
  { id: 'cm', name: 'Camarões', code: '+237' },
  { id: 'kh', name: 'Camboja', code: '+855' },
  { id: 'ca', name: 'Canadá', code: '+1' },
  { id: 'qa', name: 'Catar', code: '+974' },
  { id: 'kz', name: 'Cazaquistão', code: '+7' },
  { id: 'td', name: 'Chade', code: '+235' },
  { id: 'cl', name: 'Chile', code: '+56' },
  { id: 'cn', name: 'China', code: '+86' },
  { id: 'cy', name: 'Chipre', code: '+357' },
  { id: 'co', name: 'Colômbia', code: '+57' },
  { id: 'km', name: 'Comores', code: '+269' },
  { id: 'cg', name: 'Congo', code: '+242' },
  { id: 'kp', name: 'Coreia do Norte', code: '+850' },
  { id: 'kr', name: 'Coreia do Sul', code: '+82' },
  { id: 'ci', name: 'Costa do Marfim', code: '+225' },
  { id: 'cr', name: 'Costa Rica', code: '+506' },
  { id: 'hr', name: 'Croácia', code: '+385' },
  { id: 'cu', name: 'Cuba', code: '+53' },
  { id: 'dk', name: 'Dinamarca', code: '+45' },
  { id: 'dj', name: 'Djibuti', code: '+253' },
  { id: 'dm', name: 'Dominica', code: '+1' },
  { id: 'eg', name: 'Egito', code: '+20' },
  { id: 'sv', name: 'El Salvador', code: '+503' },
  { id: 'ae', name: 'Emirados Árabes Unidos', code: '+971' },
  { id: 'ec', name: 'Equador', code: '+593' },
  { id: 'er', name: 'Eritreia', code: '+291' },
  { id: 'sk', name: 'Eslováquia', code: '+421' },
  { id: 'si', name: 'Eslovênia', code: '+386' },
  { id: 'es', name: 'Espanha', code: '+34' },
  { id: 'us', name: 'Estados Unidos', code: '+1' },
  { id: 'ee', name: 'Estônia', code: '+372' },
  { id: 'et', name: 'Etiópia', code: '+251' },
  { id: 'fj', name: 'Fiji', code: '+679' },
  { id: 'ph', name: 'Filipinas', code: '+63' },
  { id: 'fi', name: 'Finlândia', code: '+358' },
  { id: 'fr', name: 'França', code: '+33' },
  { id: 'ga', name: 'Gabão', code: '+241' },
  { id: 'gm', name: 'Gâmbia', code: '+220' },
  { id: 'gh', name: 'Gana', code: '+233' },
  { id: 'ge', name: 'Geórgia', code: '+995' },
  { id: 'gd', name: 'Granada', code: '+1' },
  { id: 'gr', name: 'Grécia', code: '+30' },
  { id: 'gt', name: 'Guatemala', code: '+502' },
  { id: 'gy', name: 'Guiana', code: '+592' },
  { id: 'gn', name: 'Guiné', code: '+224' },
  { id: 'gw', name: 'Guiné-Bissau', code: '+245' },
  { id: 'gq', name: 'Guiné Equatorial', code: '+240' },
  { id: 'ht', name: 'Haiti', code: '+509' },
  { id: 'hn', name: 'Honduras', code: '+504' },
  { id: 'hu', name: 'Hungria', code: '+36' },
  { id: 'ye', name: 'Iêmen', code: '+967' },
  { id: 'mh', name: 'Ilhas Marshall', code: '+692' },
  { id: 'sb', name: 'Ilhas Salomão', code: '+677' },
  { id: 'in', name: 'Índia', code: '+91' },
  { id: 'id', name: 'Indonésia', code: '+62' },
  { id: 'ir', name: 'Irã', code: '+98' },
  { id: 'iq', name: 'Iraque', code: '+964' },
  { id: 'ie', name: 'Irlanda', code: '+353' },
  { id: 'is', name: 'Islândia', code: '+354' },
  { id: 'il', name: 'Israel', code: '+972' },
  { id: 'it', name: 'Itália', code: '+39' },
  { id: 'jm', name: 'Jamaica', code: '+1' },
  { id: 'jp', name: 'Japão', code: '+81' },
  { id: 'jo', name: 'Jordânia', code: '+962' },
  { id: 'kw', name: 'Kuwait', code: '+965' },
  { id: 'la', name: 'Laos', code: '+856' },
  { id: 'ls', name: 'Lesoto', code: '+266' },
  { id: 'lv', name: 'Letônia', code: '+371' },
  { id: 'lb', name: 'Líbano', code: '+961' },
  { id: 'lr', name: 'Libéria', code: '+231' },
  { id: 'ly', name: 'Líbia', code: '+218' },
  { id: 'li', name: 'Liechtenstein', code: '+423' },
  { id: 'lt', name: 'Lituânia', code: '+370' },
  { id: 'lu', name: 'Luxemburgo', code: '+352' },
  { id: 'mk', name: 'Macedônia do Norte', code: '+389' },
  { id: 'mg', name: 'Madagascar', code: '+261' },
  { id: 'my', name: 'Malásia', code: '+60' },
  { id: 'mw', name: 'Malawi', code: '+265' },
  { id: 'mv', name: 'Maldivas', code: '+960' },
  { id: 'ml', name: 'Mali', code: '+223' },
  { id: 'mt', name: 'Malta', code: '+356' },
  { id: 'ma', name: 'Marrocos', code: '+212' },
  { id: 'mu', name: 'Maurício', code: '+230' },
  { id: 'mr', name: 'Mauritânia', code: '+222' },
  { id: 'mx', name: 'México', code: '+52' },
  { id: 'mm', name: 'Mianmar', code: '+95' },
  { id: 'fm', name: 'Micronésia', code: '+691' },
  { id: 'mz', name: 'Moçambique', code: '+258' },
  { id: 'md', name: 'Moldávia', code: '+373' },
  { id: 'mc', name: 'Mônaco', code: '+377' },
  { id: 'mn', name: 'Mongólia', code: '+976' },
  { id: 'me', name: 'Montenegro', code: '+382' },
  { id: 'na', name: 'Namíbia', code: '+264' },
  { id: 'nr', name: 'Nauru', code: '+674' },
  { id: 'np', name: 'Nepal', code: '+977' },
  { id: 'ni', name: 'Nicarágua', code: '+505' },
  { id: 'ne', name: 'Níger', code: '+227' },
  { id: 'ng', name: 'Nigéria', code: '+234' },
  { id: 'no', name: 'Noruega', code: '+47' },
  { id: 'nz', name: 'Nova Zelândia', code: '+64' },
  { id: 'om', name: 'Omã', code: '+968' },
  { id: 'nl', name: 'Países Baixos', code: '+31' },
  { id: 'pw', name: 'Palau', code: '+680' },
  { id: 'pa', name: 'Panamá', code: '+507' },
  { id: 'pg', name: 'Papua-Nova Guiné', code: '+675' },
  { id: 'pk', name: 'Paquistão', code: '+92' },
  { id: 'py', name: 'Paraguai', code: '+595' },
  { id: 'pe', name: 'Peru', code: '+51' },
  { id: 'pl', name: 'Polônia', code: '+48' },
  { id: 'pt', name: 'Portugal', code: '+351' },
  { id: 'ke', name: 'Quênia', code: '+254' },
  { id: 'kg', name: 'Quirguistão', code: '+996' },
  { id: 'gb', name: 'Reino Unido', code: '+44' },
  { id: 'cf', name: 'República Centro-Africana', code: '+236' },
  { id: 'cz', name: 'República Checa', code: '+420' },
  { id: 'cd', name: 'República Democrática do Congo', code: '+243' },
  { id: 'do', name: 'República Dominicana', code: '+1' },
  { id: 'ro', name: 'Romênia', code: '+40' },
  { id: 'rw', name: 'Ruanda', code: '+250' },
  { id: 'ru', name: 'Rússia', code: '+7' },
  { id: 'ws', name: 'Samoa', code: '+685' },
  { id: 'sm', name: 'San Marino', code: '+378' },
  { id: 'lc', name: 'Santa Lúcia', code: '+1' },
  { id: 'st', name: 'São Tomé e Príncipe', code: '+239' },
  { id: 'sn', name: 'Senegal', code: '+221' },
  { id: 'sl', name: 'Serra Leoa', code: '+232' },
  { id: 'rs', name: 'Sérvia', code: '+381' },
  { id: 'sc', name: 'Seychelles', code: '+248' },
  { id: 'sg', name: 'Singapura', code: '+65' },
  { id: 'sy', name: 'Síria', code: '+963' },
  { id: 'so', name: 'Somália', code: '+252' },
  { id: 'lk', name: 'Sri Lanka', code: '+94' },
  { id: 'sz', name: 'Suazilândia', code: '+268' },
  { id: 'sd', name: 'Sudão', code: '+249' },
  { id: 'ss', name: 'Sudão do Sul', code: '+211' },
  { id: 'se', name: 'Suécia', code: '+46' },
  { id: 'ch', name: 'Suíça', code: '+41' },
  { id: 'sr', name: 'Suriname', code: '+597' },
  { id: 'th', name: 'Tailândia', code: '+66' },
  { id: 'tw', name: 'Taiwan', code: '+886' },
  { id: 'tj', name: 'Tajiquistão', code: '+992' },
  { id: 'tz', name: 'Tanzânia', code: '+255' },
  { id: 'tl', name: 'Timor-Leste', code: '+670' },
  { id: 'tg', name: 'Togo', code: '+228' },
  { id: 'to', name: 'Tonga', code: '+676' },
  { id: 'tt', name: 'Trinidad e Tobago', code: '+1' },
  { id: 'tn', name: 'Tunísia', code: '+216' },
  { id: 'tm', name: 'Turcomenistão', code: '+993' },
  { id: 'tr', name: 'Turquia', code: '+90' },
  { id: 'tv', name: 'Tuvalu', code: '+688' },
  { id: 'ua', name: 'Ucrânia', code: '+380' },
  { id: 'ug', name: 'Uganda', code: '+256' },
  { id: 'uy', name: 'Uruguai', code: '+598' },
  { id: 'uz', name: 'Uzbequistão', code: '+998' },
  { id: 'vu', name: 'Vanuatu', code: '+678' },
  { id: 'va', name: 'Vaticano', code: '+39' },
  { id: 've', name: 'Venezuela', code: '+58' },
  { id: 'vn', name: 'Vietnã', code: '+84' },
  { id: 'zm', name: 'Zâmbia', code: '+260' },
  { id: 'zw', name: 'Zimbábue', code: '+263' },
]
