export interface CountryCode {
  id: string
  name: string
  code: string
  phoneFormat: string // Format pattern using X for digits
  minLength: number // Minimum phone number length (without country code)
  maxLength: number // Maximum phone number length (without country code)
  placeholder: string // Example format for placeholder
}

export const COUNTRY_CODES: CountryCode[] = [
  {
    id: 'af',
    name: 'Afeganistão',
    code: '+93',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '701 234 567',
  },
  {
    id: 'za',
    name: 'África do Sul',
    code: '+27',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '82 123 4567',
  },
  {
    id: 'al',
    name: 'Albânia',
    code: '+355',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '69 123 4567',
  },
  {
    id: 'de',
    name: 'Alemanha',
    code: '+49',
    phoneFormat: 'XXX XXXXXXX',
    minLength: 10,
    maxLength: 12,
    placeholder: '151 1234567',
  },
  {
    id: 'ad',
    name: 'Andorra',
    code: '+376',
    phoneFormat: 'XXX XXX',
    minLength: 6,
    maxLength: 6,
    placeholder: '312 345',
  },
  {
    id: 'ao',
    name: 'Angola',
    code: '+244',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '923 123 456',
  },
  {
    id: 'ar',
    name: 'Argentina',
    code: '+54',
    phoneFormat: '9 XX XXXX-XXXX',
    minLength: 11,
    maxLength: 11,
    placeholder: '9 11 1234-5678',
  },
  {
    id: 'am',
    name: 'Armênia',
    code: '+374',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '77 123 456',
  },
  {
    id: 'au',
    name: 'Austrália',
    code: '+61',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '412 345 678',
  },
  {
    id: 'at',
    name: 'Áustria',
    code: '+43',
    phoneFormat: 'XXX XXXXXXX',
    minLength: 10,
    maxLength: 13,
    placeholder: '664 1234567',
  },
  {
    id: 'az',
    name: 'Azerbaijão',
    code: '+994',
    phoneFormat: 'XX XXX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '50 123 45 67',
  },
  {
    id: 'bs',
    name: 'Bahamas',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(242) 359-1234',
  },
  {
    id: 'bd',
    name: 'Bangladesh',
    code: '+880',
    phoneFormat: 'XXXX-XXXXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '1812-345678',
  },
  {
    id: 'bb',
    name: 'Barbados',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(246) 250-1234',
  },
  {
    id: 'be',
    name: 'Bélgica',
    code: '+32',
    phoneFormat: 'XXX XX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '470 12 34 56',
  },
  {
    id: 'bz',
    name: 'Belize',
    code: '+501',
    phoneFormat: 'XXX-XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '622-1234',
  },
  {
    id: 'bj',
    name: 'Benin',
    code: '+229',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '90 12 34 56',
  },
  {
    id: 'bm',
    name: 'Bermudas',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(441) 370-1234',
  },
  {
    id: 'bo',
    name: 'Bolívia',
    code: '+591',
    phoneFormat: 'X XXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '7 123 4567',
  },
  {
    id: 'ba',
    name: 'Bósnia e Herzegovina',
    code: '+387',
    phoneFormat: 'XX-XXX-XXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '61-123-456',
  },
  {
    id: 'bw',
    name: 'Botsuana',
    code: '+267',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '71 123 456',
  },
  {
    id: 'br',
    name: 'Brasil',
    code: '+55',
    phoneFormat: '(XX) XXXXX-XXXX',
    minLength: 11,
    maxLength: 11,
    placeholder: '(21) 99999-9999',
  },
  {
    id: 'bn',
    name: 'Brunei',
    code: '+673',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '712 3456',
  },
  {
    id: 'bg',
    name: 'Bulgária',
    code: '+359',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '48 123 4567',
  },
  {
    id: 'bf',
    name: 'Burkina Faso',
    code: '+226',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '70 12 34 56',
  },
  {
    id: 'bi',
    name: 'Burundi',
    code: '+257',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '79 56 12 34',
  },
  {
    id: 'bt',
    name: 'Butão',
    code: '+975',
    phoneFormat: 'X XXX XXX',
    minLength: 7,
    maxLength: 8,
    placeholder: '17 123 456',
  },
  {
    id: 'cv',
    name: 'Cabo Verde',
    code: '+238',
    phoneFormat: 'XXX XX XX',
    minLength: 7,
    maxLength: 7,
    placeholder: '991 12 34',
  },
  {
    id: 'cm',
    name: 'Camarões',
    code: '+237',
    phoneFormat: 'X XX XX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '6 12 34 56 78',
  },
  {
    id: 'kh',
    name: 'Camboja',
    code: '+855',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '12 345 678',
  },
  {
    id: 'ca',
    name: 'Canadá',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(416) 123-4567',
  },
  {
    id: 'qa',
    name: 'Catar',
    code: '+974',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '3312 3456',
  },
  {
    id: 'kz',
    name: 'Cazaquistão',
    code: '+7',
    phoneFormat: 'XXX XXX XX XX',
    minLength: 10,
    maxLength: 10,
    placeholder: '701 123 45 67',
  },
  {
    id: 'td',
    name: 'Chade',
    code: '+235',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '63 01 23 45',
  },
  {
    id: 'cl',
    name: 'Chile',
    code: '+56',
    phoneFormat: 'X XXXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '9 1234 5678',
  },
  {
    id: 'cn',
    name: 'China',
    code: '+86',
    phoneFormat: 'XXX XXXX XXXX',
    minLength: 11,
    maxLength: 11,
    placeholder: '138 0013 8000',
  },
  {
    id: 'cy',
    name: 'Chipre',
    code: '+357',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '96 123 456',
  },
  {
    id: 'co',
    name: 'Colômbia',
    code: '+57',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '321 123 4567',
  },
  {
    id: 'km',
    name: 'Comores',
    code: '+269',
    phoneFormat: 'XXX XX XX',
    minLength: 7,
    maxLength: 7,
    placeholder: '321 23 45',
  },
  {
    id: 'cg',
    name: 'Congo',
    code: '+242',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '06 123 4567',
  },
  {
    id: 'kp',
    name: 'Coreia do Norte',
    code: '+850',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '191 123 4567',
  },
  {
    id: 'kr',
    name: 'Coreia do Sul',
    code: '+82',
    phoneFormat: 'XXX XXXX XXXX',
    minLength: 9,
    maxLength: 11,
    placeholder: '10 1234 5678',
  },
  {
    id: 'ci',
    name: 'Costa do Marfim',
    code: '+225',
    phoneFormat: 'XX XX XX XX XX',
    minLength: 10,
    maxLength: 10,
    placeholder: '01 23 45 67 89',
  },
  {
    id: 'cr',
    name: 'Costa Rica',
    code: '+506',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '8312 3456',
  },
  {
    id: 'hr',
    name: 'Croácia',
    code: '+385',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '91 234 5678',
  },
  {
    id: 'cu',
    name: 'Cuba',
    code: '+53',
    phoneFormat: 'X XXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '5 123 4567',
  },
  {
    id: 'dk',
    name: 'Dinamarca',
    code: '+45',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '20 12 34 56',
  },
  {
    id: 'dj',
    name: 'Djibuti',
    code: '+253',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '77 83 10 01',
  },
  {
    id: 'dm',
    name: 'Dominica',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(767) 225-1234',
  },
  {
    id: 'eg',
    name: 'Egito',
    code: '+20',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '100 123 4567',
  },
  {
    id: 'sv',
    name: 'El Salvador',
    code: '+503',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '7012 3456',
  },
  {
    id: 'ae',
    name: 'Emirados Árabes Unidos',
    code: '+971',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '50 123 4567',
  },
  {
    id: 'ec',
    name: 'Equador',
    code: '+593',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '99 123 4567',
  },
  {
    id: 'er',
    name: 'Eritreia',
    code: '+291',
    phoneFormat: 'X XXX XXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '7 123 456',
  },
  {
    id: 'sk',
    name: 'Eslováquia',
    code: '+421',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '912 123 456',
  },
  {
    id: 'si',
    name: 'Eslovênia',
    code: '+386',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '31 234 567',
  },
  {
    id: 'es',
    name: 'Espanha',
    code: '+34',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '612 345 678',
  },
  {
    id: 'us',
    name: 'Estados Unidos',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(201) 555-0123',
  },
  {
    id: 'ee',
    name: 'Estônia',
    code: '+372',
    phoneFormat: 'XXXX XXXX',
    minLength: 7,
    maxLength: 8,
    placeholder: '5123 4567',
  },
  {
    id: 'et',
    name: 'Etiópia',
    code: '+251',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '91 123 4567',
  },
  {
    id: 'fj',
    name: 'Fiji',
    code: '+679',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '701 2345',
  },
  {
    id: 'ph',
    name: 'Filipinas',
    code: '+63',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '917 123 4567',
  },
  {
    id: 'fi',
    name: 'Finlândia',
    code: '+358',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 10,
    placeholder: '40 123 4567',
  },
  {
    id: 'fr',
    name: 'França',
    code: '+33',
    phoneFormat: 'X XX XX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '6 12 34 56 78',
  },
  {
    id: 'ga',
    name: 'Gabão',
    code: '+241',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '06 03 12 34',
  },
  {
    id: 'gm',
    name: 'Gâmbia',
    code: '+220',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '301 2345',
  },
  {
    id: 'gh',
    name: 'Gana',
    code: '+233',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '23 123 4567',
  },
  {
    id: 'ge',
    name: 'Geórgia',
    code: '+995',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '555 123 456',
  },
  {
    id: 'gd',
    name: 'Granada',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(473) 403-1234',
  },
  {
    id: 'gr',
    name: 'Grécia',
    code: '+30',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '691 234 5678',
  },
  {
    id: 'gt',
    name: 'Guatemala',
    code: '+502',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '5123 4567',
  },
  {
    id: 'gy',
    name: 'Guiana',
    code: '+592',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '609 1234',
  },
  {
    id: 'gn',
    name: 'Guiné',
    code: '+224',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '601 123 456',
  },
  {
    id: 'gw',
    name: 'Guiné-Bissau',
    code: '+245',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '955 1234',
  },
  {
    id: 'gq',
    name: 'Guiné Equatorial',
    code: '+240',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '222 123 456',
  },
  {
    id: 'ht',
    name: 'Haiti',
    code: '+509',
    phoneFormat: 'XX XX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '34 10 1234',
  },
  {
    id: 'hn',
    name: 'Honduras',
    code: '+504',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '9123 4567',
  },
  {
    id: 'hu',
    name: 'Hungria',
    code: '+36',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '20 123 4567',
  },
  {
    id: 'ye',
    name: 'Iêmen',
    code: '+967',
    phoneFormat: 'X XXX XXXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '1 234 5678',
  },
  {
    id: 'mh',
    name: 'Ilhas Marshall',
    code: '+692',
    phoneFormat: 'XXX-XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '235-1234',
  },
  {
    id: 'sb',
    name: 'Ilhas Salomão',
    code: '+677',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '712 3456',
  },
  {
    id: 'in',
    name: 'Índia',
    code: '+91',
    phoneFormat: 'XXXXX XXXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '81234 56789',
  },
  {
    id: 'id',
    name: 'Indonésia',
    code: '+62',
    phoneFormat: 'XXX-XXX-XXXX',
    minLength: 10,
    maxLength: 13,
    placeholder: '812-345-6789',
  },
  {
    id: 'ir',
    name: 'Irã',
    code: '+98',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '912 345 6789',
  },
  {
    id: 'iq',
    name: 'Iraque',
    code: '+964',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '790 123 4567',
  },
  {
    id: 'ie',
    name: 'Irlanda',
    code: '+353',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '85 012 3456',
  },
  {
    id: 'is',
    name: 'Islândia',
    code: '+354',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '611 1234',
  },
  {
    id: 'il',
    name: 'Israel',
    code: '+972',
    phoneFormat: 'XX-XXX-XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '50-123-4567',
  },
  {
    id: 'it',
    name: 'Itália',
    code: '+39',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 11,
    placeholder: '312 345 6789',
  },
  {
    id: 'jm',
    name: 'Jamaica',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(876) 210-1234',
  },
  {
    id: 'jp',
    name: 'Japão',
    code: '+81',
    phoneFormat: 'XX-XXXX-XXXX',
    minLength: 10,
    maxLength: 11,
    placeholder: '90-1234-5678',
  },
  {
    id: 'jo',
    name: 'Jordânia',
    code: '+962',
    phoneFormat: 'X XXXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '7 9012 3456',
  },
  {
    id: 'kw',
    name: 'Kuwait',
    code: '+965',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '5012 3456',
  },
  {
    id: 'la',
    name: 'Laos',
    code: '+856',
    phoneFormat: 'XX XX XXX XXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '20 23 123 456',
  },
  {
    id: 'ls',
    name: 'Lesoto',
    code: '+266',
    phoneFormat: 'X XXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '5 012 3456',
  },
  {
    id: 'lv',
    name: 'Letônia',
    code: '+371',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '21 234 567',
  },
  {
    id: 'lb',
    name: 'Líbano',
    code: '+961',
    phoneFormat: 'XX XXX XXX',
    minLength: 7,
    maxLength: 8,
    placeholder: '71 123 456',
  },
  {
    id: 'lr',
    name: 'Libéria',
    code: '+231',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '77 012 3456',
  },
  {
    id: 'ly',
    name: 'Líbia',
    code: '+218',
    phoneFormat: 'XX-XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '91-234 5678',
  },
  {
    id: 'li',
    name: 'Liechtenstein',
    code: '+423',
    phoneFormat: 'XXX XX XX',
    minLength: 7,
    maxLength: 7,
    placeholder: '660 23 45',
  },
  {
    id: 'lt',
    name: 'Lituânia',
    code: '+370',
    phoneFormat: 'XXX XXXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '612 34567',
  },
  {
    id: 'lu',
    name: 'Luxemburgo',
    code: '+352',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '621 123 456',
  },
  {
    id: 'mk',
    name: 'Macedônia do Norte',
    code: '+389',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '70 123 456',
  },
  {
    id: 'mg',
    name: 'Madagascar',
    code: '+261',
    phoneFormat: 'XX XX XXX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '32 12 345 67',
  },
  {
    id: 'my',
    name: 'Malásia',
    code: '+60',
    phoneFormat: 'XX-XXXX XXXX',
    minLength: 9,
    maxLength: 10,
    placeholder: '12-3456 7890',
  },
  {
    id: 'mw',
    name: 'Malawi',
    code: '+265',
    phoneFormat: 'X XXXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '1 1234 5678',
  },
  {
    id: 'mv',
    name: 'Maldivas',
    code: '+960',
    phoneFormat: 'XXX-XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '771-2345',
  },
  {
    id: 'ml',
    name: 'Mali',
    code: '+223',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '65 01 23 45',
  },
  {
    id: 'mt',
    name: 'Malta',
    code: '+356',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '9696 1234',
  },
  {
    id: 'ma',
    name: 'Marrocos',
    code: '+212',
    phoneFormat: 'XXX-XXXXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '650-123456',
  },
  {
    id: 'mu',
    name: 'Maurício',
    code: '+230',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '5251 2345',
  },
  {
    id: 'mr',
    name: 'Mauritânia',
    code: '+222',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '22 12 34 56',
  },
  {
    id: 'mx',
    name: 'México',
    code: '+52',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '222 123 4567',
  },
  {
    id: 'mm',
    name: 'Mianmar',
    code: '+95',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 10,
    placeholder: '09 212 3456',
  },
  {
    id: 'fm',
    name: 'Micronésia',
    code: '+691',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '350 1234',
  },
  {
    id: 'mz',
    name: 'Moçambique',
    code: '+258',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '82 123 4567',
  },
  {
    id: 'md',
    name: 'Moldávia',
    code: '+373',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '6012 3456',
  },
  {
    id: 'mc',
    name: 'Mônaco',
    code: '+377',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 9,
    placeholder: '06 12 34 56',
  },
  {
    id: 'mn',
    name: 'Mongólia',
    code: '+976',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '8812 3456',
  },
  {
    id: 'me',
    name: 'Montenegro',
    code: '+382',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '67 622 901',
  },
  {
    id: 'na',
    name: 'Namíbia',
    code: '+264',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '81 123 4567',
  },
  {
    id: 'nr',
    name: 'Nauru',
    code: '+674',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '555 1234',
  },
  {
    id: 'np',
    name: 'Nepal',
    code: '+977',
    phoneFormat: 'XXX-XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '984-123 4567',
  },
  {
    id: 'ni',
    name: 'Nicarágua',
    code: '+505',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '8123 4567',
  },
  {
    id: 'ne',
    name: 'Níger',
    code: '+227',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '93 12 34 56',
  },
  {
    id: 'ng',
    name: 'Nigéria',
    code: '+234',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '802 123 4567',
  },
  {
    id: 'no',
    name: 'Noruega',
    code: '+47',
    phoneFormat: 'XXX XX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '406 12 345',
  },
  {
    id: 'nz',
    name: 'Nova Zelândia',
    code: '+64',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 10,
    placeholder: '21 123 4567',
  },
  {
    id: 'om',
    name: 'Omã',
    code: '+968',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '9212 3456',
  },
  {
    id: 'nl',
    name: 'Países Baixos',
    code: '+31',
    phoneFormat: 'X XXXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '6 1234 5678',
  },
  {
    id: 'pw',
    name: 'Palau',
    code: '+680',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '620 1234',
  },
  {
    id: 'pa',
    name: 'Panamá',
    code: '+507',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '6123 4567',
  },
  {
    id: 'pg',
    name: 'Papua-Nova Guiné',
    code: '+675',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 8,
    placeholder: '681 2345',
  },
  {
    id: 'pk',
    name: 'Paquistão',
    code: '+92',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '301 234 5678',
  },
  {
    id: 'py',
    name: 'Paraguai',
    code: '+595',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '961 456 789',
  },
  {
    id: 'pe',
    name: 'Peru',
    code: '+51',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '912 345 678',
  },
  {
    id: 'pl',
    name: 'Polônia',
    code: '+48',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '512 345 678',
  },
  {
    id: 'pt',
    name: 'Portugal',
    code: '+351',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '912 345 678',
  },
  {
    id: 'ke',
    name: 'Quênia',
    code: '+254',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '712 123 456',
  },
  {
    id: 'kg',
    name: 'Quirguistão',
    code: '+996',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '700 123 456',
  },
  {
    id: 'gb',
    name: 'Reino Unido',
    code: '+44',
    phoneFormat: 'XXXX XXXXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '7400 123456',
  },
  {
    id: 'cf',
    name: 'República Centro-Africana',
    code: '+236',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '70 01 23 45',
  },
  {
    id: 'cz',
    name: 'República Checa',
    code: '+420',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '601 123 456',
  },
  {
    id: 'cd',
    name: 'República Democrática do Congo',
    code: '+243',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '991 234 567',
  },
  {
    id: 'do',
    name: 'República Dominicana',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(809) 234-5678',
  },
  {
    id: 'ro',
    name: 'Romênia',
    code: '+40',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '712 345 678',
  },
  {
    id: 'rw',
    name: 'Ruanda',
    code: '+250',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '781 234 567',
  },
  {
    id: 'ru',
    name: 'Rússia',
    code: '+7',
    phoneFormat: 'XXX XXX-XX-XX',
    minLength: 10,
    maxLength: 10,
    placeholder: '912 345-67-89',
  },
  {
    id: 'ws',
    name: 'Samoa',
    code: '+685',
    phoneFormat: 'XX XXXXX',
    minLength: 6,
    maxLength: 7,
    placeholder: '72 12345',
  },
  {
    id: 'sm',
    name: 'San Marino',
    code: '+378',
    phoneFormat: 'XXX XXX',
    minLength: 6,
    maxLength: 6,
    placeholder: '912 345',
  },
  {
    id: 'lc',
    name: 'Santa Lúcia',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(758) 284-5678',
  },
  {
    id: 'st',
    name: 'São Tomé e Príncipe',
    code: '+239',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '981 2345',
  },
  {
    id: 'sn',
    name: 'Senegal',
    code: '+221',
    phoneFormat: 'XX XXX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '70 123 45 67',
  },
  {
    id: 'sl',
    name: 'Serra Leoa',
    code: '+232',
    phoneFormat: 'XX XXXXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '25 123456',
  },
  {
    id: 'rs',
    name: 'Sérvia',
    code: '+381',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '60 123 4567',
  },
  {
    id: 'sc',
    name: 'Seychelles',
    code: '+248',
    phoneFormat: 'X XX XX XX',
    minLength: 7,
    maxLength: 7,
    placeholder: '2 51 23 45',
  },
  {
    id: 'sg',
    name: 'Singapura',
    code: '+65',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '8123 4567',
  },
  {
    id: 'sy',
    name: 'Síria',
    code: '+963',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '944 567 890',
  },
  {
    id: 'so',
    name: 'Somália',
    code: '+252',
    phoneFormat: 'XX XXX XXXX',
    minLength: 8,
    maxLength: 9,
    placeholder: '61 123 4567',
  },
  {
    id: 'lk',
    name: 'Sri Lanka',
    code: '+94',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '71 234 5678',
  },
  {
    id: 'sz',
    name: 'Suazilândia',
    code: '+268',
    phoneFormat: 'XXXX XXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '7612 3456',
  },
  {
    id: 'sd',
    name: 'Sudão',
    code: '+249',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '91 123 4567',
  },
  {
    id: 'ss',
    name: 'Sudão do Sul',
    code: '+211',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '95 123 4567',
  },
  {
    id: 'se',
    name: 'Suécia',
    code: '+46',
    phoneFormat: 'XX XXX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '70 123 45 67',
  },
  {
    id: 'ch',
    name: 'Suíça',
    code: '+41',
    phoneFormat: 'XX XXX XX XX',
    minLength: 9,
    maxLength: 9,
    placeholder: '78 123 45 67',
  },
  {
    id: 'sr',
    name: 'Suriname',
    code: '+597',
    phoneFormat: 'XXX-XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '741-2345',
  },
  {
    id: 'th',
    name: 'Tailândia',
    code: '+66',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '81 234 5678',
  },
  {
    id: 'tw',
    name: 'Taiwan',
    code: '+886',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '912 345 678',
  },
  {
    id: 'tj',
    name: 'Tajiquistão',
    code: '+992',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '37 123 4567',
  },
  {
    id: 'tz',
    name: 'Tanzânia',
    code: '+255',
    phoneFormat: 'XXX XXX XXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '621 234 567',
  },
  {
    id: 'tl',
    name: 'Timor-Leste',
    code: '+670',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 8,
    placeholder: '7721 2345',
  },
  {
    id: 'tg',
    name: 'Togo',
    code: '+228',
    phoneFormat: 'XX XX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '90 11 23 45',
  },
  {
    id: 'to',
    name: 'Tonga',
    code: '+676',
    phoneFormat: 'XXXXXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '7715123',
  },
  {
    id: 'tt',
    name: 'Trinidad e Tobago',
    code: '+1',
    phoneFormat: '(XXX) XXX-XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '(868) 291-1234',
  },
  {
    id: 'tn',
    name: 'Tunísia',
    code: '+216',
    phoneFormat: 'XX XXX XXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '20 123 456',
  },
  {
    id: 'tm',
    name: 'Turcomenistão',
    code: '+993',
    phoneFormat: 'XX XXXXXX',
    minLength: 8,
    maxLength: 8,
    placeholder: '65 123456',
  },
  {
    id: 'tr',
    name: 'Turquia',
    code: '+90',
    phoneFormat: 'XXX XXX XXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '501 234 5678',
  },
  {
    id: 'tv',
    name: 'Tuvalu',
    code: '+688',
    phoneFormat: 'XXX XXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '901 2345',
  },
  {
    id: 'ua',
    name: 'Ucrânia',
    code: '+380',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '50 123 4567',
  },
  {
    id: 'ug',
    name: 'Uganda',
    code: '+256',
    phoneFormat: 'XXX XXXXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '712 345678',
  },
  {
    id: 'uy',
    name: 'Uruguai',
    code: '+598',
    phoneFormat: 'X XXX XX XX',
    minLength: 8,
    maxLength: 8,
    placeholder: '9 123 45 67',
  },
  {
    id: 'uz',
    name: 'Uzbequistão',
    code: '+998',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '91 234 5678',
  },
  {
    id: 'vu',
    name: 'Vanuatu',
    code: '+678',
    phoneFormat: 'XXXXXXX',
    minLength: 7,
    maxLength: 7,
    placeholder: '5912345',
  },
  {
    id: 'va',
    name: 'Vaticano',
    code: '+39',
    phoneFormat: 'XX XXXX XXXX',
    minLength: 10,
    maxLength: 11,
    placeholder: '06 6982 1234',
  },
  {
    id: 've',
    name: 'Venezuela',
    code: '+58',
    phoneFormat: 'XXX-XXXXXXX',
    minLength: 10,
    maxLength: 10,
    placeholder: '412-1234567',
  },
  {
    id: 'vn',
    name: 'Vietnã',
    code: '+84',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '91 234 5678',
  },
  {
    id: 'zm',
    name: 'Zâmbia',
    code: '+260',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '95 123 4567',
  },
  {
    id: 'zw',
    name: 'Zimbábue',
    code: '+263',
    phoneFormat: 'XX XXX XXXX',
    minLength: 9,
    maxLength: 9,
    placeholder: '71 123 4567',
  },
]
