export const NEXT_PUBLIC_BUSCA_CARIOCA_DIGITAL_COLLECTION =
  process.env.NEXT_PUBLIC_BUSCA_CARIOCA_DIGITAL_COLLECTION
export const NEXT_PUBLIC_BUSCA_1746_COLLECTION =
  process.env.NEXT_PUBLIC_BUSCA_1746_COLLECTION
export const NEXT_PUBLIC_BUSCA_PREFRIO_COLLECTION =
  process.env.NEXT_PUBLIC_BUSCA_PREFRIO_COLLECTION

/**
 * Feature flag to enable/disable hardcoded external search links
 * Default: disabled (false)
 * Set NEXT_PUBLIC_ENABLE_HARDCODED_SEARCH_LINKS=true to enable
 */
export const ENABLE_HARDCODED_SEARCH_LINKS =
  process.env.NEXT_PUBLIC_ENABLE_HARDCODED_SEARCH_LINKS === 'true'
