/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type {
  GetAdminMobilidadeVehicleModelsParams,
  GetCitizenCpfVehiclesParams,
  GetMobilidadeVehicleModelsParams,
  HandlersErrorResponse,
  ModelsConductorsListResponse,
  ModelsInviteConductorRequest,
  ModelsPaginatedVehicles,
  ModelsRespondInvitationRequest,
  ModelsVehicleBrand,
  ModelsVehicleBrandCreateRequest,
  ModelsVehicleBrandUpdateRequest,
  ModelsVehicleBrandsResponse,
  ModelsVehicleColorsResponse,
  ModelsVehicleConductor,
  ModelsVehicleCreateRequest,
  ModelsVehicleDetail,
  ModelsVehicleInvitationsResponse,
  ModelsVehicleModel,
  ModelsVehicleModelCreateRequest,
  ModelsVehicleModelUpdateRequest,
  ModelsVehicleModelsResponse,
  ModelsVehicleUpdateRequest,
} from '../models'

import { customFetch } from '../../../custom-fetch'

export type getAdminMobilidadeVehicleBrandsResponse200 = {
  data: ModelsVehicleBrandsResponse
  status: 200
}

export type getAdminMobilidadeVehicleBrandsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getAdminMobilidadeVehicleBrandsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getAdminMobilidadeVehicleBrandsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getAdminMobilidadeVehicleBrandsResponseSuccess =
  getAdminMobilidadeVehicleBrandsResponse200 & {
    headers: Headers
  }
export type getAdminMobilidadeVehicleBrandsResponseError = (
  | getAdminMobilidadeVehicleBrandsResponse401
  | getAdminMobilidadeVehicleBrandsResponse403
  | getAdminMobilidadeVehicleBrandsResponse500
) & {
  headers: Headers
}

export type getAdminMobilidadeVehicleBrandsResponse =
  | getAdminMobilidadeVehicleBrandsResponseSuccess
  | getAdminMobilidadeVehicleBrandsResponseError

export const getGetAdminMobilidadeVehicleBrandsUrl = () => {
  return `/admin/mobilidade/vehicle-brands`
}

/**
 * Lista completa de marcas do catálogo, incluindo soft-deleted (admin).
 * @summary Listar marcas (admin)
 */
export const getAdminMobilidadeVehicleBrands = async (
  options?: RequestInit
): Promise<getAdminMobilidadeVehicleBrandsResponse> => {
  return customFetch<getAdminMobilidadeVehicleBrandsResponse>(
    getGetAdminMobilidadeVehicleBrandsUrl(),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type postAdminMobilidadeVehicleBrandsResponse201 = {
  data: ModelsVehicleBrand
  status: 201
}

export type postAdminMobilidadeVehicleBrandsResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type postAdminMobilidadeVehicleBrandsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type postAdminMobilidadeVehicleBrandsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type postAdminMobilidadeVehicleBrandsResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type postAdminMobilidadeVehicleBrandsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type postAdminMobilidadeVehicleBrandsResponseSuccess =
  postAdminMobilidadeVehicleBrandsResponse201 & {
    headers: Headers
  }
export type postAdminMobilidadeVehicleBrandsResponseError = (
  | postAdminMobilidadeVehicleBrandsResponse400
  | postAdminMobilidadeVehicleBrandsResponse401
  | postAdminMobilidadeVehicleBrandsResponse403
  | postAdminMobilidadeVehicleBrandsResponse409
  | postAdminMobilidadeVehicleBrandsResponse500
) & {
  headers: Headers
}

export type postAdminMobilidadeVehicleBrandsResponse =
  | postAdminMobilidadeVehicleBrandsResponseSuccess
  | postAdminMobilidadeVehicleBrandsResponseError

export const getPostAdminMobilidadeVehicleBrandsUrl = () => {
  return `/admin/mobilidade/vehicle-brands`
}

/**
 * Cadastra uma marca no catálogo. ID gerado no backend (brand_&lt;slug&gt;); is_other=false.
 * @summary Criar marca (admin)
 */
export const postAdminMobilidadeVehicleBrands = async (
  modelsVehicleBrandCreateRequest: ModelsVehicleBrandCreateRequest,
  options?: RequestInit
): Promise<postAdminMobilidadeVehicleBrandsResponse> => {
  return customFetch<postAdminMobilidadeVehicleBrandsResponse>(
    getPostAdminMobilidadeVehicleBrandsUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsVehicleBrandCreateRequest),
    }
  )
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse204 = {
  data: void
  status: 204
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponseSuccess =
  deleteAdminMobilidadeVehicleBrandsBrandIdResponse204 & {
    headers: Headers
  }
export type deleteAdminMobilidadeVehicleBrandsBrandIdResponseError = (
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponse400
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponse401
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponse403
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponse404
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponse409
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponse500
) & {
  headers: Headers
}

export type deleteAdminMobilidadeVehicleBrandsBrandIdResponse =
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponseSuccess
  | deleteAdminMobilidadeVehicleBrandsBrandIdResponseError

export const getDeleteAdminMobilidadeVehicleBrandsBrandIdUrl = (
  brandId: string
) => {
  return `/admin/mobilidade/vehicle-brands/${brandId}`
}

/**
 * Soft-delete de marca. 409 se houver modelos ativos ou veículos referenciando. Sentinel brand_outro não pode ser excluída.
 * @summary Excluir marca (admin, soft-delete)
 */
export const deleteAdminMobilidadeVehicleBrandsBrandId = async (
  brandId: string,
  options?: RequestInit
): Promise<deleteAdminMobilidadeVehicleBrandsBrandIdResponse> => {
  return customFetch<deleteAdminMobilidadeVehicleBrandsBrandIdResponse>(
    getDeleteAdminMobilidadeVehicleBrandsBrandIdUrl(brandId),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse200 = {
  data: ModelsVehicleBrand
  status: 200
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponseSuccess =
  patchAdminMobilidadeVehicleBrandsBrandIdResponse200 & {
    headers: Headers
  }
export type patchAdminMobilidadeVehicleBrandsBrandIdResponseError = (
  | patchAdminMobilidadeVehicleBrandsBrandIdResponse400
  | patchAdminMobilidadeVehicleBrandsBrandIdResponse401
  | patchAdminMobilidadeVehicleBrandsBrandIdResponse403
  | patchAdminMobilidadeVehicleBrandsBrandIdResponse404
  | patchAdminMobilidadeVehicleBrandsBrandIdResponse409
  | patchAdminMobilidadeVehicleBrandsBrandIdResponse500
) & {
  headers: Headers
}

export type patchAdminMobilidadeVehicleBrandsBrandIdResponse =
  | patchAdminMobilidadeVehicleBrandsBrandIdResponseSuccess
  | patchAdminMobilidadeVehicleBrandsBrandIdResponseError

export const getPatchAdminMobilidadeVehicleBrandsBrandIdUrl = (
  brandId: string
) => {
  return `/admin/mobilidade/vehicle-brands/${brandId}`
}

/**
 * Atualiza o nome de uma marca ativa. Sentinel brand_outro não pode ser alterada. 409 se referenciada por veículo.
 * @summary Atualizar marca (admin)
 */
export const patchAdminMobilidadeVehicleBrandsBrandId = async (
  brandId: string,
  modelsVehicleBrandUpdateRequest: ModelsVehicleBrandUpdateRequest,
  options?: RequestInit
): Promise<patchAdminMobilidadeVehicleBrandsBrandIdResponse> => {
  return customFetch<patchAdminMobilidadeVehicleBrandsBrandIdResponse>(
    getPatchAdminMobilidadeVehicleBrandsBrandIdUrl(brandId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsVehicleBrandUpdateRequest),
    }
  )
}

export type getAdminMobilidadeVehicleModelsResponse200 = {
  data: ModelsVehicleModelsResponse
  status: 200
}

export type getAdminMobilidadeVehicleModelsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getAdminMobilidadeVehicleModelsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getAdminMobilidadeVehicleModelsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getAdminMobilidadeVehicleModelsResponseSuccess =
  getAdminMobilidadeVehicleModelsResponse200 & {
    headers: Headers
  }
export type getAdminMobilidadeVehicleModelsResponseError = (
  | getAdminMobilidadeVehicleModelsResponse401
  | getAdminMobilidadeVehicleModelsResponse403
  | getAdminMobilidadeVehicleModelsResponse500
) & {
  headers: Headers
}

export type getAdminMobilidadeVehicleModelsResponse =
  | getAdminMobilidadeVehicleModelsResponseSuccess
  | getAdminMobilidadeVehicleModelsResponseError

export const getGetAdminMobilidadeVehicleModelsUrl = (
  params?: GetAdminMobilidadeVehicleModelsParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/admin/mobilidade/vehicle-models?${stringifiedParams}`
    : `/admin/mobilidade/vehicle-models`
}

/**
 * Lista completa de modelos, incluindo soft-deleted. Filtro opcional por brand_id.
 * @summary Listar modelos (admin)
 */
export const getAdminMobilidadeVehicleModels = async (
  params?: GetAdminMobilidadeVehicleModelsParams,
  options?: RequestInit
): Promise<getAdminMobilidadeVehicleModelsResponse> => {
  return customFetch<getAdminMobilidadeVehicleModelsResponse>(
    getGetAdminMobilidadeVehicleModelsUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type postAdminMobilidadeVehicleModelsResponse201 = {
  data: ModelsVehicleModel
  status: 201
}

export type postAdminMobilidadeVehicleModelsResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type postAdminMobilidadeVehicleModelsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type postAdminMobilidadeVehicleModelsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type postAdminMobilidadeVehicleModelsResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type postAdminMobilidadeVehicleModelsResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type postAdminMobilidadeVehicleModelsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type postAdminMobilidadeVehicleModelsResponseSuccess =
  postAdminMobilidadeVehicleModelsResponse201 & {
    headers: Headers
  }
export type postAdminMobilidadeVehicleModelsResponseError = (
  | postAdminMobilidadeVehicleModelsResponse400
  | postAdminMobilidadeVehicleModelsResponse401
  | postAdminMobilidadeVehicleModelsResponse403
  | postAdminMobilidadeVehicleModelsResponse404
  | postAdminMobilidadeVehicleModelsResponse409
  | postAdminMobilidadeVehicleModelsResponse500
) & {
  headers: Headers
}

export type postAdminMobilidadeVehicleModelsResponse =
  | postAdminMobilidadeVehicleModelsResponseSuccess
  | postAdminMobilidadeVehicleModelsResponseError

export const getPostAdminMobilidadeVehicleModelsUrl = () => {
  return `/admin/mobilidade/vehicle-models`
}

/**
 * Cadastra um modelo vinculado a brand_id com vehicle_type. ID gerado no backend; is_other=false.
 * @summary Criar modelo (admin)
 */
export const postAdminMobilidadeVehicleModels = async (
  modelsVehicleModelCreateRequest: ModelsVehicleModelCreateRequest,
  options?: RequestInit
): Promise<postAdminMobilidadeVehicleModelsResponse> => {
  return customFetch<postAdminMobilidadeVehicleModelsResponse>(
    getPostAdminMobilidadeVehicleModelsUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsVehicleModelCreateRequest),
    }
  )
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse204 = {
  data: void
  status: 204
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponseSuccess =
  deleteAdminMobilidadeVehicleModelsModelIdResponse204 & {
    headers: Headers
  }
export type deleteAdminMobilidadeVehicleModelsModelIdResponseError = (
  | deleteAdminMobilidadeVehicleModelsModelIdResponse400
  | deleteAdminMobilidadeVehicleModelsModelIdResponse401
  | deleteAdminMobilidadeVehicleModelsModelIdResponse403
  | deleteAdminMobilidadeVehicleModelsModelIdResponse404
  | deleteAdminMobilidadeVehicleModelsModelIdResponse409
  | deleteAdminMobilidadeVehicleModelsModelIdResponse500
) & {
  headers: Headers
}

export type deleteAdminMobilidadeVehicleModelsModelIdResponse =
  | deleteAdminMobilidadeVehicleModelsModelIdResponseSuccess
  | deleteAdminMobilidadeVehicleModelsModelIdResponseError

export const getDeleteAdminMobilidadeVehicleModelsModelIdUrl = (
  modelId: string
) => {
  return `/admin/mobilidade/vehicle-models/${modelId}`
}

/**
 * Soft-delete de modelo. 409 se veículos referenciarem. Sentinel model_outro não pode ser excluído.
 * @summary Excluir modelo (admin, soft-delete)
 */
export const deleteAdminMobilidadeVehicleModelsModelId = async (
  modelId: string,
  options?: RequestInit
): Promise<deleteAdminMobilidadeVehicleModelsModelIdResponse> => {
  return customFetch<deleteAdminMobilidadeVehicleModelsModelIdResponse>(
    getDeleteAdminMobilidadeVehicleModelsModelIdUrl(modelId),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse200 = {
  data: ModelsVehicleModel
  status: 200
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type patchAdminMobilidadeVehicleModelsModelIdResponseSuccess =
  patchAdminMobilidadeVehicleModelsModelIdResponse200 & {
    headers: Headers
  }
export type patchAdminMobilidadeVehicleModelsModelIdResponseError = (
  | patchAdminMobilidadeVehicleModelsModelIdResponse400
  | patchAdminMobilidadeVehicleModelsModelIdResponse401
  | patchAdminMobilidadeVehicleModelsModelIdResponse403
  | patchAdminMobilidadeVehicleModelsModelIdResponse404
  | patchAdminMobilidadeVehicleModelsModelIdResponse409
  | patchAdminMobilidadeVehicleModelsModelIdResponse500
) & {
  headers: Headers
}

export type patchAdminMobilidadeVehicleModelsModelIdResponse =
  | patchAdminMobilidadeVehicleModelsModelIdResponseSuccess
  | patchAdminMobilidadeVehicleModelsModelIdResponseError

export const getPatchAdminMobilidadeVehicleModelsModelIdUrl = (
  modelId: string
) => {
  return `/admin/mobilidade/vehicle-models/${modelId}`
}

/**
 * Atualiza nome, vehicle_type e/ou brand_id de um modelo ativo. Sentinel model_outro não pode ser alterado. 409 se referenciado por veículo.
 * @summary Atualizar modelo (admin)
 */
export const patchAdminMobilidadeVehicleModelsModelId = async (
  modelId: string,
  modelsVehicleModelUpdateRequest: ModelsVehicleModelUpdateRequest,
  options?: RequestInit
): Promise<patchAdminMobilidadeVehicleModelsModelIdResponse> => {
  return customFetch<patchAdminMobilidadeVehicleModelsModelIdResponse>(
    getPatchAdminMobilidadeVehicleModelsModelIdUrl(modelId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsVehicleModelUpdateRequest),
    }
  )
}

export type getCitizenCpfVehicleInvitationsResponse200 = {
  data: ModelsVehicleInvitationsResponse
  status: 200
}

export type getCitizenCpfVehicleInvitationsResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getCitizenCpfVehicleInvitationsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getCitizenCpfVehicleInvitationsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getCitizenCpfVehicleInvitationsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getCitizenCpfVehicleInvitationsResponseSuccess =
  getCitizenCpfVehicleInvitationsResponse200 & {
    headers: Headers
  }
export type getCitizenCpfVehicleInvitationsResponseError = (
  | getCitizenCpfVehicleInvitationsResponse400
  | getCitizenCpfVehicleInvitationsResponse401
  | getCitizenCpfVehicleInvitationsResponse403
  | getCitizenCpfVehicleInvitationsResponse500
) & {
  headers: Headers
}

export type getCitizenCpfVehicleInvitationsResponse =
  | getCitizenCpfVehicleInvitationsResponseSuccess
  | getCitizenCpfVehicleInvitationsResponseError

export const getGetCitizenCpfVehicleInvitationsUrl = (cpf: string) => {
  return `/citizen/${cpf}/vehicle-invitations`
}

/**
 * Lista convites pending em que o CPF é o convidado.
 * @summary Listar convites pendentes de veículo
 */
export const getCitizenCpfVehicleInvitations = async (
  cpf: string,
  options?: RequestInit
): Promise<getCitizenCpfVehicleInvitationsResponse> => {
  return customFetch<getCitizenCpfVehicleInvitationsResponse>(
    getGetCitizenCpfVehicleInvitationsUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse200 = {
  data: ModelsVehicleConductor
  status: 200
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponseSuccess =
  patchCitizenCpfVehicleInvitationsConductorIdResponse200 & {
    headers: Headers
  }
export type patchCitizenCpfVehicleInvitationsConductorIdResponseError = (
  | patchCitizenCpfVehicleInvitationsConductorIdResponse400
  | patchCitizenCpfVehicleInvitationsConductorIdResponse401
  | patchCitizenCpfVehicleInvitationsConductorIdResponse403
  | patchCitizenCpfVehicleInvitationsConductorIdResponse404
  | patchCitizenCpfVehicleInvitationsConductorIdResponse500
) & {
  headers: Headers
}

export type patchCitizenCpfVehicleInvitationsConductorIdResponse =
  | patchCitizenCpfVehicleInvitationsConductorIdResponseSuccess
  | patchCitizenCpfVehicleInvitationsConductorIdResponseError

export const getPatchCitizenCpfVehicleInvitationsConductorIdUrl = (
  cpf: string,
  conductorId: string
) => {
  return `/citizen/${cpf}/vehicle-invitations/${conductorId}`
}

/**
 * Atualiza status do convite para accepted ou rejected (somente o convidado).
 * @summary Aceitar ou recusar convite de veículo
 */
export const patchCitizenCpfVehicleInvitationsConductorId = async (
  cpf: string,
  conductorId: string,
  modelsRespondInvitationRequest: ModelsRespondInvitationRequest,
  options?: RequestInit
): Promise<patchCitizenCpfVehicleInvitationsConductorIdResponse> => {
  return customFetch<patchCitizenCpfVehicleInvitationsConductorIdResponse>(
    getPatchCitizenCpfVehicleInvitationsConductorIdUrl(cpf, conductorId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsRespondInvitationRequest),
    }
  )
}

export type getCitizenCpfVehiclesResponse200 = {
  data: ModelsPaginatedVehicles
  status: 200
}

export type getCitizenCpfVehiclesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getCitizenCpfVehiclesResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getCitizenCpfVehiclesResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getCitizenCpfVehiclesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getCitizenCpfVehiclesResponseSuccess =
  getCitizenCpfVehiclesResponse200 & {
    headers: Headers
  }
export type getCitizenCpfVehiclesResponseError = (
  | getCitizenCpfVehiclesResponse400
  | getCitizenCpfVehiclesResponse401
  | getCitizenCpfVehiclesResponse403
  | getCitizenCpfVehiclesResponse500
) & {
  headers: Headers
}

export type getCitizenCpfVehiclesResponse =
  | getCitizenCpfVehiclesResponseSuccess
  | getCitizenCpfVehiclesResponseError

export const getGetCitizenCpfVehiclesUrl = (
  cpf: string,
  params?: GetCitizenCpfVehiclesParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/citizen/${cpf}/vehicles?${stringifiedParams}`
    : `/citizen/${cpf}/vehicles`
}

/**
 * Retorna veículos em que o CPF é proprietário ou condutor aceito, com role em cada item. Quando role=conductor, inclui conductor_id (id do vínculo aceito). brand_name/model_name são resolvidos do catálogo quando há brand_id/model_id e não há brand_other/model_other.
 * @summary Listar veículos da carteira (mobilidade)
 */
export const getCitizenCpfVehicles = async (
  cpf: string,
  params?: GetCitizenCpfVehiclesParams,
  options?: RequestInit
): Promise<getCitizenCpfVehiclesResponse> => {
  return customFetch<getCitizenCpfVehiclesResponse>(
    getGetCitizenCpfVehiclesUrl(cpf, params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type postCitizenCpfVehiclesResponse201 = {
  data: ModelsVehicleDetail
  status: 201
}

export type postCitizenCpfVehiclesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type postCitizenCpfVehiclesResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type postCitizenCpfVehiclesResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type postCitizenCpfVehiclesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type postCitizenCpfVehiclesResponseSuccess =
  postCitizenCpfVehiclesResponse201 & {
    headers: Headers
  }
export type postCitizenCpfVehiclesResponseError = (
  | postCitizenCpfVehiclesResponse400
  | postCitizenCpfVehiclesResponse401
  | postCitizenCpfVehiclesResponse403
  | postCitizenCpfVehiclesResponse500
) & {
  headers: Headers
}

export type postCitizenCpfVehiclesResponse =
  | postCitizenCpfVehiclesResponseSuccess
  | postCitizenCpfVehiclesResponseError

export const getPostCitizenCpfVehiclesUrl = (cpf: string) => {
  return `/citizen/${cpf}/vehicles`
}

/**
 * Cadastra um veículo para o CPF autenticado. Fluxo catálogo (brand_id+model_id) ou Outro (brand_other/model_other+vehicle_type). URLs de foto devem ser HTTPS GCS. Se has_invoice=true, invoice_photo_url é obrigatória. Contato do dono (nome/telefone/e-mail) é enriquecido ao vivo via RMI a partir do owner_cpf — não enviar owner_* no body. registration_number é gerado pelo backend (formato RJ-E-XXXXXX).
 * @summary Cadastrar veículo
 */
export const postCitizenCpfVehicles = async (
  cpf: string,
  modelsVehicleCreateRequest: ModelsVehicleCreateRequest,
  options?: RequestInit
): Promise<postCitizenCpfVehiclesResponse> => {
  return customFetch<postCitizenCpfVehiclesResponse>(
    getPostCitizenCpfVehiclesUrl(cpf),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsVehicleCreateRequest),
    }
  )
}

export type deleteCitizenCpfVehiclesVehicleIdResponse204 = {
  data: void
  status: 204
}

export type deleteCitizenCpfVehiclesVehicleIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type deleteCitizenCpfVehiclesVehicleIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type deleteCitizenCpfVehiclesVehicleIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type deleteCitizenCpfVehiclesVehicleIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type deleteCitizenCpfVehiclesVehicleIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type deleteCitizenCpfVehiclesVehicleIdResponseSuccess =
  deleteCitizenCpfVehiclesVehicleIdResponse204 & {
    headers: Headers
  }
export type deleteCitizenCpfVehiclesVehicleIdResponseError = (
  | deleteCitizenCpfVehiclesVehicleIdResponse400
  | deleteCitizenCpfVehiclesVehicleIdResponse401
  | deleteCitizenCpfVehiclesVehicleIdResponse403
  | deleteCitizenCpfVehiclesVehicleIdResponse404
  | deleteCitizenCpfVehiclesVehicleIdResponse500
) & {
  headers: Headers
}

export type deleteCitizenCpfVehiclesVehicleIdResponse =
  | deleteCitizenCpfVehiclesVehicleIdResponseSuccess
  | deleteCitizenCpfVehiclesVehicleIdResponseError

export const getDeleteCitizenCpfVehiclesVehicleIdUrl = (
  cpf: string,
  vehicleId: string
) => {
  return `/citizen/${cpf}/vehicles/${vehicleId}`
}

/**
 * Soft-delete do veículo e revoga vínculos pending/accepted (somente proprietário).
 * @summary Excluir veículo (soft delete)
 */
export const deleteCitizenCpfVehiclesVehicleId = async (
  cpf: string,
  vehicleId: string,
  options?: RequestInit
): Promise<deleteCitizenCpfVehiclesVehicleIdResponse> => {
  return customFetch<deleteCitizenCpfVehiclesVehicleIdResponse>(
    getDeleteCitizenCpfVehiclesVehicleIdUrl(cpf, vehicleId),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getCitizenCpfVehiclesVehicleIdResponse200 = {
  data: ModelsVehicleDetail
  status: 200
}

export type getCitizenCpfVehiclesVehicleIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getCitizenCpfVehiclesVehicleIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getCitizenCpfVehiclesVehicleIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getCitizenCpfVehiclesVehicleIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type getCitizenCpfVehiclesVehicleIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getCitizenCpfVehiclesVehicleIdResponseSuccess =
  getCitizenCpfVehiclesVehicleIdResponse200 & {
    headers: Headers
  }
export type getCitizenCpfVehiclesVehicleIdResponseError = (
  | getCitizenCpfVehiclesVehicleIdResponse400
  | getCitizenCpfVehiclesVehicleIdResponse401
  | getCitizenCpfVehiclesVehicleIdResponse403
  | getCitizenCpfVehiclesVehicleIdResponse404
  | getCitizenCpfVehiclesVehicleIdResponse500
) & {
  headers: Headers
}

export type getCitizenCpfVehiclesVehicleIdResponse =
  | getCitizenCpfVehiclesVehicleIdResponseSuccess
  | getCitizenCpfVehiclesVehicleIdResponseError

export const getGetCitizenCpfVehiclesVehicleIdUrl = (
  cpf: string,
  vehicleId: string
) => {
  return `/citizen/${cpf}/vehicles/${vehicleId}`
}

/**
 * Retorna o detalhe do veículo para proprietário ou condutor aceito (inclui invoice_photo_url, metadados de arquivos e registration_number). Quando role=conductor, inclui conductor_id (id do vínculo aceito). owner_name/owner_phone/owner_email são enriquecidos ao vivo via RMI a partir de owner_cpf. brand_name/model_name vêm do catálogo quando há brand_id/model_id e não há texto livre (*_other).
 * @summary Obter detalhe do veículo
 */
export const getCitizenCpfVehiclesVehicleId = async (
  cpf: string,
  vehicleId: string,
  options?: RequestInit
): Promise<getCitizenCpfVehiclesVehicleIdResponse> => {
  return customFetch<getCitizenCpfVehiclesVehicleIdResponse>(
    getGetCitizenCpfVehiclesVehicleIdUrl(cpf, vehicleId),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type patchCitizenCpfVehiclesVehicleIdResponse200 = {
  data: ModelsVehicleDetail
  status: 200
}

export type patchCitizenCpfVehiclesVehicleIdResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type patchCitizenCpfVehiclesVehicleIdResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type patchCitizenCpfVehiclesVehicleIdResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type patchCitizenCpfVehiclesVehicleIdResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type patchCitizenCpfVehiclesVehicleIdResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type patchCitizenCpfVehiclesVehicleIdResponseSuccess =
  patchCitizenCpfVehiclesVehicleIdResponse200 & {
    headers: Headers
  }
export type patchCitizenCpfVehiclesVehicleIdResponseError = (
  | patchCitizenCpfVehiclesVehicleIdResponse400
  | patchCitizenCpfVehiclesVehicleIdResponse401
  | patchCitizenCpfVehiclesVehicleIdResponse403
  | patchCitizenCpfVehiclesVehicleIdResponse404
  | patchCitizenCpfVehiclesVehicleIdResponse500
) & {
  headers: Headers
}

export type patchCitizenCpfVehiclesVehicleIdResponse =
  | patchCitizenCpfVehiclesVehicleIdResponseSuccess
  | patchCitizenCpfVehiclesVehicleIdResponseError

export const getPatchCitizenCpfVehiclesVehicleIdUrl = (
  cpf: string,
  vehicleId: string
) => {
  return `/citizen/${cpf}/vehicles/${vehicleId}`
}

/**
 * Atualiza campos do veículo (somente proprietário). Em mudança de marca/modelo do catálogo, vehicle_type é rederivado do modelo. Para trocar para fluxo Outro (texto livre), envie brand_id/model_id como null (ou "") junto com brand_other/model_other e vehicle_type; campo omitido não altera o valor atual.
 * @summary Atualizar veículo
 */
export const patchCitizenCpfVehiclesVehicleId = async (
  cpf: string,
  vehicleId: string,
  modelsVehicleUpdateRequest: ModelsVehicleUpdateRequest,
  options?: RequestInit
): Promise<patchCitizenCpfVehiclesVehicleIdResponse> => {
  return customFetch<patchCitizenCpfVehiclesVehicleIdResponse>(
    getPatchCitizenCpfVehiclesVehicleIdUrl(cpf, vehicleId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsVehicleUpdateRequest),
    }
  )
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse200 = {
  data: ModelsConductorsListResponse
  status: 200
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponseSuccess =
  getCitizenCpfVehiclesVehicleIdConductorsResponse200 & {
    headers: Headers
  }
export type getCitizenCpfVehiclesVehicleIdConductorsResponseError = (
  | getCitizenCpfVehiclesVehicleIdConductorsResponse400
  | getCitizenCpfVehiclesVehicleIdConductorsResponse401
  | getCitizenCpfVehiclesVehicleIdConductorsResponse403
  | getCitizenCpfVehiclesVehicleIdConductorsResponse404
  | getCitizenCpfVehiclesVehicleIdConductorsResponse500
) & {
  headers: Headers
}

export type getCitizenCpfVehiclesVehicleIdConductorsResponse =
  | getCitizenCpfVehiclesVehicleIdConductorsResponseSuccess
  | getCitizenCpfVehiclesVehicleIdConductorsResponseError

export const getGetCitizenCpfVehiclesVehicleIdConductorsUrl = (
  cpf: string,
  vehicleId: string
) => {
  return `/citizen/${cpf}/vehicles/${vehicleId}/conductors`
}

/**
 * Lista vínculos pending e accepted (somente proprietário). Pending devolve snapshot do convite; accepted enriquece nome/e-mail/celular ao vivo via RMI.
 * @summary Listar condutores do veículo
 */
export const getCitizenCpfVehiclesVehicleIdConductors = async (
  cpf: string,
  vehicleId: string,
  options?: RequestInit
): Promise<getCitizenCpfVehiclesVehicleIdConductorsResponse> => {
  return customFetch<getCitizenCpfVehiclesVehicleIdConductorsResponse>(
    getGetCitizenCpfVehiclesVehicleIdConductorsUrl(cpf, vehicleId),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse201 = {
  data: ModelsVehicleConductor
  status: 201
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponseSuccess =
  postCitizenCpfVehiclesVehicleIdConductorsResponse201 & {
    headers: Headers
  }
export type postCitizenCpfVehiclesVehicleIdConductorsResponseError = (
  | postCitizenCpfVehiclesVehicleIdConductorsResponse400
  | postCitizenCpfVehiclesVehicleIdConductorsResponse401
  | postCitizenCpfVehiclesVehicleIdConductorsResponse403
  | postCitizenCpfVehiclesVehicleIdConductorsResponse404
  | postCitizenCpfVehiclesVehicleIdConductorsResponse409
  | postCitizenCpfVehiclesVehicleIdConductorsResponse500
) & {
  headers: Headers
}

export type postCitizenCpfVehiclesVehicleIdConductorsResponse =
  | postCitizenCpfVehiclesVehicleIdConductorsResponseSuccess
  | postCitizenCpfVehiclesVehicleIdConductorsResponseError

export const getPostCitizenCpfVehiclesVehicleIdConductorsUrl = (
  cpf: string,
  vehicleId: string
) => {
  return `/citizen/${cpf}/vehicles/${vehicleId}/conductors`
}

/**
 * Cria vínculo pending e enfileira e-mail de convite via notify_email do body (somente proprietário). name/phone são hints opcionais enquanto pending. Duplicata pending/accepted retorna 409.
 * @summary Convidar condutor
 */
export const postCitizenCpfVehiclesVehicleIdConductors = async (
  cpf: string,
  vehicleId: string,
  modelsInviteConductorRequest: ModelsInviteConductorRequest,
  options?: RequestInit
): Promise<postCitizenCpfVehiclesVehicleIdConductorsResponse> => {
  return customFetch<postCitizenCpfVehiclesVehicleIdConductorsResponse>(
    getPostCitizenCpfVehiclesVehicleIdConductorsUrl(cpf, vehicleId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsInviteConductorRequest),
    }
  )
}

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse204 =
  {
    data: void
    status: 204
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse400 =
  {
    data: HandlersErrorResponse
    status: 400
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse401 =
  {
    data: HandlersErrorResponse
    status: 401
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse403 =
  {
    data: HandlersErrorResponse
    status: 403
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse404 =
  {
    data: HandlersErrorResponse
    status: 404
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse500 =
  {
    data: HandlersErrorResponse
    status: 500
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponseSuccess =
  deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse204 & {
    headers: Headers
  }
export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponseError =
  (
    | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse400
    | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse401
    | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse403
    | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse404
    | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse500
  ) & {
    headers: Headers
  }

export type deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse =
  | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponseSuccess
  | deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponseError

export const getDeleteCitizenCpfVehiclesVehicleIdConductorsConductorIdUrl = (
  cpf: string,
  vehicleId: string,
  conductorId: string
) => {
  return `/citizen/${cpf}/vehicles/${vehicleId}/conductors/${conductorId}`
}

/**
 * Proprietário revoga pending/accepted; condutor aceito pode sair (self-leave).
 * @summary Remover / revogar condutor
 */
export const deleteCitizenCpfVehiclesVehicleIdConductorsConductorId = async (
  cpf: string,
  vehicleId: string,
  conductorId: string,
  options?: RequestInit
): Promise<deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse> => {
  return customFetch<deleteCitizenCpfVehiclesVehicleIdConductorsConductorIdResponse>(
    getDeleteCitizenCpfVehiclesVehicleIdConductorsConductorIdUrl(
      cpf,
      vehicleId,
      conductorId
    ),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getMobilidadeVehicleBrandsResponse200 = {
  data: ModelsVehicleBrandsResponse
  status: 200
}

export type getMobilidadeVehicleBrandsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getMobilidadeVehicleBrandsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getMobilidadeVehicleBrandsResponseSuccess =
  getMobilidadeVehicleBrandsResponse200 & {
    headers: Headers
  }
export type getMobilidadeVehicleBrandsResponseError = (
  | getMobilidadeVehicleBrandsResponse401
  | getMobilidadeVehicleBrandsResponse500
) & {
  headers: Headers
}

export type getMobilidadeVehicleBrandsResponse =
  | getMobilidadeVehicleBrandsResponseSuccess
  | getMobilidadeVehicleBrandsResponseError

export const getGetMobilidadeVehicleBrandsUrl = () => {
  return `/mobilidade/vehicle-brands`
}

/**
 * Catálogo de marcas para o formulário de mobilidade (seed Mongo). Sentinel "Outro" usa id estável brand_outro com is_other=true.
 * @summary Listar marcas de veículos
 */
export const getMobilidadeVehicleBrands = async (
  options?: RequestInit
): Promise<getMobilidadeVehicleBrandsResponse> => {
  return customFetch<getMobilidadeVehicleBrandsResponse>(
    getGetMobilidadeVehicleBrandsUrl(),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getMobilidadeVehicleColorsResponse200 = {
  data: ModelsVehicleColorsResponse
  status: 200
}

export type getMobilidadeVehicleColorsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getMobilidadeVehicleColorsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getMobilidadeVehicleColorsResponseSuccess =
  getMobilidadeVehicleColorsResponse200 & {
    headers: Headers
  }
export type getMobilidadeVehicleColorsResponseError = (
  | getMobilidadeVehicleColorsResponse401
  | getMobilidadeVehicleColorsResponse500
) & {
  headers: Headers
}

export type getMobilidadeVehicleColorsResponse =
  | getMobilidadeVehicleColorsResponseSuccess
  | getMobilidadeVehicleColorsResponseError

export const getGetMobilidadeVehicleColorsUrl = () => {
  return `/mobilidade/vehicle-colors`
}

/**
 * Lista fixa de cores permitidas no formulário de mobilidade (fora do CSV de marcas/modelos).
 * @summary Listar cores de veículos
 */
export const getMobilidadeVehicleColors = async (
  options?: RequestInit
): Promise<getMobilidadeVehicleColorsResponse> => {
  return customFetch<getMobilidadeVehicleColorsResponse>(
    getGetMobilidadeVehicleColorsUrl(),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getMobilidadeVehicleModelsResponse200 = {
  data: ModelsVehicleModelsResponse
  status: 200
}

export type getMobilidadeVehicleModelsResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getMobilidadeVehicleModelsResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getMobilidadeVehicleModelsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getMobilidadeVehicleModelsResponseSuccess =
  getMobilidadeVehicleModelsResponse200 & {
    headers: Headers
  }
export type getMobilidadeVehicleModelsResponseError = (
  | getMobilidadeVehicleModelsResponse400
  | getMobilidadeVehicleModelsResponse401
  | getMobilidadeVehicleModelsResponse500
) & {
  headers: Headers
}

export type getMobilidadeVehicleModelsResponse =
  | getMobilidadeVehicleModelsResponseSuccess
  | getMobilidadeVehicleModelsResponseError

export const getGetMobilidadeVehicleModelsUrl = (
  params: GetMobilidadeVehicleModelsParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/mobilidade/vehicle-models?${stringifiedParams}`
    : `/mobilidade/vehicle-models`
}

/**
 * Modelos do catálogo filtrados por brand_id (obrigatório), incluindo vehicle_type. Sentinel "Outro" usa id estável model_outro com is_other=true.
 * @summary Listar modelos de veículos por marca
 */
export const getMobilidadeVehicleModels = async (
  params: GetMobilidadeVehicleModelsParams,
  options?: RequestInit
): Promise<getMobilidadeVehicleModelsResponse> => {
  return customFetch<getMobilidadeVehicleModelsResponse>(
    getGetMobilidadeVehicleModelsUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}
