/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeVagasId200,
  DeleteApiV1EmpregabilidadeVagasId400,
  DeleteApiV1EmpregabilidadeVagasId500,
  EmpregabilidadeUpdateTiposPCDRequest,
  EmpregabilidadeVaga,
  EmpregabilidadeVagaBody,
  GetApiV1EmpregabilidadeVagas200,
  GetApiV1EmpregabilidadeVagas500,
  GetApiV1EmpregabilidadeVagasId400,
  GetApiV1EmpregabilidadeVagasId404,
  GetApiV1EmpregabilidadeVagasId500,
  GetApiV1EmpregabilidadeVagasParams,
  PostApiV1EmpregabilidadeVagas400,
  PostApiV1EmpregabilidadeVagas500,
  PostApiV1EmpregabilidadeVagasDraft400,
  PostApiV1EmpregabilidadeVagasDraft500,
  PutApiV1EmpregabilidadeVagasId400,
  PutApiV1EmpregabilidadeVagasId500,
  PutApiV1EmpregabilidadeVagasIdDiscontinue200,
  PutApiV1EmpregabilidadeVagasIdDiscontinue400,
  PutApiV1EmpregabilidadeVagasIdDiscontinue404,
  PutApiV1EmpregabilidadeVagasIdDiscontinue409,
  PutApiV1EmpregabilidadeVagasIdDiscontinue500,
  PutApiV1EmpregabilidadeVagasIdFreeze200,
  PutApiV1EmpregabilidadeVagasIdFreeze400,
  PutApiV1EmpregabilidadeVagasIdFreeze404,
  PutApiV1EmpregabilidadeVagasIdFreeze409,
  PutApiV1EmpregabilidadeVagasIdFreeze500,
  PutApiV1EmpregabilidadeVagasIdPublish200,
  PutApiV1EmpregabilidadeVagasIdPublish400,
  PutApiV1EmpregabilidadeVagasIdPublish404,
  PutApiV1EmpregabilidadeVagasIdPublish409,
  PutApiV1EmpregabilidadeVagasIdPublish500,
  PutApiV1EmpregabilidadeVagasIdReactivate200,
  PutApiV1EmpregabilidadeVagasIdReactivate400,
  PutApiV1EmpregabilidadeVagasIdReactivate404,
  PutApiV1EmpregabilidadeVagasIdReactivate409,
  PutApiV1EmpregabilidadeVagasIdReactivate500,
  PutApiV1EmpregabilidadeVagasIdSendToApproval200,
  PutApiV1EmpregabilidadeVagasIdSendToApproval400,
  PutApiV1EmpregabilidadeVagasIdSendToApproval404,
  PutApiV1EmpregabilidadeVagasIdSendToApproval409,
  PutApiV1EmpregabilidadeVagasIdSendToApproval500,
  PutApiV1EmpregabilidadeVagasIdSendToDraft200,
  PutApiV1EmpregabilidadeVagasIdSendToDraft400,
  PutApiV1EmpregabilidadeVagasIdSendToDraft404,
  PutApiV1EmpregabilidadeVagasIdSendToDraft409,
  PutApiV1EmpregabilidadeVagasIdSendToDraft500,
  PutApiV1EmpregabilidadeVagasIdTiposPcd200,
  PutApiV1EmpregabilidadeVagasIdTiposPcd400,
  PutApiV1EmpregabilidadeVagasIdTiposPcd500,
  PutApiV1EmpregabilidadeVagasIdUnfreeze200,
  PutApiV1EmpregabilidadeVagasIdUnfreeze400,
  PutApiV1EmpregabilidadeVagasIdUnfreeze404,
  PutApiV1EmpregabilidadeVagasIdUnfreeze409,
  PutApiV1EmpregabilidadeVagasIdUnfreeze500,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna lista paginada de vagas com filtros opcionais
 * @summary Listar vagas
 */
export type getApiV1EmpregabilidadeVagasResponse200 = {
  data: GetApiV1EmpregabilidadeVagas200
  status: 200
}

export type getApiV1EmpregabilidadeVagasResponse500 = {
  data: GetApiV1EmpregabilidadeVagas500
  status: 500
}

export type getApiV1EmpregabilidadeVagasResponseComposite =
  | getApiV1EmpregabilidadeVagasResponse200
  | getApiV1EmpregabilidadeVagasResponse500

export type getApiV1EmpregabilidadeVagasResponse =
  getApiV1EmpregabilidadeVagasResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeVagasUrl = (
  params?: GetApiV1EmpregabilidadeVagasParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/vagas?${stringifiedParams}`
    : `/api/v1/empregabilidade/vagas`
}

export const getApiV1EmpregabilidadeVagas = async (
  params?: GetApiV1EmpregabilidadeVagasParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeVagasResponse> => {
  return customFetch<getApiV1EmpregabilidadeVagasResponse>(
    getGetApiV1EmpregabilidadeVagasUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma nova vaga
 * @summary Criar vaga
 */
export type postApiV1EmpregabilidadeVagasResponse201 = {
  data: EmpregabilidadeVaga
  status: 201
}

export type postApiV1EmpregabilidadeVagasResponse400 = {
  data: PostApiV1EmpregabilidadeVagas400
  status: 400
}

export type postApiV1EmpregabilidadeVagasResponse500 = {
  data: PostApiV1EmpregabilidadeVagas500
  status: 500
}

export type postApiV1EmpregabilidadeVagasResponseComposite =
  | postApiV1EmpregabilidadeVagasResponse201
  | postApiV1EmpregabilidadeVagasResponse400
  | postApiV1EmpregabilidadeVagasResponse500

export type postApiV1EmpregabilidadeVagasResponse =
  postApiV1EmpregabilidadeVagasResponseComposite & {
    headers: Headers
  }

export const getPostApiV1EmpregabilidadeVagasUrl = () => {
  return `/api/v1/empregabilidade/vagas`
}

export const postApiV1EmpregabilidadeVagas = async (
  empregabilidadeVagaBody: EmpregabilidadeVagaBody,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeVagasResponse> => {
  return customFetch<postApiV1EmpregabilidadeVagasResponse>(
    getPostApiV1EmpregabilidadeVagasUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeVagaBody),
    }
  )
}

/**
 * Cria uma nova vaga
 * @summary Criar vaga
 */
export type postApiV1EmpregabilidadeVagasDraftResponse201 = {
  data: EmpregabilidadeVaga
  status: 201
}

export type postApiV1EmpregabilidadeVagasDraftResponse400 = {
  data: PostApiV1EmpregabilidadeVagasDraft400
  status: 400
}

export type postApiV1EmpregabilidadeVagasDraftResponse500 = {
  data: PostApiV1EmpregabilidadeVagasDraft500
  status: 500
}

export type postApiV1EmpregabilidadeVagasDraftResponseComposite =
  | postApiV1EmpregabilidadeVagasDraftResponse201
  | postApiV1EmpregabilidadeVagasDraftResponse400
  | postApiV1EmpregabilidadeVagasDraftResponse500

export type postApiV1EmpregabilidadeVagasDraftResponse =
  postApiV1EmpregabilidadeVagasDraftResponseComposite & {
    headers: Headers
  }

export const getPostApiV1EmpregabilidadeVagasDraftUrl = () => {
  return `/api/v1/empregabilidade/vagas/draft`
}

export const postApiV1EmpregabilidadeVagasDraft = async (
  empregabilidadeVagaBody: EmpregabilidadeVagaBody,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeVagasDraftResponse> => {
  return customFetch<postApiV1EmpregabilidadeVagasDraftResponse>(
    getPostApiV1EmpregabilidadeVagasDraftUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeVagaBody),
    }
  )
}

/**
 * Retorna uma vaga pelo ID
 * @summary Buscar vaga
 */
export type getApiV1EmpregabilidadeVagasIdResponse200 = {
  data: EmpregabilidadeVaga
  status: 200
}

export type getApiV1EmpregabilidadeVagasIdResponse400 = {
  data: GetApiV1EmpregabilidadeVagasId400
  status: 400
}

export type getApiV1EmpregabilidadeVagasIdResponse404 = {
  data: GetApiV1EmpregabilidadeVagasId404
  status: 404
}

export type getApiV1EmpregabilidadeVagasIdResponse500 = {
  data: GetApiV1EmpregabilidadeVagasId500
  status: 500
}

export type getApiV1EmpregabilidadeVagasIdResponseComposite =
  | getApiV1EmpregabilidadeVagasIdResponse200
  | getApiV1EmpregabilidadeVagasIdResponse400
  | getApiV1EmpregabilidadeVagasIdResponse404
  | getApiV1EmpregabilidadeVagasIdResponse500

export type getApiV1EmpregabilidadeVagasIdResponse =
  getApiV1EmpregabilidadeVagasIdResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeVagasIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}`
}

export const getApiV1EmpregabilidadeVagasId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeVagasIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeVagasIdResponse>(
    getGetApiV1EmpregabilidadeVagasIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma vaga existente
 * @summary Atualizar vaga
 */
export type putApiV1EmpregabilidadeVagasIdResponse200 = {
  data: EmpregabilidadeVaga
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdResponse400 = {
  data: PutApiV1EmpregabilidadeVagasId400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdResponse500 = {
  data: PutApiV1EmpregabilidadeVagasId500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdResponseComposite =
  | putApiV1EmpregabilidadeVagasIdResponse200
  | putApiV1EmpregabilidadeVagasIdResponse400
  | putApiV1EmpregabilidadeVagasIdResponse500

export type putApiV1EmpregabilidadeVagasIdResponse =
  putApiV1EmpregabilidadeVagasIdResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}`
}

export const putApiV1EmpregabilidadeVagasId = async (
  id: string,
  empregabilidadeVagaBody: EmpregabilidadeVagaBody,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdResponse>(
    getPutApiV1EmpregabilidadeVagasIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeVagaBody),
    }
  )
}

/**
 * Remove uma vaga pelo ID
 * @summary Excluir vaga
 */
export type deleteApiV1EmpregabilidadeVagasIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeVagasId200
  status: 200
}

export type deleteApiV1EmpregabilidadeVagasIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeVagasId400
  status: 400
}

export type deleteApiV1EmpregabilidadeVagasIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeVagasId500
  status: 500
}

export type deleteApiV1EmpregabilidadeVagasIdResponseComposite =
  | deleteApiV1EmpregabilidadeVagasIdResponse200
  | deleteApiV1EmpregabilidadeVagasIdResponse400
  | deleteApiV1EmpregabilidadeVagasIdResponse500

export type deleteApiV1EmpregabilidadeVagasIdResponse =
  deleteApiV1EmpregabilidadeVagasIdResponseComposite & {
    headers: Headers
  }

export const getDeleteApiV1EmpregabilidadeVagasIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}`
}

export const deleteApiV1EmpregabilidadeVagasId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeVagasIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeVagasIdResponse>(
    getDeleteApiV1EmpregabilidadeVagasIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

/**
 * Descontinua uma vaga publicada ou congelada e atualiza o status de todas as candidaturas para vaga_descontinuada
 * @summary Descontinuar vaga
 */
export type putApiV1EmpregabilidadeVagasIdDiscontinueResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdDiscontinue200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdDiscontinueResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdDiscontinue400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdDiscontinueResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdDiscontinue404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdDiscontinueResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdDiscontinue409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdDiscontinueResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdDiscontinue500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdDiscontinueResponseComposite =
  | putApiV1EmpregabilidadeVagasIdDiscontinueResponse200
  | putApiV1EmpregabilidadeVagasIdDiscontinueResponse400
  | putApiV1EmpregabilidadeVagasIdDiscontinueResponse404
  | putApiV1EmpregabilidadeVagasIdDiscontinueResponse409
  | putApiV1EmpregabilidadeVagasIdDiscontinueResponse500

export type putApiV1EmpregabilidadeVagasIdDiscontinueResponse =
  putApiV1EmpregabilidadeVagasIdDiscontinueResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdDiscontinueUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/discontinue`
}

export const putApiV1EmpregabilidadeVagasIdDiscontinue = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdDiscontinueResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdDiscontinueResponse>(
    getPutApiV1EmpregabilidadeVagasIdDiscontinueUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Congela uma vaga publicada e atualiza o status de todas as candidaturas vinculadas para vaga_congelada
 * @summary Congelar vaga
 */
export type putApiV1EmpregabilidadeVagasIdFreezeResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdFreeze200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdFreezeResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdFreeze400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdFreezeResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdFreeze404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdFreezeResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdFreeze409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdFreezeResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdFreeze500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdFreezeResponseComposite =
  | putApiV1EmpregabilidadeVagasIdFreezeResponse200
  | putApiV1EmpregabilidadeVagasIdFreezeResponse400
  | putApiV1EmpregabilidadeVagasIdFreezeResponse404
  | putApiV1EmpregabilidadeVagasIdFreezeResponse409
  | putApiV1EmpregabilidadeVagasIdFreezeResponse500

export type putApiV1EmpregabilidadeVagasIdFreezeResponse =
  putApiV1EmpregabilidadeVagasIdFreezeResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdFreezeUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/freeze`
}

export const putApiV1EmpregabilidadeVagasIdFreeze = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdFreezeResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdFreezeResponse>(
    getPutApiV1EmpregabilidadeVagasIdFreezeUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Publica uma vaga em edição
 * @summary Publicar vaga
 */
export type putApiV1EmpregabilidadeVagasIdPublishResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdPublish200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdPublishResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdPublish400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdPublishResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdPublish404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdPublishResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdPublish409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdPublishResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdPublish500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdPublishResponseComposite =
  | putApiV1EmpregabilidadeVagasIdPublishResponse200
  | putApiV1EmpregabilidadeVagasIdPublishResponse400
  | putApiV1EmpregabilidadeVagasIdPublishResponse404
  | putApiV1EmpregabilidadeVagasIdPublishResponse409
  | putApiV1EmpregabilidadeVagasIdPublishResponse500

export type putApiV1EmpregabilidadeVagasIdPublishResponse =
  putApiV1EmpregabilidadeVagasIdPublishResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdPublishUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/publish`
}

export const putApiV1EmpregabilidadeVagasIdPublish = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdPublishResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdPublishResponse>(
    getPutApiV1EmpregabilidadeVagasIdPublishUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Reativa uma vaga descontinuada e restaura o status anterior das candidaturas
 * @summary Reativar vaga
 */
export type putApiV1EmpregabilidadeVagasIdReactivateResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdReactivate200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdReactivateResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdReactivate400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdReactivateResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdReactivate404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdReactivateResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdReactivate409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdReactivateResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdReactivate500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdReactivateResponseComposite =
  | putApiV1EmpregabilidadeVagasIdReactivateResponse200
  | putApiV1EmpregabilidadeVagasIdReactivateResponse400
  | putApiV1EmpregabilidadeVagasIdReactivateResponse404
  | putApiV1EmpregabilidadeVagasIdReactivateResponse409
  | putApiV1EmpregabilidadeVagasIdReactivateResponse500

export type putApiV1EmpregabilidadeVagasIdReactivateResponse =
  putApiV1EmpregabilidadeVagasIdReactivateResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdReactivateUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/reactivate`
}

export const putApiV1EmpregabilidadeVagasIdReactivate = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdReactivateResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdReactivateResponse>(
    getPutApiV1EmpregabilidadeVagasIdReactivateUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Envia uma vaga em edição para o fluxo de aprovação
 * @summary Enviar vaga para aprovação
 */
export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToApproval200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToApproval400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToApproval404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToApproval409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToApproval500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponseComposite =
  | putApiV1EmpregabilidadeVagasIdSendToApprovalResponse200
  | putApiV1EmpregabilidadeVagasIdSendToApprovalResponse400
  | putApiV1EmpregabilidadeVagasIdSendToApprovalResponse404
  | putApiV1EmpregabilidadeVagasIdSendToApprovalResponse409
  | putApiV1EmpregabilidadeVagasIdSendToApprovalResponse500

export type putApiV1EmpregabilidadeVagasIdSendToApprovalResponse =
  putApiV1EmpregabilidadeVagasIdSendToApprovalResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdSendToApprovalUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/vagas/${id}/send-to-approval`
}

export const putApiV1EmpregabilidadeVagasIdSendToApproval = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdSendToApprovalResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdSendToApprovalResponse>(
    getPutApiV1EmpregabilidadeVagasIdSendToApprovalUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Retorna uma vaga em aprovação para o estado de edição (rascunho)
 * @summary Retornar vaga para rascunho
 */
export type putApiV1EmpregabilidadeVagasIdSendToDraftResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToDraft200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdSendToDraftResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToDraft400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdSendToDraftResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToDraft404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdSendToDraftResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToDraft409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdSendToDraftResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdSendToDraft500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdSendToDraftResponseComposite =
  | putApiV1EmpregabilidadeVagasIdSendToDraftResponse200
  | putApiV1EmpregabilidadeVagasIdSendToDraftResponse400
  | putApiV1EmpregabilidadeVagasIdSendToDraftResponse404
  | putApiV1EmpregabilidadeVagasIdSendToDraftResponse409
  | putApiV1EmpregabilidadeVagasIdSendToDraftResponse500

export type putApiV1EmpregabilidadeVagasIdSendToDraftResponse =
  putApiV1EmpregabilidadeVagasIdSendToDraftResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdSendToDraftUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/send-to-draft`
}

export const putApiV1EmpregabilidadeVagasIdSendToDraft = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdSendToDraftResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdSendToDraftResponse>(
    getPutApiV1EmpregabilidadeVagasIdSendToDraftUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}

/**
 * Atualiza os tipos de PCD aceitos na vaga
 * @summary Atualizar tipos PCD da vaga
 */
export type putApiV1EmpregabilidadeVagasIdTiposPcdResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdTiposPcd200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdTiposPcdResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdTiposPcd400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdTiposPcdResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdTiposPcd500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdTiposPcdResponseComposite =
  | putApiV1EmpregabilidadeVagasIdTiposPcdResponse200
  | putApiV1EmpregabilidadeVagasIdTiposPcdResponse400
  | putApiV1EmpregabilidadeVagasIdTiposPcdResponse500

export type putApiV1EmpregabilidadeVagasIdTiposPcdResponse =
  putApiV1EmpregabilidadeVagasIdTiposPcdResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdTiposPcdUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/tipos-pcd`
}

export const putApiV1EmpregabilidadeVagasIdTiposPcd = async (
  id: string,
  empregabilidadeUpdateTiposPCDRequest: EmpregabilidadeUpdateTiposPCDRequest,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdTiposPcdResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdTiposPcdResponse>(
    getPutApiV1EmpregabilidadeVagasIdTiposPcdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeUpdateTiposPCDRequest),
    }
  )
}

/**
 * Descongela uma vaga congelada e restaura o status anterior das candidaturas
 * @summary Descongelar vaga
 */
export type putApiV1EmpregabilidadeVagasIdUnfreezeResponse200 = {
  data: PutApiV1EmpregabilidadeVagasIdUnfreeze200
  status: 200
}

export type putApiV1EmpregabilidadeVagasIdUnfreezeResponse400 = {
  data: PutApiV1EmpregabilidadeVagasIdUnfreeze400
  status: 400
}

export type putApiV1EmpregabilidadeVagasIdUnfreezeResponse404 = {
  data: PutApiV1EmpregabilidadeVagasIdUnfreeze404
  status: 404
}

export type putApiV1EmpregabilidadeVagasIdUnfreezeResponse409 = {
  data: PutApiV1EmpregabilidadeVagasIdUnfreeze409
  status: 409
}

export type putApiV1EmpregabilidadeVagasIdUnfreezeResponse500 = {
  data: PutApiV1EmpregabilidadeVagasIdUnfreeze500
  status: 500
}

export type putApiV1EmpregabilidadeVagasIdUnfreezeResponseComposite =
  | putApiV1EmpregabilidadeVagasIdUnfreezeResponse200
  | putApiV1EmpregabilidadeVagasIdUnfreezeResponse400
  | putApiV1EmpregabilidadeVagasIdUnfreezeResponse404
  | putApiV1EmpregabilidadeVagasIdUnfreezeResponse409
  | putApiV1EmpregabilidadeVagasIdUnfreezeResponse500

export type putApiV1EmpregabilidadeVagasIdUnfreezeResponse =
  putApiV1EmpregabilidadeVagasIdUnfreezeResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasIdUnfreezeUrl = (id: string) => {
  return `/api/v1/empregabilidade/vagas/${id}/unfreeze`
}

export const putApiV1EmpregabilidadeVagasIdUnfreeze = async (
  id: string,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasIdUnfreezeResponse> => {
  return customFetch<putApiV1EmpregabilidadeVagasIdUnfreezeResponse>(
    getPutApiV1EmpregabilidadeVagasIdUnfreezeUrl(id),
    {
      ...options,
      method: 'PUT',
    }
  )
}
