/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type {
  HandlersErrorResponse,
  HandlersHealthResponse
} from '.././models';

import { customFetch } from '../../../custom-fetch';

/**
 * Verifica a saúde da API e suas dependências (MongoDB e Redis). Retorna status detalhado para cada serviço.
 * @summary Verificação de saúde
 */
export type getHealthResponse200 = {
  data: HandlersHealthResponse
  status: 200
}

export type getHealthResponse500 = {
  data: HandlersErrorResponse
  status: 500
}
    
export type getHealthResponseComposite = getHealthResponse200 | getHealthResponse500;
    
export type getHealthResponse = getHealthResponseComposite & {
  headers: Headers;
}

export const getGetHealthUrl = () => {


  

  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  return customFetch<getHealthResponse>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


