/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type {
  HandlersErrorResponse,
  ModelsNotificationPreferencesResponse,
  ModelsPhoneNotificationPreferencesResponse,
  ModelsUpdateCategoryPreferenceRequestBody,
  ModelsUpdateNotificationPreferencesRequestBody,
} from '.././models'

import { customFetch } from '../../../custom-fetch'

/**
 * Get notification preferences for a citizen including global and category opt-ins
 * @summary Get citizen notification preferences
 */
export type getCitizenCpfNotificationPreferencesResponse200 = {
  data: ModelsNotificationPreferencesResponse
  status: 200
}

export type getCitizenCpfNotificationPreferencesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getCitizenCpfNotificationPreferencesResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getCitizenCpfNotificationPreferencesResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getCitizenCpfNotificationPreferencesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getCitizenCpfNotificationPreferencesResponseComposite =
  | getCitizenCpfNotificationPreferencesResponse200
  | getCitizenCpfNotificationPreferencesResponse400
  | getCitizenCpfNotificationPreferencesResponse401
  | getCitizenCpfNotificationPreferencesResponse403
  | getCitizenCpfNotificationPreferencesResponse500

export type getCitizenCpfNotificationPreferencesResponse =
  getCitizenCpfNotificationPreferencesResponseComposite & {
    headers: Headers
  }

export const getGetCitizenCpfNotificationPreferencesUrl = (cpf: string) => {
  return `/citizen/${cpf}/notification-preferences`
}

export const getCitizenCpfNotificationPreferences = async (
  cpf: string,
  options?: RequestInit
): Promise<getCitizenCpfNotificationPreferencesResponse> => {
  return customFetch<getCitizenCpfNotificationPreferencesResponse>(
    getGetCitizenCpfNotificationPreferencesUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Update notification preferences for a citizen (global and/or category opt-ins)
 * @summary Update citizen notification preferences
 */
export type putCitizenCpfNotificationPreferencesResponse200 = {
  data: ModelsNotificationPreferencesResponse
  status: 200
}

export type putCitizenCpfNotificationPreferencesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type putCitizenCpfNotificationPreferencesResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type putCitizenCpfNotificationPreferencesResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type putCitizenCpfNotificationPreferencesResponse422 = {
  data: HandlersErrorResponse
  status: 422
}

export type putCitizenCpfNotificationPreferencesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type putCitizenCpfNotificationPreferencesResponseComposite =
  | putCitizenCpfNotificationPreferencesResponse200
  | putCitizenCpfNotificationPreferencesResponse400
  | putCitizenCpfNotificationPreferencesResponse401
  | putCitizenCpfNotificationPreferencesResponse403
  | putCitizenCpfNotificationPreferencesResponse422
  | putCitizenCpfNotificationPreferencesResponse500

export type putCitizenCpfNotificationPreferencesResponse =
  putCitizenCpfNotificationPreferencesResponseComposite & {
    headers: Headers
  }

export const getPutCitizenCpfNotificationPreferencesUrl = (cpf: string) => {
  return `/citizen/${cpf}/notification-preferences`
}

export const putCitizenCpfNotificationPreferences = async (
  cpf: string,
  modelsUpdateNotificationPreferencesRequestBody: ModelsUpdateNotificationPreferencesRequestBody,
  options?: RequestInit
): Promise<putCitizenCpfNotificationPreferencesResponse> => {
  return customFetch<putCitizenCpfNotificationPreferencesResponse>(
    getPutCitizenCpfNotificationPreferencesUrl(cpf),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsUpdateNotificationPreferencesRequestBody),
    }
  )
}

/**
 * Update opt-in preference for a single notification category
 * @summary Update single category preference
 */
export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse200 =
  {
    data: ModelsNotificationPreferencesResponse
    status: 200
  }

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse400 =
  {
    data: HandlersErrorResponse
    status: 400
  }

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse401 =
  {
    data: HandlersErrorResponse
    status: 401
  }

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse403 =
  {
    data: HandlersErrorResponse
    status: 403
  }

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse422 =
  {
    data: HandlersErrorResponse
    status: 422
  }

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse500 =
  {
    data: HandlersErrorResponse
    status: 500
  }

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponseComposite =
  | patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse200
  | patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse400
  | patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse401
  | patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse403
  | patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse422
  | patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse500

export type patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse =
  patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponseComposite & {
    headers: Headers
  }

export const getPatchCitizenCpfNotificationPreferencesCategoriesCategoryIdUrl =
  (cpf: string, categoryId: string) => {
    return `/citizen/${cpf}/notification-preferences/categories/${categoryId}`
  }

export const patchCitizenCpfNotificationPreferencesCategoriesCategoryId =
  async (
    cpf: string,
    categoryId: string,
    modelsUpdateCategoryPreferenceRequestBody: ModelsUpdateCategoryPreferenceRequestBody,
    options?: RequestInit
  ): Promise<patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse> => {
    return customFetch<patchCitizenCpfNotificationPreferencesCategoriesCategoryIdResponse>(
      getPatchCitizenCpfNotificationPreferencesCategoriesCategoryIdUrl(
        cpf,
        categoryId
      ),
      {
        ...options,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(modelsUpdateCategoryPreferenceRequestBody),
      }
    )
  }

/**
 * Get notification preferences for a phone number including global and category opt-ins (synced with CPF). Admin only.
 * @summary Get phone notification preferences (admin only)
 */
export type getPhonePhoneNumberNotificationPreferencesResponse200 = {
  data: ModelsPhoneNotificationPreferencesResponse
  status: 200
}

export type getPhonePhoneNumberNotificationPreferencesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getPhonePhoneNumberNotificationPreferencesResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getPhonePhoneNumberNotificationPreferencesResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getPhonePhoneNumberNotificationPreferencesResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type getPhonePhoneNumberNotificationPreferencesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getPhonePhoneNumberNotificationPreferencesResponseComposite =
  | getPhonePhoneNumberNotificationPreferencesResponse200
  | getPhonePhoneNumberNotificationPreferencesResponse400
  | getPhonePhoneNumberNotificationPreferencesResponse401
  | getPhonePhoneNumberNotificationPreferencesResponse403
  | getPhonePhoneNumberNotificationPreferencesResponse404
  | getPhonePhoneNumberNotificationPreferencesResponse500

export type getPhonePhoneNumberNotificationPreferencesResponse =
  getPhonePhoneNumberNotificationPreferencesResponseComposite & {
    headers: Headers
  }

export const getGetPhonePhoneNumberNotificationPreferencesUrl = (
  phoneNumber: string
) => {
  return `/phone/${phoneNumber}/notification-preferences`
}

export const getPhonePhoneNumberNotificationPreferences = async (
  phoneNumber: string,
  options?: RequestInit
): Promise<getPhonePhoneNumberNotificationPreferencesResponse> => {
  return customFetch<getPhonePhoneNumberNotificationPreferencesResponse>(
    getGetPhonePhoneNumberNotificationPreferencesUrl(phoneNumber),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Update notification preferences for a phone number (synced with CPF preferences). Admin only.
 * @summary Update phone notification preferences (admin only)
 */
export type putPhonePhoneNumberNotificationPreferencesResponse200 = {
  data: ModelsPhoneNotificationPreferencesResponse
  status: 200
}

export type putPhonePhoneNumberNotificationPreferencesResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type putPhonePhoneNumberNotificationPreferencesResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type putPhonePhoneNumberNotificationPreferencesResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type putPhonePhoneNumberNotificationPreferencesResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type putPhonePhoneNumberNotificationPreferencesResponse422 = {
  data: HandlersErrorResponse
  status: 422
}

export type putPhonePhoneNumberNotificationPreferencesResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type putPhonePhoneNumberNotificationPreferencesResponseComposite =
  | putPhonePhoneNumberNotificationPreferencesResponse200
  | putPhonePhoneNumberNotificationPreferencesResponse400
  | putPhonePhoneNumberNotificationPreferencesResponse401
  | putPhonePhoneNumberNotificationPreferencesResponse403
  | putPhonePhoneNumberNotificationPreferencesResponse404
  | putPhonePhoneNumberNotificationPreferencesResponse422
  | putPhonePhoneNumberNotificationPreferencesResponse500

export type putPhonePhoneNumberNotificationPreferencesResponse =
  putPhonePhoneNumberNotificationPreferencesResponseComposite & {
    headers: Headers
  }

export const getPutPhonePhoneNumberNotificationPreferencesUrl = (
  phoneNumber: string
) => {
  return `/phone/${phoneNumber}/notification-preferences`
}

export const putPhonePhoneNumberNotificationPreferences = async (
  phoneNumber: string,
  modelsUpdateNotificationPreferencesRequestBody: ModelsUpdateNotificationPreferencesRequestBody,
  options?: RequestInit
): Promise<putPhonePhoneNumberNotificationPreferencesResponse> => {
  return customFetch<putPhonePhoneNumberNotificationPreferencesResponse>(
    getPutPhonePhoneNumberNotificationPreferencesUrl(phoneNumber),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsUpdateNotificationPreferencesRequestBody),
    }
  )
}

/**
 * Update opt-in preference for a single notification category for a phone number. Admin only.
 * @summary Update single category preference for phone (admin only)
 */
export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse200 =
  {
    data: ModelsPhoneNotificationPreferencesResponse
    status: 200
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse400 =
  {
    data: HandlersErrorResponse
    status: 400
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse401 =
  {
    data: HandlersErrorResponse
    status: 401
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse403 =
  {
    data: HandlersErrorResponse
    status: 403
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse404 =
  {
    data: HandlersErrorResponse
    status: 404
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse422 =
  {
    data: HandlersErrorResponse
    status: 422
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse500 =
  {
    data: HandlersErrorResponse
    status: 500
  }

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponseComposite =
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse200
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse400
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse401
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse403
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse404
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse422
  | patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse500

export type patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse =
  patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponseComposite & {
    headers: Headers
  }

export const getPatchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdUrl =
  (phoneNumber: string, categoryId: string) => {
    return `/phone/${phoneNumber}/notification-preferences/categories/${categoryId}`
  }

export const patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryId =
  async (
    phoneNumber: string,
    categoryId: string,
    modelsUpdateCategoryPreferenceRequestBody: ModelsUpdateCategoryPreferenceRequestBody,
    options?: RequestInit
  ): Promise<patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse> => {
    return customFetch<patchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdResponse>(
      getPatchPhonePhoneNumberNotificationPreferencesCategoriesCategoryIdUrl(
        phoneNumber,
        categoryId
      ),
      {
        ...options,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(modelsUpdateCategoryPreferenceRequestBody),
      }
    )
  }
