/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export type GetAdminPhoneQuarantinedParams = {
  /**
   * Página (padrão: 1)
   */
  page?: number
  /**
   * Itens por página (padrão: 10)
   */
  per_page?: number
}
