/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export type GetCnaesParams = {
  /**
   * Número da página (padrão: 1)
   * @minimum 1
   */
  page?: number
  /**
   * Itens por página (padrão: 10, máximo: 100)
   * @minimum 1
   * @maximum 100
   */
  per_page?: number
  /**
   * Texto para busca na denominação
   */
  search?: string
  /**
   * Filtro por seção (ex: A)
   */
  secao?: string
  /**
   * Filtro por divisão (ex: 1)
   */
  divisao?: string
  /**
   * Filtro por grupo (ex: 1.1)
   */
  grupo?: string
  /**
   * Filtro por classe (ex: 01.12-1)
   */
  classe?: string
  /**
   * Filtro por subclasse
   */
  subclasse?: string
}
