/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export type GetDepartmentsParams = {
  /**
   * Código da UA pai para filtrar departamentos filhos
   */
  parent_id?: string
  /**
   * Nível mínimo do departamento
   * @minimum 1
   */
  min_level?: number
  /**
   * Nível máximo do departamento
   * @minimum 1
   */
  max_level?: number
  /**
   * Nível exato do departamento (sobrescreve min/max)
   * @minimum 1
   */
  exact_level?: number
  /**
   * Sigla da UA para filtro exato
   */
  sigla_ua?: string
  /**
   * Texto para busca textual em nome_ua
   */
  search?: string
  /**
   * Número da página (padrão: 1)
   * @minimum 1
   */
  page?: number
  /**
   * Itens por página (padrão: 10, máximo: 100)
   * @minimum 1
   * @maximum 100
   */
  per_page?: number
}
