/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

/**
 * Resultado da validação, contendo informações sobre o endereço de email quando válido.
 */
export interface HandlersEmailValidationResponse {
  /** Domínio do email (após o @) */
  domain?: string
  /** Parte local do email (antes do @) */
  local_part?: string
  /** Mensagem de retorno. */
  message?: string
  /** Email normalizado (lowercase) */
  normalized?: string
  /** Indica se o email é válido. */
  valid?: boolean
  /** Tipo de validação aplicada */
  validation_type?: string
}
