/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { HandlersSalesforceWebhookDados } from './handlersSalesforceWebhookDados'
import type { HandlersSalesforceWebhookRequestSwaggerEvento } from './handlersSalesforceWebhookRequestSwaggerEvento'

export interface HandlersSalesforceWebhookRequestSwagger {
  cpf?: string
  dados?: HandlersSalesforceWebhookDados
  evento?: HandlersSalesforceWebhookRequestSwaggerEvento
  updatedAt?: string
}
