/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { HandlersMemoryModelMemoryType } from './handlersMemoryModelMemoryType'
import type { HandlersMemoryModelRelevance } from './handlersMemoryModelRelevance'

export interface HandlersMemoryModel {
  created_at?: string
  description: string
  memory_id?: string
  memory_name: string
  memory_type: HandlersMemoryModelMemoryType
  relevance: HandlersMemoryModelRelevance
  updated_at?: string
  value: string
}
