/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { HandlersHealthResponseServices } from './handlersHealthResponseServices'

export interface HandlersHealthResponse {
  services?: HandlersHealthResponseServices
  status?: boolean
  timestamp?: string
  version?: string
}
