/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

/**
 * Resultado da validação, contendo a decomposição (DDI, DDD, número) quando válida.
 */
export interface HandlersPhoneValidationResponse {
  /** DDD (código de área) */
  ddd?: string
  /** DDI (código do país) */
  ddi?: string
  /** Representação E.164 do número */
  e164?: string
  /** Mensagem de retorno. */
  message?: string
  /** Número do assinante */
  numero?: string
  /** Região ISO 3166-1 alpha-2 */
  region?: string
  /** Indica se o número é válido. */
  valid?: boolean
}
