/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { ModelsPhoneNotificationPreferencesResponseCategoryOptIns } from './modelsPhoneNotificationPreferencesResponseCategoryOptIns'

export interface ModelsPhoneNotificationPreferencesResponse {
  category_opt_ins?: ModelsPhoneNotificationPreferencesResponseCategoryOptIns
  opt_in?: boolean
  phone_number?: string
  updated_at?: string
}
