/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { ModelsAccountant } from './modelsAccountant';
import type { ModelsLegalEntityContact } from './modelsLegalEntityContact';
import type { ModelsLegalEntityAddress } from './modelsLegalEntityAddress';
import type { ModelsFederativeEntity } from './modelsFederativeEntity';
import type { ModelsHeadquartersBranch } from './modelsHeadquartersBranch';
import type { ModelsLegalNature } from './modelsLegalNature';
import type { ModelsRegistrationAuthority } from './modelsRegistrationAuthority';
import type { ModelsCompanySize } from './modelsCompanySize';
import type { ModelsResponsiblePerson } from './modelsResponsiblePerson';
import type { ModelsRegistrationStatus } from './modelsRegistrationStatus';
import type { ModelsSpecialStatus } from './modelsSpecialStatus';
import type { ModelsPartner } from './modelsPartner';

export interface ModelsLegalEntity {
  _id?: unknown;
  capital_social?: number;
  cnae_fiscal?: string;
  cnae_secundarias?: string[];
  cnpj?: string;
  contador?: ModelsAccountant;
  contato?: ModelsLegalEntityContact;
  endereco?: ModelsLegalEntityAddress;
  ente_federativo?: ModelsFederativeEntity;
  formas_atuacao?: string[];
  inicio_atividade_data?: string;
  language?: string;
  matriz_filial?: ModelsHeadquartersBranch;
  natureza_juridica?: ModelsLegalNature;
  nire?: string;
  nome_fantasia?: string;
  orgao_registro?: ModelsRegistrationAuthority;
  porte?: ModelsCompanySize;
  razao_social?: string;
  responsavel?: ModelsResponsiblePerson;
  situacao_cadastral?: ModelsRegistrationStatus;
  situacao_especial?: ModelsSpecialStatus;
  socios?: ModelsPartner[];
  socios_quantidade?: number;
  sucessoes?: unknown[];
  tipos_unidade?: string[];
}
