/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsCadUnico {
  data_cadastro?: string
  data_limite_cadastro_atual?: string
  data_ultima_atualizacao?: string
  indicador?: boolean
  status_cadastral?: string
}
