/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { ModelsVehicleRole } from './modelsVehicleRole'
import type { ModelsVehicleType } from './modelsVehicleType'

export interface ModelsVehicleDetail {
  brand_id?: string
  /** BrandName is response-only: catalog brand name when brand_id is set and brand_other is empty. */
  brand_name?: string
  brand_other?: string
  color?: string
  conductor_id?: string
  created_at?: string
  deleted_at?: string
  display_name?: string
  has_invoice?: boolean
  id?: string
  invoice_photo_file_name?: string
  invoice_photo_file_size?: number
  invoice_photo_url?: string
  model_id?: string
  /** ModelName is response-only: catalog model name when model_id is set and model_other is empty. */
  model_name?: string
  model_other?: string
  owner_cpf?: string
  owner_email?: string
  owner_name?: string
  owner_phone?: string
  /** RegistrationNumber is a short wallet identifier generated on create (format RJ-E-XXXXXX). Not accepted in POST/PATCH. */
  registration_number?: string
  role?: ModelsVehicleRole
  self_declaration?: boolean
  serial_number?: string
  /** Optional file metadata for UI detail (Apêndice A.4). */
  serial_number_photo_file_name?: string
  serial_number_photo_file_size?: number
  serial_number_photo_url?: string
  updated_at?: string
  vehicle_photo_file_name?: string
  vehicle_photo_file_size?: number
  vehicle_photo_url?: string
  vehicle_type?: ModelsVehicleType
}
