/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsDepartmentResponse {
  cd_ua?: string
  cd_ua_pai?: string
  id?: string
  msg?: string
  nivel?: number
  nome_ua?: string
  ordem_absoluta?: string
  ordem_relativa?: string
  ordem_ua_basica?: string
  sigla_ua?: string
  updated_at?: string
}
