/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsPartner {
  cnpj_socio?: string
  codigo_pais?: string
  cpf_representante_legal?: string
  cpf_socio?: string
  data_situacao_especial?: string
  nome_socio_estrangeiro?: string
  qualificacao_representante_legal?: string
  qualificacao_socio?: string
  tipo?: string
}
