/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsEnderecoAlternativo {
  bairro?: string
  cep?: string
  complemento?: string
  estado?: string
  latitude?: string
  logradouro?: string
  longitude?: string
  municipio?: string
  numero?: string
  origem?: string
  pluscode?: string
  sistema?: string
  tipo_logradouro?: string
}
