/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsMaintenanceRequest {
  categoria?: string
  cpf?: string
  data_alvo_finalizacao?: string
  data_fim?: string
  data_inicio?: string
  descricao?: string
  /** Pre-built address string */
  endereco?: string
  id?: string
  /** Maps from MongoDB "id" field */
  id_chamado?: string
  indicador?: boolean
  nome_unidade_organizacional?: string
  origem_ocorrencia?: string
  status?: string
  subtipo?: string
  tipo?: string
  total_chamados?: number
  total_fechados?: number
}
