/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsQuarantineStats {
  active_quarantines?: number;
  expired_quarantines?: number;
  quarantine_history_total?: number;
  quarantines_with_cpf?: number;
  quarantines_without_cpf?: number;
  total_quarantined?: number;
}
