/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsBetaWhitelistMoveRequest {
  from_group_id: string
  phone_numbers: string[]
  to_group_id: string
}
