/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */

export interface ModelsMaintenanceRequest {
  categoria?: string
  cpf?: string
  data_alvo_diagnostico?: string
  data_alvo_finalizacao?: string
  data_fim?: string
  data_inicio?: string
  data_real_diagnostico?: string
  dentro_prazo?: string
  descricao?: string
  id?: string
  id_bairro?: string
  id_chamado?: string
  id_logradouro?: string
  id_origem_ocorrencia?: string
  id_subtipo?: string
  id_territorialidade?: string
  id_tipo?: string
  id_unidade_organizacional?: string
  id_unidade_organizacional_mae?: string
  justificativa_status?: string
  latitude?: number
  longitude?: number
  nome_unidade_organizacional?: string
  numero_logradouro?: number
  origem_ocorrencia?: string
  prazo_tipo?: string
  prazo_unidade?: string
  reclamacoes?: number
  situacao?: string
  status?: string
  subtipo?: string
  tempo_prazo?: string
  tipo?: string
  tipo_situacao?: string
  unidade_organizacional_ouvidoria?: string
}
