import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import {
  AnimationType,
  type PageTransitionsConfiguration,
  PageTransitionsProvider,
} from './page-transitions'

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600'],
})

export const metadata: Metadata = {
  title: 'Portal do Cidadão',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const config: PageTransitionsConfiguration = {
    animation: {
      type: AnimationType.SlideHorizontally,
      duration: 200,
    },
  }
  return (
    <html lang="pt-BR">
      <body className={`dark ${dmSans.className} bg-background antialiased`}>
        <PageTransitionsProvider config={config}>
          {children}
        </PageTransitionsProvider>
      </body>
    </html>
  )
}
