/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api-imoveis
 * Cadastro local de inscricoes imobiliarias e servicos de IPTU / Divida Ativa.
 * OpenAPI spec version: 1.0.0
 */
import type {
  FazendaImovel,
  GetImoveisInscricaoConsultaParams,
  GetImoveisInscricaoSegundaViaParams,
  ImovelConsultaResponse,
  ImovelRequest,
  ImovelResponse,
  OpcaoIptuResponse,
} from '../models'

import { customFetchDividaAtiva } from '../../../custom-fetch-divida-ativa'

export type getImoveisResponse200 = {
  data: ImovelResponse
  status: 200
}

export type getImoveisResponse401 = {
  data: void
  status: 401
}

export type getImoveisResponse503 = {
  data: void
  status: 503
}

export type getImoveisResponseSuccess = getImoveisResponse200 & {
  headers: Headers
}
export type getImoveisResponseError = (
  | getImoveisResponse401
  | getImoveisResponse503
) & {
  headers: Headers
}

export type getImoveisResponse =
  | getImoveisResponseSuccess
  | getImoveisResponseError

export const getGetImoveisUrl = () => {
  return `/imoveis`
}

/**
 * Valida o JWT no Keycloak, extrai o CPF da claim preferred_username e consulta somente o banco local dbo.tbNC_Imovel. Nao chama WS Fazenda nem ePortal.
 * @summary Lista os imoveis cadastrados do usuario autenticado
 */
export const getImoveis = async (
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<getImoveisResponse> => {
  return customFetchDividaAtiva<getImoveisResponse>(getGetImoveisUrl(), {
    ...options,
    method: 'GET',
  })
}

export type postImoveisResponse201 = {
  data: ImovelResponse
  status: 201
}

export type postImoveisResponse400 = {
  data: void
  status: 400
}

export type postImoveisResponse401 = {
  data: void
  status: 401
}

export type postImoveisResponse503 = {
  data: void
  status: 503
}

export type postImoveisResponseSuccess = postImoveisResponse201 & {
  headers: Headers
}
export type postImoveisResponseError = (
  | postImoveisResponse400
  | postImoveisResponse401
  | postImoveisResponse503
) & {
  headers: Headers
}

export type postImoveisResponse =
  | postImoveisResponseSuccess
  | postImoveisResponseError

export const getPostImoveisUrl = () => {
  return `/imoveis`
}

/**
 * Valida o JWT, consulta o WSFazenda_Iptu para buscar o endereco da inscricao informada e grava o imovel no banco local dbo.tbNC_Imovel vinculado ao CPF autenticado.
 * @summary Cadastra uma inscricao imobiliaria para o usuario
 */
export const postImoveis = async (
  imovelRequest: ImovelRequest,
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<postImoveisResponse> => {
  return customFetchDividaAtiva<postImoveisResponse>(getPostImoveisUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(imovelRequest),
  })
}

export type deleteImoveisIdResponse204 = {
  data: void
  status: 204
}

export type deleteImoveisIdResponse401 = {
  data: void
  status: 401
}

export type deleteImoveisIdResponse404 = {
  data: void
  status: 404
}

export type deleteImoveisIdResponseSuccess = deleteImoveisIdResponse204 & {
  headers: Headers
}
export type deleteImoveisIdResponseError = (
  | deleteImoveisIdResponse401
  | deleteImoveisIdResponse404
) & {
  headers: Headers
}

export type deleteImoveisIdResponse =
  | deleteImoveisIdResponseSuccess
  | deleteImoveisIdResponseError

export const getDeleteImoveisIdUrl = (id: number) => {
  return `/imoveis/${id}`
}

/**
 * Valida o JWT e remove do banco local o registro pelo id, desde que ele pertenca ao CPF autenticado. Nao remove dados em sistemas da Fazenda.
 * @summary Remove um imovel cadastrado
 */
export const deleteImoveisId = async (
  id: number,
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<deleteImoveisIdResponse> => {
  return customFetchDividaAtiva<deleteImoveisIdResponse>(
    getDeleteImoveisIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getImoveisInscricaoCadastroResponse200 = {
  data: FazendaImovel
  status: 200
}

export type getImoveisInscricaoCadastroResponse400 = {
  data: void
  status: 400
}

export type getImoveisInscricaoCadastroResponse401 = {
  data: void
  status: 401
}

export type getImoveisInscricaoCadastroResponse503 = {
  data: void
  status: 503
}

export type getImoveisInscricaoCadastroResponseSuccess =
  getImoveisInscricaoCadastroResponse200 & {
    headers: Headers
  }
export type getImoveisInscricaoCadastroResponseError = (
  | getImoveisInscricaoCadastroResponse400
  | getImoveisInscricaoCadastroResponse401
  | getImoveisInscricaoCadastroResponse503
) & {
  headers: Headers
}

export type getImoveisInscricaoCadastroResponse =
  | getImoveisInscricaoCadastroResponseSuccess
  | getImoveisInscricaoCadastroResponseError

export const getGetImoveisInscricaoCadastroUrl = (inscricao: string) => {
  return `/imoveis/${inscricao}/cadastro`
}

/**
 * Valida o JWT no Keycloak e, a partir da inscricao imobiliaria, consulta o WSFazenda_Iptu e retorna os dados cadastrais do imovel (endereco e inscricao normalizada). Nao consulta o banco local. Retorna lista vazia quando nao houver registro para a inscricao.
 * @summary Consulta os dados cadastrais do imovel no WSFazenda_Iptu
 */
export const getImoveisInscricaoCadastro = async (
  inscricao: string,
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<getImoveisInscricaoCadastroResponse> => {
  return customFetchDividaAtiva<getImoveisInscricaoCadastroResponse>(
    getGetImoveisInscricaoCadastroUrl(inscricao),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getImoveisInscricaoConsultaResponse200 = {
  data: ImovelConsultaResponse
  status: 200
}

export type getImoveisInscricaoConsultaResponse401 = {
  data: void
  status: 401
}

export type getImoveisInscricaoConsultaResponse404 = {
  data: void
  status: 404
}

export type getImoveisInscricaoConsultaResponse503 = {
  data: void
  status: 503
}

export type getImoveisInscricaoConsultaResponseSuccess =
  getImoveisInscricaoConsultaResponse200 & {
    headers: Headers
  }
export type getImoveisInscricaoConsultaResponseError = (
  | getImoveisInscricaoConsultaResponse401
  | getImoveisInscricaoConsultaResponse404
  | getImoveisInscricaoConsultaResponse503
) & {
  headers: Headers
}

export type getImoveisInscricaoConsultaResponse =
  | getImoveisInscricaoConsultaResponseSuccess
  | getImoveisInscricaoConsultaResponseError

export const getGetImoveisInscricaoConsultaUrl = (
  inscricao: string,
  params?: GetImoveisInscricaoConsultaParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/imoveis/${inscricao}/consulta?${stringifiedParams}`
    : `/imoveis/${inscricao}/consulta`
}

/**
 * Agrega dados do banco local com opcoes do ePortal. Primeiro busca o imovel em dbo.tbNC_Imovel pelo CPF autenticado e inscricao. Depois chama o SOAP manual do ePortal para verificar parcelamento e segunda via, retornando URLs com token cripto apenas quando o ePortal informar disponibilidade. Nao chama o WSFazenda_Iptu neste endpoint.
 * @summary Consulta o imovel e monta as opcoes disponiveis de IPTU
 */
export const getImoveisInscricaoConsulta = async (
  inscricao: string,
  params?: GetImoveisInscricaoConsultaParams,
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<getImoveisInscricaoConsultaResponse> => {
  return customFetchDividaAtiva<getImoveisInscricaoConsultaResponse>(
    getGetImoveisInscricaoConsultaUrl(inscricao, params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getImoveisInscricaoParcelamentosResponse200 = {
  data: OpcaoIptuResponse
  status: 200
}

export type getImoveisInscricaoParcelamentosResponse401 = {
  data: void
  status: 401
}

export type getImoveisInscricaoParcelamentosResponse503 = {
  data: void
  status: 503
}

export type getImoveisInscricaoParcelamentosResponseSuccess =
  getImoveisInscricaoParcelamentosResponse200 & {
    headers: Headers
  }
export type getImoveisInscricaoParcelamentosResponseError = (
  | getImoveisInscricaoParcelamentosResponse401
  | getImoveisInscricaoParcelamentosResponse503
) & {
  headers: Headers
}

export type getImoveisInscricaoParcelamentosResponse =
  | getImoveisInscricaoParcelamentosResponseSuccess
  | getImoveisInscricaoParcelamentosResponseError

export const getGetImoveisInscricaoParcelamentosUrl = (inscricao: string) => {
  return `/imoveis/${inscricao}/parcelamentos`
}

/**
 * Valida o JWT, chama o SOAP manual do ePortal VerificaDebitosParcelamentoInInscricao e retorna a URL de parcelamento com token cripto quando houver debitos parcelaveis. Nao consulta o WSFazenda_Iptu.
 * @summary Consulta somente a opcao de parcelamento
 */
export const getImoveisInscricaoParcelamentos = async (
  inscricao: string,
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<getImoveisInscricaoParcelamentosResponse> => {
  return customFetchDividaAtiva<getImoveisInscricaoParcelamentosResponse>(
    getGetImoveisInscricaoParcelamentosUrl(inscricao),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getImoveisInscricaoSegundaViaResponse200 = {
  data: OpcaoIptuResponse
  status: 200
}

export type getImoveisInscricaoSegundaViaResponse401 = {
  data: void
  status: 401
}

export type getImoveisInscricaoSegundaViaResponse503 = {
  data: void
  status: 503
}

export type getImoveisInscricaoSegundaViaResponseSuccess =
  getImoveisInscricaoSegundaViaResponse200 & {
    headers: Headers
  }
export type getImoveisInscricaoSegundaViaResponseError = (
  | getImoveisInscricaoSegundaViaResponse401
  | getImoveisInscricaoSegundaViaResponse503
) & {
  headers: Headers
}

export type getImoveisInscricaoSegundaViaResponse =
  | getImoveisInscricaoSegundaViaResponseSuccess
  | getImoveisInscricaoSegundaViaResponseError

export const getGetImoveisInscricaoSegundaViaUrl = (
  inscricao: string,
  params?: GetImoveisInscricaoSegundaViaParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/imoveis/${inscricao}/segunda-via?${stringifiedParams}`
    : `/imoveis/${inscricao}/segunda-via`
}

/**
 * Valida o JWT, consulta o SOAP manual do ePortal VerificaSegundaViaParcelamentoInInscricao e retorna a URL da segunda via com token cripto somente quando houver disponibilidade. O token da segunda via inclui CPF, inscricao, exercicio, email, nome e data. Para anos anteriores, o parametro exercicio deve ser informado.
 * @summary Monta somente a opcao de segunda via
 */
export const getImoveisInscricaoSegundaVia = async (
  inscricao: string,
  params?: GetImoveisInscricaoSegundaViaParams,
  options?: Parameters<typeof customFetchDividaAtiva>[1]
): Promise<getImoveisInscricaoSegundaViaResponse> => {
  return customFetchDividaAtiva<getImoveisInscricaoSegundaViaResponse>(
    getGetImoveisInscricaoSegundaViaUrl(inscricao, params),
    {
      ...options,
      method: 'GET',
    }
  )
}
