/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeCurriculoConquistasId200,
  DeleteApiV1EmpregabilidadeCurriculoConquistasId400,
  DeleteApiV1EmpregabilidadeCurriculoConquistasId403,
  DeleteApiV1EmpregabilidadeCurriculoConquistasId404,
  DeleteApiV1EmpregabilidadeCurriculoConquistasId500,
  DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId200,
  DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId400,
  DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId403,
  DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId404,
  DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId500,
  DeleteApiV1EmpregabilidadeCurriculoExperienciasId200,
  DeleteApiV1EmpregabilidadeCurriculoExperienciasId400,
  DeleteApiV1EmpregabilidadeCurriculoExperienciasId403,
  DeleteApiV1EmpregabilidadeCurriculoExperienciasId404,
  DeleteApiV1EmpregabilidadeCurriculoExperienciasId500,
  DeleteApiV1EmpregabilidadeCurriculoFormacoesId200,
  DeleteApiV1EmpregabilidadeCurriculoFormacoesId400,
  DeleteApiV1EmpregabilidadeCurriculoFormacoesId403,
  DeleteApiV1EmpregabilidadeCurriculoFormacoesId404,
  DeleteApiV1EmpregabilidadeCurriculoFormacoesId500,
  DeleteApiV1EmpregabilidadeCurriculoIdiomasId200,
  DeleteApiV1EmpregabilidadeCurriculoIdiomasId400,
  DeleteApiV1EmpregabilidadeCurriculoIdiomasId403,
  DeleteApiV1EmpregabilidadeCurriculoIdiomasId404,
  DeleteApiV1EmpregabilidadeCurriculoIdiomasId500,
  EmpregabilidadeCurriculoCompleto,
  EmpregabilidadeCurriculoConquista,
  EmpregabilidadeCurriculoCursoComplementar,
  EmpregabilidadeCurriculoExperiencia,
  EmpregabilidadeCurriculoFormacao,
  EmpregabilidadeCurriculoIdioma,
  EmpregabilidadeCurriculoSituacaoInteresses,
  EmpregabilidadeExperienciaProfissionalAccordionRequest,
  EmpregabilidadeFormacaoAccordionRequest,
  GetApiV1EmpregabilidadeCurriculoConquistasId400,
  GetApiV1EmpregabilidadeCurriculoConquistasId404,
  GetApiV1EmpregabilidadeCurriculoConquistasId500,
  GetApiV1EmpregabilidadeCurriculoCpf403,
  GetApiV1EmpregabilidadeCurriculoCpf500,
  GetApiV1EmpregabilidadeCurriculoCpfConquistas200,
  GetApiV1EmpregabilidadeCurriculoCpfConquistas403,
  GetApiV1EmpregabilidadeCurriculoCpfConquistas500,
  GetApiV1EmpregabilidadeCurriculoCpfCursosComplementares200,
  GetApiV1EmpregabilidadeCurriculoCpfCursosComplementares403,
  GetApiV1EmpregabilidadeCurriculoCpfCursosComplementares500,
  GetApiV1EmpregabilidadeCurriculoCpfExperiencias200,
  GetApiV1EmpregabilidadeCurriculoCpfExperiencias403,
  GetApiV1EmpregabilidadeCurriculoCpfExperiencias500,
  GetApiV1EmpregabilidadeCurriculoCpfFormacoes200,
  GetApiV1EmpregabilidadeCurriculoCpfFormacoes403,
  GetApiV1EmpregabilidadeCurriculoCpfFormacoes500,
  GetApiV1EmpregabilidadeCurriculoCpfIdiomas200,
  GetApiV1EmpregabilidadeCurriculoCpfIdiomas403,
  GetApiV1EmpregabilidadeCurriculoCpfIdiomas500,
  GetApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses403,
  GetApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses404,
  GetApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses500,
  GetApiV1EmpregabilidadeCurriculoCursosComplementaresId400,
  GetApiV1EmpregabilidadeCurriculoCursosComplementaresId404,
  GetApiV1EmpregabilidadeCurriculoCursosComplementaresId500,
  GetApiV1EmpregabilidadeCurriculoExperienciasId400,
  GetApiV1EmpregabilidadeCurriculoExperienciasId404,
  GetApiV1EmpregabilidadeCurriculoExperienciasId500,
  GetApiV1EmpregabilidadeCurriculoFormacoesId400,
  GetApiV1EmpregabilidadeCurriculoFormacoesId404,
  GetApiV1EmpregabilidadeCurriculoFormacoesId500,
  GetApiV1EmpregabilidadeCurriculoIdiomasId400,
  GetApiV1EmpregabilidadeCurriculoIdiomasId404,
  GetApiV1EmpregabilidadeCurriculoIdiomasId500,
  PostApiV1EmpregabilidadeCurriculoConquistas400,
  PostApiV1EmpregabilidadeCurriculoConquistas401,
  PostApiV1EmpregabilidadeCurriculoConquistas500,
  PostApiV1EmpregabilidadeCurriculoCursosComplementares400,
  PostApiV1EmpregabilidadeCurriculoCursosComplementares401,
  PostApiV1EmpregabilidadeCurriculoCursosComplementares500,
  PostApiV1EmpregabilidadeCurriculoExperiencias400,
  PostApiV1EmpregabilidadeCurriculoExperiencias401,
  PostApiV1EmpregabilidadeCurriculoExperiencias500,
  PostApiV1EmpregabilidadeCurriculoFormacoes400,
  PostApiV1EmpregabilidadeCurriculoFormacoes401,
  PostApiV1EmpregabilidadeCurriculoFormacoes500,
  PostApiV1EmpregabilidadeCurriculoIdiomas400,
  PostApiV1EmpregabilidadeCurriculoIdiomas401,
  PostApiV1EmpregabilidadeCurriculoIdiomas500,
  PutApiV1EmpregabilidadeCurriculoConquistasId400,
  PutApiV1EmpregabilidadeCurriculoConquistasId403,
  PutApiV1EmpregabilidadeCurriculoConquistasId404,
  PutApiV1EmpregabilidadeCurriculoConquistasId500,
  PutApiV1EmpregabilidadeCurriculoCpfConquistas200,
  PutApiV1EmpregabilidadeCurriculoCpfConquistas400,
  PutApiV1EmpregabilidadeCurriculoCpfConquistas403,
  PutApiV1EmpregabilidadeCurriculoCpfConquistas500,
  PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares200,
  PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares400,
  PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares403,
  PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares500,
  PutApiV1EmpregabilidadeCurriculoCpfExperiencias200,
  PutApiV1EmpregabilidadeCurriculoCpfExperiencias400,
  PutApiV1EmpregabilidadeCurriculoCpfExperiencias403,
  PutApiV1EmpregabilidadeCurriculoCpfExperiencias500,
  PutApiV1EmpregabilidadeCurriculoCpfFormacoes200,
  PutApiV1EmpregabilidadeCurriculoCpfFormacoes400,
  PutApiV1EmpregabilidadeCurriculoCpfFormacoes403,
  PutApiV1EmpregabilidadeCurriculoCpfFormacoes500,
  PutApiV1EmpregabilidadeCurriculoCpfIdiomas200,
  PutApiV1EmpregabilidadeCurriculoCpfIdiomas400,
  PutApiV1EmpregabilidadeCurriculoCpfIdiomas403,
  PutApiV1EmpregabilidadeCurriculoCpfIdiomas500,
  PutApiV1EmpregabilidadeCurriculoCursosComplementaresId400,
  PutApiV1EmpregabilidadeCurriculoCursosComplementaresId403,
  PutApiV1EmpregabilidadeCurriculoCursosComplementaresId404,
  PutApiV1EmpregabilidadeCurriculoCursosComplementaresId500,
  PutApiV1EmpregabilidadeCurriculoExperienciasId400,
  PutApiV1EmpregabilidadeCurriculoExperienciasId403,
  PutApiV1EmpregabilidadeCurriculoExperienciasId404,
  PutApiV1EmpregabilidadeCurriculoExperienciasId500,
  PutApiV1EmpregabilidadeCurriculoFormacoesId400,
  PutApiV1EmpregabilidadeCurriculoFormacoesId403,
  PutApiV1EmpregabilidadeCurriculoFormacoesId404,
  PutApiV1EmpregabilidadeCurriculoFormacoesId500,
  PutApiV1EmpregabilidadeCurriculoIdiomasId400,
  PutApiV1EmpregabilidadeCurriculoIdiomasId403,
  PutApiV1EmpregabilidadeCurriculoIdiomasId404,
  PutApiV1EmpregabilidadeCurriculoIdiomasId500,
  PutApiV1EmpregabilidadeCurriculoSituacaoInteresses400,
  PutApiV1EmpregabilidadeCurriculoSituacaoInteresses401,
  PutApiV1EmpregabilidadeCurriculoSituacaoInteresses500,
} from '../models'

import { customFetch } from '../../../custom-fetch-course'

export type getApiV1EmpregabilidadeCurriculoCpfResponse200 = {
  data: EmpregabilidadeCurriculoCompleto
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfResponse403 = {
  data: GetApiV1EmpregabilidadeCurriculoCpf403
  status: 403
}

export type getApiV1EmpregabilidadeCurriculoCpfResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpf500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfResponseError = (
  | getApiV1EmpregabilidadeCurriculoCpfResponse403
  | getApiV1EmpregabilidadeCurriculoCpfResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoCpfResponse =
  | getApiV1EmpregabilidadeCurriculoCpfResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfUrl = (cpf: string) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}`
}

/**
 * Retorna o currículo completo de um usuário
 * @summary Buscar currículo completo
 */
export const getApiV1EmpregabilidadeCurriculoCpf = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCpfConquistasResponse200 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfConquistas200
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfConquistasResponse403 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfConquistas403
  status: 403
}

export type getApiV1EmpregabilidadeCurriculoCpfConquistasResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfConquistas500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfConquistasResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfConquistasResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfConquistasResponseError = (
  | getApiV1EmpregabilidadeCurriculoCpfConquistasResponse403
  | getApiV1EmpregabilidadeCurriculoCpfConquistasResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoCpfConquistasResponse =
  | getApiV1EmpregabilidadeCurriculoCpfConquistasResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfConquistasResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfConquistasUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/conquistas`
}

/**
 * Retorna todas as conquistas do usuário autenticado
 * @summary Listar conquistas por CPF
 */
export const getApiV1EmpregabilidadeCurriculoCpfConquistas = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfConquistasResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfConquistasResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfConquistasUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponse200 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfConquistas200
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfConquistas400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfConquistas403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfConquistas500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponseSuccess =
  putApiV1EmpregabilidadeCurriculoCpfConquistasResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponseError = (
  | putApiV1EmpregabilidadeCurriculoCpfConquistasResponse400
  | putApiV1EmpregabilidadeCurriculoCpfConquistasResponse403
  | putApiV1EmpregabilidadeCurriculoCpfConquistasResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoCpfConquistasResponse =
  | putApiV1EmpregabilidadeCurriculoCpfConquistasResponseSuccess
  | putApiV1EmpregabilidadeCurriculoCpfConquistasResponseError

export const getPutApiV1EmpregabilidadeCurriculoCpfConquistasUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/conquistas`
}

/**
 * Remove todas as conquistas do CPF e insere as novas em uma transação
 * @summary Substituir conquistas por CPF
 */
export const putApiV1EmpregabilidadeCurriculoCpfConquistas = async (
  cpf: string,
  empregabilidadeCurriculoConquista: EmpregabilidadeCurriculoConquista[],
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoCpfConquistasResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoCpfConquistasResponse>(
    getPutApiV1EmpregabilidadeCurriculoCpfConquistasUrl(cpf),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoConquista),
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse200 =
  {
    data: GetApiV1EmpregabilidadeCurriculoCpfCursosComplementares200
    status: 200
  }

export type getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse403 =
  {
    data: GetApiV1EmpregabilidadeCurriculoCpfCursosComplementares403
    status: 403
  }

export type getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse500 =
  {
    data: GetApiV1EmpregabilidadeCurriculoCpfCursosComplementares500
    status: 500
  }

export type getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseError =
  (
    | getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse403
    | getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse500
  ) & {
    headers: Headers
  }

export type getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse =
  | getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfCursosComplementaresUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/cursos-complementares`
}

/**
 * Retorna todos os cursos complementares do usuário autenticado
 * @summary Listar cursos complementares por CPF
 */
export const getApiV1EmpregabilidadeCurriculoCpfCursosComplementares = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfCursosComplementaresUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse200 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares200
    status: 200
  }

export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse400 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares400
    status: 400
  }

export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse403 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares403
    status: 403
  }

export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse500 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCpfCursosComplementares500
    status: 500
  }

export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseSuccess =
  putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseError =
  (
    | putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse400
    | putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse403
    | putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse500
  ) & {
    headers: Headers
  }

export type putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse =
  | putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseSuccess
  | putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponseError

export const getPutApiV1EmpregabilidadeCurriculoCpfCursosComplementaresUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/cursos-complementares`
}

/**
 * Remove todos os cursos complementares do CPF e insere os novos em uma transação
 * @summary Substituir cursos complementares por CPF
 */
export const putApiV1EmpregabilidadeCurriculoCpfCursosComplementares = async (
  cpf: string,
  empregabilidadeCurriculoCursoComplementar: EmpregabilidadeCurriculoCursoComplementar[],
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoCpfCursosComplementaresResponse>(
    getPutApiV1EmpregabilidadeCurriculoCpfCursosComplementaresUrl(cpf),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoCursoComplementar),
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse200 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfExperiencias200
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse403 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfExperiencias403
  status: 403
}

export type getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfExperiencias500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfExperienciasResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfExperienciasResponseError = (
  | getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse403
  | getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse =
  | getApiV1EmpregabilidadeCurriculoCpfExperienciasResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfExperienciasResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfExperienciasUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/experiencias`
}

/**
 * Retorna todas as experiências profissionais do usuário autenticado
 * @summary Listar experiências por CPF
 */
export const getApiV1EmpregabilidadeCurriculoCpfExperiencias = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfExperienciasResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfExperienciasUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse200 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfExperiencias200
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfExperiencias400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfExperiencias403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfExperiencias500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponseSuccess =
  putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponseError = (
  | putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse400
  | putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse403
  | putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse =
  | putApiV1EmpregabilidadeCurriculoCpfExperienciasResponseSuccess
  | putApiV1EmpregabilidadeCurriculoCpfExperienciasResponseError

export const getPutApiV1EmpregabilidadeCurriculoCpfExperienciasUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/experiencias`
}

/**
 * Remove todas as experiências e conquistas do CPF e insere as novas em uma transação
 * @summary Substituir experiências e conquistas por CPF
 */
export const putApiV1EmpregabilidadeCurriculoCpfExperiencias = async (
  cpf: string,
  empregabilidadeExperienciaProfissionalAccordionRequest: EmpregabilidadeExperienciaProfissionalAccordionRequest,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoCpfExperienciasResponse>(
    getPutApiV1EmpregabilidadeCurriculoCpfExperienciasUrl(cpf),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        empregabilidadeExperienciaProfissionalAccordionRequest
      ),
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse200 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfFormacoes200
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse403 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfFormacoes403
  status: 403
}

export type getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfFormacoes500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfFormacoesResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfFormacoesResponseError = (
  | getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse403
  | getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse =
  | getApiV1EmpregabilidadeCurriculoCpfFormacoesResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfFormacoesResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfFormacoesUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/formacoes`
}

/**
 * Retorna todas as formações do usuário autenticado
 * @summary Listar formações por CPF
 */
export const getApiV1EmpregabilidadeCurriculoCpfFormacoes = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfFormacoesResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfFormacoesUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse200 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfFormacoes200
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfFormacoes400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfFormacoes403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfFormacoes500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponseSuccess =
  putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponseError = (
  | putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse400
  | putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse403
  | putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse =
  | putApiV1EmpregabilidadeCurriculoCpfFormacoesResponseSuccess
  | putApiV1EmpregabilidadeCurriculoCpfFormacoesResponseError

export const getPutApiV1EmpregabilidadeCurriculoCpfFormacoesUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/formacoes`
}

/**
 * Remove todas as formações e idiomas do CPF e insere os novos em uma única transação
 * @summary Substituir formações e idiomas por CPF
 */
export const putApiV1EmpregabilidadeCurriculoCpfFormacoes = async (
  cpf: string,
  empregabilidadeFormacaoAccordionRequest: EmpregabilidadeFormacaoAccordionRequest,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoCpfFormacoesResponse>(
    getPutApiV1EmpregabilidadeCurriculoCpfFormacoesUrl(cpf),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeFormacaoAccordionRequest),
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse200 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfIdiomas200
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse403 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfIdiomas403
  status: 403
}

export type getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfIdiomas500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfIdiomasResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfIdiomasResponseError = (
  | getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse403
  | getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse =
  | getApiV1EmpregabilidadeCurriculoCpfIdiomasResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfIdiomasResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfIdiomasUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/idiomas`
}

/**
 * Retorna todos os idiomas do usuário autenticado
 * @summary Listar idiomas por CPF
 */
export const getApiV1EmpregabilidadeCurriculoCpfIdiomas = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfIdiomasResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfIdiomasUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse200 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfIdiomas200
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfIdiomas400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfIdiomas403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoCpfIdiomas500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponseSuccess =
  putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponseError = (
  | putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse400
  | putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse403
  | putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse =
  | putApiV1EmpregabilidadeCurriculoCpfIdiomasResponseSuccess
  | putApiV1EmpregabilidadeCurriculoCpfIdiomasResponseError

export const getPutApiV1EmpregabilidadeCurriculoCpfIdiomasUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/idiomas`
}

/**
 * Remove todos os idiomas do CPF e insere os novos em uma transação
 * @summary Substituir idiomas por CPF
 */
export const putApiV1EmpregabilidadeCurriculoCpfIdiomas = async (
  cpf: string,
  empregabilidadeCurriculoIdioma: EmpregabilidadeCurriculoIdioma[],
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoCpfIdiomasResponse>(
    getPutApiV1EmpregabilidadeCurriculoCpfIdiomasUrl(cpf),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoIdioma),
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse200 = {
  data: EmpregabilidadeCurriculoSituacaoInteresses
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse403 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses403
  status: 403
}

export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse404 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses404
  status: 404
}

export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponseError =
  (
    | getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse403
    | getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse404
    | getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse500
  ) & {
    headers: Headers
  }

export type getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse =
  | getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponseError

export const getGetApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}/situacao-interesses`
}

/**
 * Retorna a situação atual e interesses do usuário autenticado
 * @summary Buscar situação e interesses por CPF
 */
export const getApiV1EmpregabilidadeCurriculoCpfSituacaoInteresses = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfSituacaoInteressesUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type postApiV1EmpregabilidadeCurriculoConquistasResponse201 = {
  data: EmpregabilidadeCurriculoConquista
  status: 201
}

export type postApiV1EmpregabilidadeCurriculoConquistasResponse400 = {
  data: PostApiV1EmpregabilidadeCurriculoConquistas400
  status: 400
}

export type postApiV1EmpregabilidadeCurriculoConquistasResponse401 = {
  data: PostApiV1EmpregabilidadeCurriculoConquistas401
  status: 401
}

export type postApiV1EmpregabilidadeCurriculoConquistasResponse500 = {
  data: PostApiV1EmpregabilidadeCurriculoConquistas500
  status: 500
}

export type postApiV1EmpregabilidadeCurriculoConquistasResponseSuccess =
  postApiV1EmpregabilidadeCurriculoConquistasResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeCurriculoConquistasResponseError = (
  | postApiV1EmpregabilidadeCurriculoConquistasResponse400
  | postApiV1EmpregabilidadeCurriculoConquistasResponse401
  | postApiV1EmpregabilidadeCurriculoConquistasResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeCurriculoConquistasResponse =
  | postApiV1EmpregabilidadeCurriculoConquistasResponseSuccess
  | postApiV1EmpregabilidadeCurriculoConquistasResponseError

export const getPostApiV1EmpregabilidadeCurriculoConquistasUrl = () => {
  return `/api/v1/empregabilidade/curriculo/conquistas`
}

/**
 * Adiciona uma nova conquista ao currículo do usuário autenticado
 * @summary Criar conquista
 */
export const postApiV1EmpregabilidadeCurriculoConquistas = async (
  empregabilidadeCurriculoConquista: EmpregabilidadeCurriculoConquista,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeCurriculoConquistasResponse> => {
  return customFetch<postApiV1EmpregabilidadeCurriculoConquistasResponse>(
    getPostApiV1EmpregabilidadeCurriculoConquistasUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoConquista),
    }
  )
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeCurriculoConquistasId200
  status: 200
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeCurriculoConquistasId400
  status: 400
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse403 = {
  data: DeleteApiV1EmpregabilidadeCurriculoConquistasId403
  status: 403
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse404 = {
  data: DeleteApiV1EmpregabilidadeCurriculoConquistasId404
  status: 404
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeCurriculoConquistasId500
  status: 500
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponseSuccess =
  deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponseError = (
  | deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse400
  | deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse403
  | deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse404
  | deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse =
  | deleteApiV1EmpregabilidadeCurriculoConquistasIdResponseSuccess
  | deleteApiV1EmpregabilidadeCurriculoConquistasIdResponseError

export const getDeleteApiV1EmpregabilidadeCurriculoConquistasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/conquistas/${id}`
}

/**
 * Remove uma conquista do currículo do usuário autenticado
 * @summary Excluir conquista
 */
export const deleteApiV1EmpregabilidadeCurriculoConquistasId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeCurriculoConquistasIdResponse>(
    getDeleteApiV1EmpregabilidadeCurriculoConquistasIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoConquistasIdResponse200 = {
  data: EmpregabilidadeCurriculoConquista
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoConquistasIdResponse400 = {
  data: GetApiV1EmpregabilidadeCurriculoConquistasId400
  status: 400
}

export type getApiV1EmpregabilidadeCurriculoConquistasIdResponse404 = {
  data: GetApiV1EmpregabilidadeCurriculoConquistasId404
  status: 404
}

export type getApiV1EmpregabilidadeCurriculoConquistasIdResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoConquistasId500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoConquistasIdResponseSuccess =
  getApiV1EmpregabilidadeCurriculoConquistasIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoConquistasIdResponseError = (
  | getApiV1EmpregabilidadeCurriculoConquistasIdResponse400
  | getApiV1EmpregabilidadeCurriculoConquistasIdResponse404
  | getApiV1EmpregabilidadeCurriculoConquistasIdResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoConquistasIdResponse =
  | getApiV1EmpregabilidadeCurriculoConquistasIdResponseSuccess
  | getApiV1EmpregabilidadeCurriculoConquistasIdResponseError

export const getGetApiV1EmpregabilidadeCurriculoConquistasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/conquistas/${id}`
}

/**
 * Retorna uma conquista específica do currículo
 * @summary Buscar conquista por ID
 */
export const getApiV1EmpregabilidadeCurriculoConquistasId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoConquistasIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoConquistasIdResponse>(
    getGetApiV1EmpregabilidadeCurriculoConquistasIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponse200 = {
  data: EmpregabilidadeCurriculoConquista
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoConquistasId400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoConquistasId403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponse404 = {
  data: PutApiV1EmpregabilidadeCurriculoConquistasId404
  status: 404
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoConquistasId500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponseSuccess =
  putApiV1EmpregabilidadeCurriculoConquistasIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoConquistasIdResponseError = (
  | putApiV1EmpregabilidadeCurriculoConquistasIdResponse400
  | putApiV1EmpregabilidadeCurriculoConquistasIdResponse403
  | putApiV1EmpregabilidadeCurriculoConquistasIdResponse404
  | putApiV1EmpregabilidadeCurriculoConquistasIdResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoConquistasIdResponse =
  | putApiV1EmpregabilidadeCurriculoConquistasIdResponseSuccess
  | putApiV1EmpregabilidadeCurriculoConquistasIdResponseError

export const getPutApiV1EmpregabilidadeCurriculoConquistasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/conquistas/${id}`
}

/**
 * Atualiza uma conquista existente do usuário autenticado
 * @summary Atualizar conquista
 */
export const putApiV1EmpregabilidadeCurriculoConquistasId = async (
  id: string,
  empregabilidadeCurriculoConquista: EmpregabilidadeCurriculoConquista,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoConquistasIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoConquistasIdResponse>(
    getPutApiV1EmpregabilidadeCurriculoConquistasIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoConquista),
    }
  )
}

export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse201 = {
  data: EmpregabilidadeCurriculoCursoComplementar
  status: 201
}

export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse400 = {
  data: PostApiV1EmpregabilidadeCurriculoCursosComplementares400
  status: 400
}

export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse401 = {
  data: PostApiV1EmpregabilidadeCurriculoCursosComplementares401
  status: 401
}

export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse500 = {
  data: PostApiV1EmpregabilidadeCurriculoCursosComplementares500
  status: 500
}

export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponseSuccess =
  postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponseError =
  (
    | postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse400
    | postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse401
    | postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse500
  ) & {
    headers: Headers
  }

export type postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse =
  | postApiV1EmpregabilidadeCurriculoCursosComplementaresResponseSuccess
  | postApiV1EmpregabilidadeCurriculoCursosComplementaresResponseError

export const getPostApiV1EmpregabilidadeCurriculoCursosComplementaresUrl =
  () => {
    return `/api/v1/empregabilidade/curriculo/cursos-complementares`
  }

/**
 * Adiciona um novo curso complementar ao currículo do usuário autenticado
 * @summary Criar curso complementar
 */
export const postApiV1EmpregabilidadeCurriculoCursosComplementares = async (
  empregabilidadeCurriculoCursoComplementar: EmpregabilidadeCurriculoCursoComplementar,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse> => {
  return customFetch<postApiV1EmpregabilidadeCurriculoCursosComplementaresResponse>(
    getPostApiV1EmpregabilidadeCurriculoCursosComplementaresUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoCursoComplementar),
    }
  )
}

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse200 =
  {
    data: DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId200
    status: 200
  }

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse400 =
  {
    data: DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId400
    status: 400
  }

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse403 =
  {
    data: DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId403
    status: 403
  }

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse404 =
  {
    data: DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId404
    status: 404
  }

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse500 =
  {
    data: DeleteApiV1EmpregabilidadeCurriculoCursosComplementaresId500
    status: 500
  }

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseSuccess =
  deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseError =
  (
    | deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse400
    | deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse403
    | deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse404
    | deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse500
  ) & {
    headers: Headers
  }

export type deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse =
  | deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseSuccess
  | deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseError

export const getDeleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/cursos-complementares/${id}`
}

/**
 * Remove um curso complementar do currículo do usuário autenticado
 * @summary Excluir curso complementar
 */
export const deleteApiV1EmpregabilidadeCurriculoCursosComplementaresId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse>(
    getDeleteApiV1EmpregabilidadeCurriculoCursosComplementaresIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse200 =
  {
    data: EmpregabilidadeCurriculoCursoComplementar
    status: 200
  }

export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse400 =
  {
    data: GetApiV1EmpregabilidadeCurriculoCursosComplementaresId400
    status: 400
  }

export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse404 =
  {
    data: GetApiV1EmpregabilidadeCurriculoCursosComplementaresId404
    status: 404
  }

export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse500 =
  {
    data: GetApiV1EmpregabilidadeCurriculoCursosComplementaresId500
    status: 500
  }

export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseSuccess =
  getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseError =
  (
    | getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse400
    | getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse404
    | getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse500
  ) & {
    headers: Headers
  }

export type getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse =
  | getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseSuccess
  | getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseError

export const getGetApiV1EmpregabilidadeCurriculoCursosComplementaresIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/cursos-complementares/${id}`
}

/**
 * Retorna um curso complementar específico do currículo
 * @summary Buscar curso complementar por ID
 */
export const getApiV1EmpregabilidadeCurriculoCursosComplementaresId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse>(
    getGetApiV1EmpregabilidadeCurriculoCursosComplementaresIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse200 =
  {
    data: EmpregabilidadeCurriculoCursoComplementar
    status: 200
  }

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse400 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCursosComplementaresId400
    status: 400
  }

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse403 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCursosComplementaresId403
    status: 403
  }

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse404 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCursosComplementaresId404
    status: 404
  }

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse500 =
  {
    data: PutApiV1EmpregabilidadeCurriculoCursosComplementaresId500
    status: 500
  }

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseSuccess =
  putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseError =
  (
    | putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse400
    | putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse403
    | putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse404
    | putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse500
  ) & {
    headers: Headers
  }

export type putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse =
  | putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseSuccess
  | putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponseError

export const getPutApiV1EmpregabilidadeCurriculoCursosComplementaresIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/cursos-complementares/${id}`
}

/**
 * Atualiza um curso complementar existente do usuário autenticado
 * @summary Atualizar curso complementar
 */
export const putApiV1EmpregabilidadeCurriculoCursosComplementaresId = async (
  id: string,
  empregabilidadeCurriculoCursoComplementar: EmpregabilidadeCurriculoCursoComplementar,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoCursosComplementaresIdResponse>(
    getPutApiV1EmpregabilidadeCurriculoCursosComplementaresIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoCursoComplementar),
    }
  )
}

export type postApiV1EmpregabilidadeCurriculoExperienciasResponse201 = {
  data: EmpregabilidadeCurriculoExperiencia
  status: 201
}

export type postApiV1EmpregabilidadeCurriculoExperienciasResponse400 = {
  data: PostApiV1EmpregabilidadeCurriculoExperiencias400
  status: 400
}

export type postApiV1EmpregabilidadeCurriculoExperienciasResponse401 = {
  data: PostApiV1EmpregabilidadeCurriculoExperiencias401
  status: 401
}

export type postApiV1EmpregabilidadeCurriculoExperienciasResponse500 = {
  data: PostApiV1EmpregabilidadeCurriculoExperiencias500
  status: 500
}

export type postApiV1EmpregabilidadeCurriculoExperienciasResponseSuccess =
  postApiV1EmpregabilidadeCurriculoExperienciasResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeCurriculoExperienciasResponseError = (
  | postApiV1EmpregabilidadeCurriculoExperienciasResponse400
  | postApiV1EmpregabilidadeCurriculoExperienciasResponse401
  | postApiV1EmpregabilidadeCurriculoExperienciasResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeCurriculoExperienciasResponse =
  | postApiV1EmpregabilidadeCurriculoExperienciasResponseSuccess
  | postApiV1EmpregabilidadeCurriculoExperienciasResponseError

export const getPostApiV1EmpregabilidadeCurriculoExperienciasUrl = () => {
  return `/api/v1/empregabilidade/curriculo/experiencias`
}

/**
 * Adiciona uma nova experiência profissional ao currículo do usuário autenticado
 * @summary Criar experiência
 */
export const postApiV1EmpregabilidadeCurriculoExperiencias = async (
  empregabilidadeCurriculoExperiencia: EmpregabilidadeCurriculoExperiencia,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeCurriculoExperienciasResponse> => {
  return customFetch<postApiV1EmpregabilidadeCurriculoExperienciasResponse>(
    getPostApiV1EmpregabilidadeCurriculoExperienciasUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoExperiencia),
    }
  )
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeCurriculoExperienciasId200
  status: 200
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeCurriculoExperienciasId400
  status: 400
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse403 = {
  data: DeleteApiV1EmpregabilidadeCurriculoExperienciasId403
  status: 403
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse404 = {
  data: DeleteApiV1EmpregabilidadeCurriculoExperienciasId404
  status: 404
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeCurriculoExperienciasId500
  status: 500
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponseSuccess =
  deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponseError = (
  | deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse400
  | deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse403
  | deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse404
  | deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse =
  | deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponseSuccess
  | deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponseError

export const getDeleteApiV1EmpregabilidadeCurriculoExperienciasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/experiencias/${id}`
}

/**
 * Remove uma experiência do currículo do usuário autenticado
 * @summary Excluir experiência
 */
export const deleteApiV1EmpregabilidadeCurriculoExperienciasId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeCurriculoExperienciasIdResponse>(
    getDeleteApiV1EmpregabilidadeCurriculoExperienciasIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponse200 = {
  data: EmpregabilidadeCurriculoExperiencia
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponse400 = {
  data: GetApiV1EmpregabilidadeCurriculoExperienciasId400
  status: 400
}

export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponse404 = {
  data: GetApiV1EmpregabilidadeCurriculoExperienciasId404
  status: 404
}

export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoExperienciasId500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponseSuccess =
  getApiV1EmpregabilidadeCurriculoExperienciasIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponseError = (
  | getApiV1EmpregabilidadeCurriculoExperienciasIdResponse400
  | getApiV1EmpregabilidadeCurriculoExperienciasIdResponse404
  | getApiV1EmpregabilidadeCurriculoExperienciasIdResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoExperienciasIdResponse =
  | getApiV1EmpregabilidadeCurriculoExperienciasIdResponseSuccess
  | getApiV1EmpregabilidadeCurriculoExperienciasIdResponseError

export const getGetApiV1EmpregabilidadeCurriculoExperienciasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/experiencias/${id}`
}

/**
 * Retorna uma experiência específica do currículo
 * @summary Buscar experiência por ID
 */
export const getApiV1EmpregabilidadeCurriculoExperienciasId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoExperienciasIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoExperienciasIdResponse>(
    getGetApiV1EmpregabilidadeCurriculoExperienciasIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponse200 = {
  data: EmpregabilidadeCurriculoExperiencia
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoExperienciasId400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoExperienciasId403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponse404 = {
  data: PutApiV1EmpregabilidadeCurriculoExperienciasId404
  status: 404
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoExperienciasId500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponseSuccess =
  putApiV1EmpregabilidadeCurriculoExperienciasIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponseError = (
  | putApiV1EmpregabilidadeCurriculoExperienciasIdResponse400
  | putApiV1EmpregabilidadeCurriculoExperienciasIdResponse403
  | putApiV1EmpregabilidadeCurriculoExperienciasIdResponse404
  | putApiV1EmpregabilidadeCurriculoExperienciasIdResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoExperienciasIdResponse =
  | putApiV1EmpregabilidadeCurriculoExperienciasIdResponseSuccess
  | putApiV1EmpregabilidadeCurriculoExperienciasIdResponseError

export const getPutApiV1EmpregabilidadeCurriculoExperienciasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/experiencias/${id}`
}

/**
 * Atualiza uma experiência existente do usuário autenticado
 * @summary Atualizar experiência
 */
export const putApiV1EmpregabilidadeCurriculoExperienciasId = async (
  id: string,
  empregabilidadeCurriculoExperiencia: EmpregabilidadeCurriculoExperiencia,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoExperienciasIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoExperienciasIdResponse>(
    getPutApiV1EmpregabilidadeCurriculoExperienciasIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoExperiencia),
    }
  )
}

export type postApiV1EmpregabilidadeCurriculoFormacoesResponse201 = {
  data: EmpregabilidadeCurriculoFormacao
  status: 201
}

export type postApiV1EmpregabilidadeCurriculoFormacoesResponse400 = {
  data: PostApiV1EmpregabilidadeCurriculoFormacoes400
  status: 400
}

export type postApiV1EmpregabilidadeCurriculoFormacoesResponse401 = {
  data: PostApiV1EmpregabilidadeCurriculoFormacoes401
  status: 401
}

export type postApiV1EmpregabilidadeCurriculoFormacoesResponse500 = {
  data: PostApiV1EmpregabilidadeCurriculoFormacoes500
  status: 500
}

export type postApiV1EmpregabilidadeCurriculoFormacoesResponseSuccess =
  postApiV1EmpregabilidadeCurriculoFormacoesResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeCurriculoFormacoesResponseError = (
  | postApiV1EmpregabilidadeCurriculoFormacoesResponse400
  | postApiV1EmpregabilidadeCurriculoFormacoesResponse401
  | postApiV1EmpregabilidadeCurriculoFormacoesResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeCurriculoFormacoesResponse =
  | postApiV1EmpregabilidadeCurriculoFormacoesResponseSuccess
  | postApiV1EmpregabilidadeCurriculoFormacoesResponseError

export const getPostApiV1EmpregabilidadeCurriculoFormacoesUrl = () => {
  return `/api/v1/empregabilidade/curriculo/formacoes`
}

/**
 * Cria uma nova formação no currículo do usuário autenticado
 * @summary Criar formação
 */
export const postApiV1EmpregabilidadeCurriculoFormacoes = async (
  empregabilidadeCurriculoFormacao: EmpregabilidadeCurriculoFormacao,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeCurriculoFormacoesResponse> => {
  return customFetch<postApiV1EmpregabilidadeCurriculoFormacoesResponse>(
    getPostApiV1EmpregabilidadeCurriculoFormacoesUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoFormacao),
    }
  )
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeCurriculoFormacoesId200
  status: 200
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeCurriculoFormacoesId400
  status: 400
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse403 = {
  data: DeleteApiV1EmpregabilidadeCurriculoFormacoesId403
  status: 403
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse404 = {
  data: DeleteApiV1EmpregabilidadeCurriculoFormacoesId404
  status: 404
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeCurriculoFormacoesId500
  status: 500
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponseSuccess =
  deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponseError = (
  | deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse400
  | deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse403
  | deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse404
  | deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse =
  | deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponseSuccess
  | deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponseError

export const getDeleteApiV1EmpregabilidadeCurriculoFormacoesIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/formacoes/${id}`
}

/**
 * Remove uma formação do currículo do usuário autenticado
 * @summary Excluir formação
 */
export const deleteApiV1EmpregabilidadeCurriculoFormacoesId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeCurriculoFormacoesIdResponse>(
    getDeleteApiV1EmpregabilidadeCurriculoFormacoesIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponse200 = {
  data: EmpregabilidadeCurriculoFormacao
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponse400 = {
  data: GetApiV1EmpregabilidadeCurriculoFormacoesId400
  status: 400
}

export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponse404 = {
  data: GetApiV1EmpregabilidadeCurriculoFormacoesId404
  status: 404
}

export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoFormacoesId500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponseSuccess =
  getApiV1EmpregabilidadeCurriculoFormacoesIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponseError = (
  | getApiV1EmpregabilidadeCurriculoFormacoesIdResponse400
  | getApiV1EmpregabilidadeCurriculoFormacoesIdResponse404
  | getApiV1EmpregabilidadeCurriculoFormacoesIdResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoFormacoesIdResponse =
  | getApiV1EmpregabilidadeCurriculoFormacoesIdResponseSuccess
  | getApiV1EmpregabilidadeCurriculoFormacoesIdResponseError

export const getGetApiV1EmpregabilidadeCurriculoFormacoesIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/formacoes/${id}`
}

/**
 * Retorna uma formação específica
 * @summary Buscar formação por ID
 */
export const getApiV1EmpregabilidadeCurriculoFormacoesId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoFormacoesIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoFormacoesIdResponse>(
    getGetApiV1EmpregabilidadeCurriculoFormacoesIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponse200 = {
  data: EmpregabilidadeCurriculoFormacao
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoFormacoesId400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoFormacoesId403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponse404 = {
  data: PutApiV1EmpregabilidadeCurriculoFormacoesId404
  status: 404
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoFormacoesId500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponseSuccess =
  putApiV1EmpregabilidadeCurriculoFormacoesIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponseError = (
  | putApiV1EmpregabilidadeCurriculoFormacoesIdResponse400
  | putApiV1EmpregabilidadeCurriculoFormacoesIdResponse403
  | putApiV1EmpregabilidadeCurriculoFormacoesIdResponse404
  | putApiV1EmpregabilidadeCurriculoFormacoesIdResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoFormacoesIdResponse =
  | putApiV1EmpregabilidadeCurriculoFormacoesIdResponseSuccess
  | putApiV1EmpregabilidadeCurriculoFormacoesIdResponseError

export const getPutApiV1EmpregabilidadeCurriculoFormacoesIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/formacoes/${id}`
}

/**
 * Atualiza uma formação existente do usuário autenticado
 * @summary Atualizar formação
 */
export const putApiV1EmpregabilidadeCurriculoFormacoesId = async (
  id: string,
  empregabilidadeCurriculoFormacao: EmpregabilidadeCurriculoFormacao,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoFormacoesIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoFormacoesIdResponse>(
    getPutApiV1EmpregabilidadeCurriculoFormacoesIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoFormacao),
    }
  )
}

export type postApiV1EmpregabilidadeCurriculoIdiomasResponse201 = {
  data: EmpregabilidadeCurriculoIdioma
  status: 201
}

export type postApiV1EmpregabilidadeCurriculoIdiomasResponse400 = {
  data: PostApiV1EmpregabilidadeCurriculoIdiomas400
  status: 400
}

export type postApiV1EmpregabilidadeCurriculoIdiomasResponse401 = {
  data: PostApiV1EmpregabilidadeCurriculoIdiomas401
  status: 401
}

export type postApiV1EmpregabilidadeCurriculoIdiomasResponse500 = {
  data: PostApiV1EmpregabilidadeCurriculoIdiomas500
  status: 500
}

export type postApiV1EmpregabilidadeCurriculoIdiomasResponseSuccess =
  postApiV1EmpregabilidadeCurriculoIdiomasResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeCurriculoIdiomasResponseError = (
  | postApiV1EmpregabilidadeCurriculoIdiomasResponse400
  | postApiV1EmpregabilidadeCurriculoIdiomasResponse401
  | postApiV1EmpregabilidadeCurriculoIdiomasResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeCurriculoIdiomasResponse =
  | postApiV1EmpregabilidadeCurriculoIdiomasResponseSuccess
  | postApiV1EmpregabilidadeCurriculoIdiomasResponseError

export const getPostApiV1EmpregabilidadeCurriculoIdiomasUrl = () => {
  return `/api/v1/empregabilidade/curriculo/idiomas`
}

/**
 * Adiciona um novo idioma ao currículo do usuário autenticado
 * @summary Criar idioma no currículo
 */
export const postApiV1EmpregabilidadeCurriculoIdiomas = async (
  empregabilidadeCurriculoIdioma: EmpregabilidadeCurriculoIdioma,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeCurriculoIdiomasResponse> => {
  return customFetch<postApiV1EmpregabilidadeCurriculoIdiomasResponse>(
    getPostApiV1EmpregabilidadeCurriculoIdiomasUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoIdioma),
    }
  )
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeCurriculoIdiomasId200
  status: 200
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeCurriculoIdiomasId400
  status: 400
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse403 = {
  data: DeleteApiV1EmpregabilidadeCurriculoIdiomasId403
  status: 403
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse404 = {
  data: DeleteApiV1EmpregabilidadeCurriculoIdiomasId404
  status: 404
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeCurriculoIdiomasId500
  status: 500
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponseSuccess =
  deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponseError = (
  | deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse400
  | deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse403
  | deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse404
  | deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse =
  | deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponseSuccess
  | deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponseError

export const getDeleteApiV1EmpregabilidadeCurriculoIdiomasIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/curriculo/idiomas/${id}`
}

/**
 * Remove um idioma do currículo do usuário autenticado
 * @summary Excluir idioma do currículo
 */
export const deleteApiV1EmpregabilidadeCurriculoIdiomasId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeCurriculoIdiomasIdResponse>(
    getDeleteApiV1EmpregabilidadeCurriculoIdiomasIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponse200 = {
  data: EmpregabilidadeCurriculoIdioma
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponse400 = {
  data: GetApiV1EmpregabilidadeCurriculoIdiomasId400
  status: 400
}

export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponse404 = {
  data: GetApiV1EmpregabilidadeCurriculoIdiomasId404
  status: 404
}

export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoIdiomasId500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponseSuccess =
  getApiV1EmpregabilidadeCurriculoIdiomasIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponseError = (
  | getApiV1EmpregabilidadeCurriculoIdiomasIdResponse400
  | getApiV1EmpregabilidadeCurriculoIdiomasIdResponse404
  | getApiV1EmpregabilidadeCurriculoIdiomasIdResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCurriculoIdiomasIdResponse =
  | getApiV1EmpregabilidadeCurriculoIdiomasIdResponseSuccess
  | getApiV1EmpregabilidadeCurriculoIdiomasIdResponseError

export const getGetApiV1EmpregabilidadeCurriculoIdiomasIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/curriculo/idiomas/${id}`
}

/**
 * Retorna um idioma específico do currículo
 * @summary Buscar idioma por ID
 */
export const getApiV1EmpregabilidadeCurriculoIdiomasId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoIdiomasIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeCurriculoIdiomasIdResponse>(
    getGetApiV1EmpregabilidadeCurriculoIdiomasIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponse200 = {
  data: EmpregabilidadeCurriculoIdioma
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoIdiomasId400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponse403 = {
  data: PutApiV1EmpregabilidadeCurriculoIdiomasId403
  status: 403
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponse404 = {
  data: PutApiV1EmpregabilidadeCurriculoIdiomasId404
  status: 404
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoIdiomasId500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponseSuccess =
  putApiV1EmpregabilidadeCurriculoIdiomasIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponseError = (
  | putApiV1EmpregabilidadeCurriculoIdiomasIdResponse400
  | putApiV1EmpregabilidadeCurriculoIdiomasIdResponse403
  | putApiV1EmpregabilidadeCurriculoIdiomasIdResponse404
  | putApiV1EmpregabilidadeCurriculoIdiomasIdResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoIdiomasIdResponse =
  | putApiV1EmpregabilidadeCurriculoIdiomasIdResponseSuccess
  | putApiV1EmpregabilidadeCurriculoIdiomasIdResponseError

export const getPutApiV1EmpregabilidadeCurriculoIdiomasIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/curriculo/idiomas/${id}`
}

/**
 * Atualiza um idioma existente do usuário autenticado
 * @summary Atualizar idioma no currículo
 */
export const putApiV1EmpregabilidadeCurriculoIdiomasId = async (
  id: string,
  empregabilidadeCurriculoIdioma: EmpregabilidadeCurriculoIdioma,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoIdiomasIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoIdiomasIdResponse>(
    getPutApiV1EmpregabilidadeCurriculoIdiomasIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoIdioma),
    }
  )
}

export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse200 = {
  data: EmpregabilidadeCurriculoSituacaoInteresses
  status: 200
}

export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse400 = {
  data: PutApiV1EmpregabilidadeCurriculoSituacaoInteresses400
  status: 400
}

export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse401 = {
  data: PutApiV1EmpregabilidadeCurriculoSituacaoInteresses401
  status: 401
}

export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse500 = {
  data: PutApiV1EmpregabilidadeCurriculoSituacaoInteresses500
  status: 500
}

export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponseSuccess =
  putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponseError = (
  | putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse400
  | putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse401
  | putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse =
  | putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponseSuccess
  | putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponseError

export const getPutApiV1EmpregabilidadeCurriculoSituacaoInteressesUrl = () => {
  return `/api/v1/empregabilidade/curriculo/situacao-interesses`
}

/**
 * Cria ou atualiza a situação atual e interesses do usuário autenticado
 * @summary Criar ou atualizar situação e interesses
 */
export const putApiV1EmpregabilidadeCurriculoSituacaoInteresses = async (
  empregabilidadeCurriculoSituacaoInteresses: EmpregabilidadeCurriculoSituacaoInteresses,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse> => {
  return customFetch<putApiV1EmpregabilidadeCurriculoSituacaoInteressesResponse>(
    getPutApiV1EmpregabilidadeCurriculoSituacaoInteressesUrl(),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCurriculoSituacaoInteresses),
    }
  )
}
