/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { HandlersErrorResponse } from '../models'

import { customFetch } from '../../../custom-fetch'

export type getMetricsResponse200 = {
  data: string
  status: 200
}

export type getMetricsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getMetricsResponseSuccess = getMetricsResponse200 & {
  headers: Headers
}
export type getMetricsResponseError = getMetricsResponse500 & {
  headers: Headers
}

export type getMetricsResponse =
  | getMetricsResponseSuccess
  | getMetricsResponseError

export const getGetMetricsUrl = () => {
  return `/metrics`
}

/**
 * Expõe métricas Prometheus para monitoramento do sistema
 * @summary Métricas Prometheus
 */
export const getMetrics = async (
  options?: RequestInit
): Promise<getMetricsResponse> => {
  return customFetch<getMetricsResponse>(getGetMetricsUrl(), {
    ...options,
    method: 'GET',
  })
}
