/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type {
  HandlersErrorResponse
} from '.././models';

import { customFetch } from '../../../custom-fetch';

/**
 * Expõe métricas Prometheus para monitoramento do sistema
 * @summary Métricas Prometheus
 */
export type getMetricsResponse200 = {
  data: string
  status: 200
}

export type getMetricsResponse500 = {
  data: HandlersErrorResponse
  status: 500
}
    
export type getMetricsResponseComposite = getMetricsResponse200 | getMetricsResponse500;
    
export type getMetricsResponse = getMetricsResponseComposite & {
  headers: Headers;
}

export const getGetMetricsUrl = () => {


  

  return `/metrics`
}

export const getMetrics = async ( options?: RequestInit): Promise<getMetricsResponse> => {
  
  return customFetch<getMetricsResponse>(getGetMetricsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


