/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  EmpregabilidadeAreaAtuacaoHabilidade,
  ResponseErrorResponse,
} from '../models'

import { customFetch } from '../../../custom-fetch-course'

export type getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse200 =
  {
    data: EmpregabilidadeAreaAtuacaoHabilidade[]
    status: 200
  }

export type getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse500 =
  {
    data: ResponseErrorResponse
    status: 500
  }

export type getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponseSuccess =
  getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponseError =
  getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse500 & {
    headers: Headers
  }

export type getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse =
  | getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponseSuccess
  | getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponseError

export const getGetApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesUrl =
  () => {
    return `/api/v1/empregabilidade/habilidades/areas-atuacao-habilidades`
  }

/**
 * Retorna todos os vínculos cadastrados entre áreas de atuação e habilidades
 * @summary Listar vínculos entre Áreas de Atuação e Habilidades
 */
export const getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidades = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse> => {
  return customFetch<getApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesResponse>(
    getGetApiV1EmpregabilidadeHabilidadesAreasAtuacaoHabilidadesUrl(),
    {
      ...options,
      method: 'GET',
    }
  )
}
