/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Chamados Público - Pref.Rio (Experience API)
 * API de integração para consulta pública e básica de chamados via protocolo, sem autenticação de cidadão logado. Utiliza Integration User (Client Credentials) para comunicação com o Salesforce.
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from './errorResponse'

/**
 * Credenciais ausentes ou inválidas (Integration User).
 */
export type UnauthorizedErrorResponse = ErrorResponse
