/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeDisponibilidadesId200,
  DeleteApiV1EmpregabilidadeDisponibilidadesId400,
  DeleteApiV1EmpregabilidadeDisponibilidadesId500,
  EmpregabilidadeDisponibilidade,
  GetApiV1EmpregabilidadeDisponibilidades200,
  GetApiV1EmpregabilidadeDisponibilidades500,
  GetApiV1EmpregabilidadeDisponibilidadesId400,
  GetApiV1EmpregabilidadeDisponibilidadesId404,
  GetApiV1EmpregabilidadeDisponibilidadesParams,
  PostApiV1EmpregabilidadeDisponibilidades400,
  PostApiV1EmpregabilidadeDisponibilidades500,
  PutApiV1EmpregabilidadeDisponibilidadesId400,
  PutApiV1EmpregabilidadeDisponibilidadesId500,
} from '../models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna uma lista paginada de disponibilidades
 * @summary Listar disponibilidades
 */
export type getApiV1EmpregabilidadeDisponibilidadesResponse200 = {
  data: GetApiV1EmpregabilidadeDisponibilidades200
  status: 200
}

export type getApiV1EmpregabilidadeDisponibilidadesResponse500 = {
  data: GetApiV1EmpregabilidadeDisponibilidades500
  status: 500
}

export type getApiV1EmpregabilidadeDisponibilidadesResponseSuccess =
  getApiV1EmpregabilidadeDisponibilidadesResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeDisponibilidadesResponseError =
  getApiV1EmpregabilidadeDisponibilidadesResponse500 & {
    headers: Headers
  }

export type getApiV1EmpregabilidadeDisponibilidadesResponse =
  | getApiV1EmpregabilidadeDisponibilidadesResponseSuccess
  | getApiV1EmpregabilidadeDisponibilidadesResponseError

export const getGetApiV1EmpregabilidadeDisponibilidadesUrl = (
  params?: GetApiV1EmpregabilidadeDisponibilidadesParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/disponibilidades?${stringifiedParams}`
    : `/api/v1/empregabilidade/disponibilidades`
}

export const getApiV1EmpregabilidadeDisponibilidades = async (
  params?: GetApiV1EmpregabilidadeDisponibilidadesParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeDisponibilidadesResponse> => {
  return customFetch<getApiV1EmpregabilidadeDisponibilidadesResponse>(
    getGetApiV1EmpregabilidadeDisponibilidadesUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma nova disponibilidade
 * @summary Criar disponibilidade
 */
export type postApiV1EmpregabilidadeDisponibilidadesResponse201 = {
  data: EmpregabilidadeDisponibilidade
  status: 201
}

export type postApiV1EmpregabilidadeDisponibilidadesResponse400 = {
  data: PostApiV1EmpregabilidadeDisponibilidades400
  status: 400
}

export type postApiV1EmpregabilidadeDisponibilidadesResponse500 = {
  data: PostApiV1EmpregabilidadeDisponibilidades500
  status: 500
}

export type postApiV1EmpregabilidadeDisponibilidadesResponseSuccess =
  postApiV1EmpregabilidadeDisponibilidadesResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeDisponibilidadesResponseError = (
  | postApiV1EmpregabilidadeDisponibilidadesResponse400
  | postApiV1EmpregabilidadeDisponibilidadesResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeDisponibilidadesResponse =
  | postApiV1EmpregabilidadeDisponibilidadesResponseSuccess
  | postApiV1EmpregabilidadeDisponibilidadesResponseError

export const getPostApiV1EmpregabilidadeDisponibilidadesUrl = () => {
  return `/api/v1/empregabilidade/disponibilidades`
}

export const postApiV1EmpregabilidadeDisponibilidades = async (
  empregabilidadeDisponibilidade: EmpregabilidadeDisponibilidade,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeDisponibilidadesResponse> => {
  return customFetch<postApiV1EmpregabilidadeDisponibilidadesResponse>(
    getPostApiV1EmpregabilidadeDisponibilidadesUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeDisponibilidade),
    }
  )
}

/**
 * Remove uma disponibilidade
 * @summary Excluir disponibilidade
 */
export type deleteApiV1EmpregabilidadeDisponibilidadesIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeDisponibilidadesId200
  status: 200
}

export type deleteApiV1EmpregabilidadeDisponibilidadesIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeDisponibilidadesId400
  status: 400
}

export type deleteApiV1EmpregabilidadeDisponibilidadesIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeDisponibilidadesId500
  status: 500
}

export type deleteApiV1EmpregabilidadeDisponibilidadesIdResponseSuccess =
  deleteApiV1EmpregabilidadeDisponibilidadesIdResponse200 & {
    headers: Headers
  }
export type deleteApiV1EmpregabilidadeDisponibilidadesIdResponseError = (
  | deleteApiV1EmpregabilidadeDisponibilidadesIdResponse400
  | deleteApiV1EmpregabilidadeDisponibilidadesIdResponse500
) & {
  headers: Headers
}

export type deleteApiV1EmpregabilidadeDisponibilidadesIdResponse =
  | deleteApiV1EmpregabilidadeDisponibilidadesIdResponseSuccess
  | deleteApiV1EmpregabilidadeDisponibilidadesIdResponseError

export const getDeleteApiV1EmpregabilidadeDisponibilidadesIdUrl = (
  id: string
) => {
  return `/api/v1/empregabilidade/disponibilidades/${id}`
}

export const deleteApiV1EmpregabilidadeDisponibilidadesId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeDisponibilidadesIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeDisponibilidadesIdResponse>(
    getDeleteApiV1EmpregabilidadeDisponibilidadesIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}

/**
 * Retorna uma disponibilidade específica
 * @summary Buscar disponibilidade por ID
 */
export type getApiV1EmpregabilidadeDisponibilidadesIdResponse200 = {
  data: EmpregabilidadeDisponibilidade
  status: 200
}

export type getApiV1EmpregabilidadeDisponibilidadesIdResponse400 = {
  data: GetApiV1EmpregabilidadeDisponibilidadesId400
  status: 400
}

export type getApiV1EmpregabilidadeDisponibilidadesIdResponse404 = {
  data: GetApiV1EmpregabilidadeDisponibilidadesId404
  status: 404
}

export type getApiV1EmpregabilidadeDisponibilidadesIdResponseSuccess =
  getApiV1EmpregabilidadeDisponibilidadesIdResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeDisponibilidadesIdResponseError = (
  | getApiV1EmpregabilidadeDisponibilidadesIdResponse400
  | getApiV1EmpregabilidadeDisponibilidadesIdResponse404
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeDisponibilidadesIdResponse =
  | getApiV1EmpregabilidadeDisponibilidadesIdResponseSuccess
  | getApiV1EmpregabilidadeDisponibilidadesIdResponseError

export const getGetApiV1EmpregabilidadeDisponibilidadesIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/disponibilidades/${id}`
}

export const getApiV1EmpregabilidadeDisponibilidadesId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeDisponibilidadesIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeDisponibilidadesIdResponse>(
    getGetApiV1EmpregabilidadeDisponibilidadesIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma disponibilidade existente
 * @summary Atualizar disponibilidade
 */
export type putApiV1EmpregabilidadeDisponibilidadesIdResponse200 = {
  data: EmpregabilidadeDisponibilidade
  status: 200
}

export type putApiV1EmpregabilidadeDisponibilidadesIdResponse400 = {
  data: PutApiV1EmpregabilidadeDisponibilidadesId400
  status: 400
}

export type putApiV1EmpregabilidadeDisponibilidadesIdResponse500 = {
  data: PutApiV1EmpregabilidadeDisponibilidadesId500
  status: 500
}

export type putApiV1EmpregabilidadeDisponibilidadesIdResponseSuccess =
  putApiV1EmpregabilidadeDisponibilidadesIdResponse200 & {
    headers: Headers
  }
export type putApiV1EmpregabilidadeDisponibilidadesIdResponseError = (
  | putApiV1EmpregabilidadeDisponibilidadesIdResponse400
  | putApiV1EmpregabilidadeDisponibilidadesIdResponse500
) & {
  headers: Headers
}

export type putApiV1EmpregabilidadeDisponibilidadesIdResponse =
  | putApiV1EmpregabilidadeDisponibilidadesIdResponseSuccess
  | putApiV1EmpregabilidadeDisponibilidadesIdResponseError

export const getPutApiV1EmpregabilidadeDisponibilidadesIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/disponibilidades/${id}`
}

export const putApiV1EmpregabilidadeDisponibilidadesId = async (
  id: string,
  empregabilidadeDisponibilidade: EmpregabilidadeDisponibilidade,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeDisponibilidadesIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeDisponibilidadesIdResponse>(
    getPutApiV1EmpregabilidadeDisponibilidadesIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeDisponibilidade),
    }
  )
}
