/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeEscolaridadesId200,
  DeleteApiV1EmpregabilidadeEscolaridadesId400,
  DeleteApiV1EmpregabilidadeEscolaridadesId500,
  EmpregabilidadeEscolaridade,
  EmpregabilidadeEscolaridadeBody,
  GetApiV1EmpregabilidadeEscolaridades200,
  GetApiV1EmpregabilidadeEscolaridades500,
  GetApiV1EmpregabilidadeEscolaridadesId400,
  GetApiV1EmpregabilidadeEscolaridadesId404,
  GetApiV1EmpregabilidadeEscolaridadesParams,
  PostApiV1EmpregabilidadeEscolaridades400,
  PostApiV1EmpregabilidadeEscolaridades500,
  PutApiV1EmpregabilidadeEscolaridadesId400,
  PutApiV1EmpregabilidadeEscolaridadesId500,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna uma lista paginada de escolaridades
 * @summary Listar escolaridades
 */
export type getApiV1EmpregabilidadeEscolaridadesResponse200 = {
  data: GetApiV1EmpregabilidadeEscolaridades200
  status: 200
}

export type getApiV1EmpregabilidadeEscolaridadesResponse500 = {
  data: GetApiV1EmpregabilidadeEscolaridades500
  status: 500
}

export type getApiV1EmpregabilidadeEscolaridadesResponseComposite =
  | getApiV1EmpregabilidadeEscolaridadesResponse200
  | getApiV1EmpregabilidadeEscolaridadesResponse500

export type getApiV1EmpregabilidadeEscolaridadesResponse =
  getApiV1EmpregabilidadeEscolaridadesResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeEscolaridadesUrl = (
  params?: GetApiV1EmpregabilidadeEscolaridadesParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/escolaridades?${stringifiedParams}`
    : `/api/v1/empregabilidade/escolaridades`
}

export const getApiV1EmpregabilidadeEscolaridades = async (
  params?: GetApiV1EmpregabilidadeEscolaridadesParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeEscolaridadesResponse> => {
  return customFetch<getApiV1EmpregabilidadeEscolaridadesResponse>(
    getGetApiV1EmpregabilidadeEscolaridadesUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma nova escolaridade
 * @summary Criar escolaridade
 */
export type postApiV1EmpregabilidadeEscolaridadesResponse201 = {
  data: EmpregabilidadeEscolaridade
  status: 201
}

export type postApiV1EmpregabilidadeEscolaridadesResponse400 = {
  data: PostApiV1EmpregabilidadeEscolaridades400
  status: 400
}

export type postApiV1EmpregabilidadeEscolaridadesResponse500 = {
  data: PostApiV1EmpregabilidadeEscolaridades500
  status: 500
}

export type postApiV1EmpregabilidadeEscolaridadesResponseComposite =
  | postApiV1EmpregabilidadeEscolaridadesResponse201
  | postApiV1EmpregabilidadeEscolaridadesResponse400
  | postApiV1EmpregabilidadeEscolaridadesResponse500

export type postApiV1EmpregabilidadeEscolaridadesResponse =
  postApiV1EmpregabilidadeEscolaridadesResponseComposite & {
    headers: Headers
  }

export const getPostApiV1EmpregabilidadeEscolaridadesUrl = () => {
  return `/api/v1/empregabilidade/escolaridades`
}

export const postApiV1EmpregabilidadeEscolaridades = async (
  empregabilidadeEscolaridadeBody: EmpregabilidadeEscolaridadeBody,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeEscolaridadesResponse> => {
  return customFetch<postApiV1EmpregabilidadeEscolaridadesResponse>(
    getPostApiV1EmpregabilidadeEscolaridadesUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEscolaridadeBody),
    }
  )
}

/**
 * Retorna uma escolaridade específica
 * @summary Buscar escolaridade por ID
 */
export type getApiV1EmpregabilidadeEscolaridadesIdResponse200 = {
  data: EmpregabilidadeEscolaridade
  status: 200
}

export type getApiV1EmpregabilidadeEscolaridadesIdResponse400 = {
  data: GetApiV1EmpregabilidadeEscolaridadesId400
  status: 400
}

export type getApiV1EmpregabilidadeEscolaridadesIdResponse404 = {
  data: GetApiV1EmpregabilidadeEscolaridadesId404
  status: 404
}

export type getApiV1EmpregabilidadeEscolaridadesIdResponseComposite =
  | getApiV1EmpregabilidadeEscolaridadesIdResponse200
  | getApiV1EmpregabilidadeEscolaridadesIdResponse400
  | getApiV1EmpregabilidadeEscolaridadesIdResponse404

export type getApiV1EmpregabilidadeEscolaridadesIdResponse =
  getApiV1EmpregabilidadeEscolaridadesIdResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeEscolaridadesIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/escolaridades/${id}`
}

export const getApiV1EmpregabilidadeEscolaridadesId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeEscolaridadesIdResponse> => {
  return customFetch<getApiV1EmpregabilidadeEscolaridadesIdResponse>(
    getGetApiV1EmpregabilidadeEscolaridadesIdUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma escolaridade existente
 * @summary Atualizar escolaridade
 */
export type putApiV1EmpregabilidadeEscolaridadesIdResponse200 = {
  data: EmpregabilidadeEscolaridade
  status: 200
}

export type putApiV1EmpregabilidadeEscolaridadesIdResponse400 = {
  data: PutApiV1EmpregabilidadeEscolaridadesId400
  status: 400
}

export type putApiV1EmpregabilidadeEscolaridadesIdResponse500 = {
  data: PutApiV1EmpregabilidadeEscolaridadesId500
  status: 500
}

export type putApiV1EmpregabilidadeEscolaridadesIdResponseComposite =
  | putApiV1EmpregabilidadeEscolaridadesIdResponse200
  | putApiV1EmpregabilidadeEscolaridadesIdResponse400
  | putApiV1EmpregabilidadeEscolaridadesIdResponse500

export type putApiV1EmpregabilidadeEscolaridadesIdResponse =
  putApiV1EmpregabilidadeEscolaridadesIdResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeEscolaridadesIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/escolaridades/${id}`
}

export const putApiV1EmpregabilidadeEscolaridadesId = async (
  id: string,
  empregabilidadeEscolaridadeBody: EmpregabilidadeEscolaridadeBody,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeEscolaridadesIdResponse> => {
  return customFetch<putApiV1EmpregabilidadeEscolaridadesIdResponse>(
    getPutApiV1EmpregabilidadeEscolaridadesIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEscolaridadeBody),
    }
  )
}

/**
 * Remove uma escolaridade
 * @summary Excluir escolaridade
 */
export type deleteApiV1EmpregabilidadeEscolaridadesIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeEscolaridadesId200
  status: 200
}

export type deleteApiV1EmpregabilidadeEscolaridadesIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeEscolaridadesId400
  status: 400
}

export type deleteApiV1EmpregabilidadeEscolaridadesIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeEscolaridadesId500
  status: 500
}

export type deleteApiV1EmpregabilidadeEscolaridadesIdResponseComposite =
  | deleteApiV1EmpregabilidadeEscolaridadesIdResponse200
  | deleteApiV1EmpregabilidadeEscolaridadesIdResponse400
  | deleteApiV1EmpregabilidadeEscolaridadesIdResponse500

export type deleteApiV1EmpregabilidadeEscolaridadesIdResponse =
  deleteApiV1EmpregabilidadeEscolaridadesIdResponseComposite & {
    headers: Headers
  }

export const getDeleteApiV1EmpregabilidadeEscolaridadesIdUrl = (id: string) => {
  return `/api/v1/empregabilidade/escolaridades/${id}`
}

export const deleteApiV1EmpregabilidadeEscolaridadesId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeEscolaridadesIdResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeEscolaridadesIdResponse>(
    getDeleteApiV1EmpregabilidadeEscolaridadesIdUrl(id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
