import {
  alvaraIcon,
  cadrioIcon,
  cadunicoIcon,
  dividaAtivaIcon,
  iptuIcon,
  licencaSanitariaIcon,
  multasIcon,
} from './most-accessed-services'

import {
  ambienteIcon,
  animaisIcon,
  anticorrupcaoIcon,
  cidadaniaIcon,
  cidadeIcon,
  culturaIcon,
  cursosIcon,
  educacaoIcon,
  emergenciaIcon,
  esporteIcon,
  familiaIcon,
  impostoIcon,
  licencaIcon,
  lgpdIcon,
  obrasIcon,
  ordemPublicaIcon,
  ouvidoriaIcon,
  peticionamentosIcon,
  saudeIcon,
  segurancaIcon,
  servidorIcon,
  trabalhoIcon,
  transitoIcon,
  transporteIcon,
} from './services'

import {
  atualizarCadastroIcon,
  cariocaIcon,
  deslogadoIcon,
  iptuBannerIcon,
  licencaBannerIcon,
} from './banners'

import { brasaoPrefHeaderIcon, logoPrefHeaderIcon } from './logos'

// Named exports
export {
  alvaraIcon,
  ambienteIcon,
  animaisIcon,
  anticorrupcaoIcon,
  atualizarCadastroIcon,
  brasaoPrefHeaderIcon,
  cadrioIcon,
  cadunicoIcon,
  cariocaIcon,
  cidadaniaIcon,
  cidadeIcon,
  culturaIcon,
  cursosIcon,
  deslogadoIcon,
  dividaAtivaIcon,
  educacaoIcon,
  emergenciaIcon,
  esporteIcon,
  familiaIcon,
  impostoIcon,
  iptuBannerIcon,
  iptuIcon,
  licencaBannerIcon,
  licencaIcon,
  licencaSanitariaIcon,
  lgpdIcon,
  logoPrefHeaderIcon,
  multasIcon,
  obrasIcon,
  ordemPublicaIcon,
  ouvidoriaIcon,
  peticionamentosIcon,
  saudeIcon,
  segurancaIcon,
  servidorIcon,
  trabalhoIcon,
  transitoIcon,
  transporteIcon,
}

// Default services export
const icons = {
  ambienteIcon,
  animaisIcon,
  anticorrupcaoIcon,
  cidadaniaIcon,
  cidadeIcon,
  culturaIcon,
  cursosIcon,
  educacaoIcon,
  emergenciaIcon,
  esporteIcon,
  familiaIcon,
  impostoIcon,
  licencaIcon,
  lgpdIcon,
  obrasIcon,
  ordemPublicaIcon,
  ouvidoriaIcon,
  peticionamentosIcon,
  saudeIcon,
  segurancaIcon,
  servidorIcon,
  trabalhoIcon,
  transitoIcon,
  transporteIcon,
}

export default icons
