/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API Dívida Ativa Imobiliária - Pref.Rio (CONTRATO PROVISÓRIO)
 * Contrato **provisório** para os serviços de dívida ativa imobiliária do portal do cidadão:
 * cadastro de imóveis, consulta de débitos/CDAs, simulação de parcelamento, abertura de
 * requerimento e acompanhamento.
 *
 * ATENÇÃO: este documento **não** foi ratificado pela equipe da API (Quarkus). Foi escrito
 * unilateralmente pelo time de front para permitir desenvolvimento em paralelo ao back-end
 * (decisões D8 e D13 do plano do módulo). Cada campo, formato e código de erro aqui é uma
 * premissa registrada em `docs/divida-ativa.md`, e será reconciliado com o contrato oficial
 * na fase de integração.
 *
 * As regras fiscais continuam nos sistemas corporativos (DAM/PGM). Esta API é camada de
 * integração; o front apenas reflete os estados e erros que ela devolve.
 *
 * Identidade: o cidadão é derivado do Bearer token (Keycloak) pela própria API. Nenhum
 * endpoint recebe CPF por path, query ou body.
 *
 * OpenAPI spec version: 0.1.0-provisorio
 */
import type {
  DocumentoRecebido,
  ErrorResponse,
  InternalErrorResponse,
  PostRequerimentoDocumentoBody,
  Requerimento,
  RequerimentoInput,
  UnauthorizedErrorResponse,
  ValidationErrorResponse,
} from '../models'

import { customFetchDividaAtiva } from '../../../custom-fetch-divida-ativa'

export type postRequerimentoResponse201 = {
  data: Requerimento
  status: 201
}

export type postRequerimentoResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type postRequerimentoResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type postRequerimentoResponse409 = {
  data: ErrorResponse
  status: 409
}

export type postRequerimentoResponse422 = {
  data: ErrorResponse
  status: 422
}

export type postRequerimentoResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type postRequerimentoResponseSuccess = postRequerimentoResponse201 & {
  headers: Headers
}
export type postRequerimentoResponseError = (
  | postRequerimentoResponse400
  | postRequerimentoResponse401
  | postRequerimentoResponse409
  | postRequerimentoResponse422
  | postRequerimentoResponse500
) & {
  headers: Headers
}

export type postRequerimentoResponse =
  | postRequerimentoResponseSuccess
  | postRequerimentoResponseError

export const getPostRequerimentoUrl = () => {
  return `/v1/requerimentos`
}

/**
 * Recebe a condição escolhida na simulação e as referências dos documentos já enviados
 * por `POST /v1/requerimentos/documentos`. Responde com o protocolo.
 * @summary Abre um requerimento de parcelamento.
 */
export const postRequerimento = async (
  requerimentoInput: RequerimentoInput,
  options?: RequestInit
): Promise<postRequerimentoResponse> => {
  return customFetchDividaAtiva<postRequerimentoResponse>(
    getPostRequerimentoUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(requerimentoInput),
    }
  )
}

export type postRequerimentoDocumentoResponse201 = {
  data: DocumentoRecebido
  status: 201
}

export type postRequerimentoDocumentoResponse400 = {
  data: ValidationErrorResponse
  status: 400
}

export type postRequerimentoDocumentoResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type postRequerimentoDocumentoResponse413 = {
  data: ErrorResponse
  status: 413
}

export type postRequerimentoDocumentoResponse415 = {
  data: ErrorResponse
  status: 415
}

export type postRequerimentoDocumentoResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type postRequerimentoDocumentoResponseSuccess =
  postRequerimentoDocumentoResponse201 & {
    headers: Headers
  }
export type postRequerimentoDocumentoResponseError = (
  | postRequerimentoDocumentoResponse400
  | postRequerimentoDocumentoResponse401
  | postRequerimentoDocumentoResponse413
  | postRequerimentoDocumentoResponse415
  | postRequerimentoDocumentoResponse500
) & {
  headers: Headers
}

export type postRequerimentoDocumentoResponse =
  | postRequerimentoDocumentoResponseSuccess
  | postRequerimentoDocumentoResponseError

export const getPostRequerimentoDocumentoUrl = () => {
  return `/v1/requerimentos/documentos`
}

/**
 * PROVISÓRIO — o mecanismo de upload é uma decisão em aberto (DEP-3 do plano). Este
 * endpoint assume multipart com um arquivo por chamada, devolvendo uma referência
 * (`documentoId`) que é citada na criação do requerimento. Se a decisão for upload direto
 * para storage com URL assinada, este endpoint é substituído por um par
 * "gerar URL / confirmar envio" e o schema RequerimentoInput não muda.
 * @summary Envia um documento digitalizado para instruir um requerimento.
 */
export const postRequerimentoDocumento = async (
  postRequerimentoDocumentoBody: PostRequerimentoDocumentoBody,
  options?: RequestInit
): Promise<postRequerimentoDocumentoResponse> => {
  const formData = new FormData()
  formData.append(`tipo`, postRequerimentoDocumentoBody.tipo)
  formData.append(`arquivo`, postRequerimentoDocumentoBody.arquivo)

  return customFetchDividaAtiva<postRequerimentoDocumentoResponse>(
    getPostRequerimentoDocumentoUrl(),
    {
      ...options,
      method: 'POST',
      body: formData,
    }
  )
}
