/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Cidadão - Pref.Rio (System API)
 * API de integração para validação de identidade via Keycloak e sincronização de Person Account no Salesforce.
 * OpenAPI spec version: 1.0.3
 */
import type { ProtocoloResumo } from './protocoloResumo'

/**
 * Lista de protocolos do cidadão com resumo das ordens de serviço.
 */
export interface ChamadosListResponse {
  protocolos?: ProtocoloResumo[]
}
