/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Cidadão - Pref.Rio (System API)
 * API de integração para validação de identidade via Keycloak e sincronização de Person Account no Salesforce.
 * OpenAPI spec version: 1.0.3
 */

/**
 * @nullable
 */
export type ChamadoDetailResponseOrdensDeServicoItemCanOpenRecurso = {
  available?: boolean
  /** @nullable */
  categoryId?: string | null
  /**
   * Prazo-limite ISO-8601 para abrir recurso.
   * @nullable
   */
  deadline?: string | null
} | null
