/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Cidadão - Pref.Rio (System API)
 * API de integração para validação de identidade via Keycloak e sincronização de Person Account no Salesforce.
 * OpenAPI spec version: 1.0.3
 */

export interface CitizenCreateRequest {
  cpf: string
  nome: string
  email: string
  /** Formato obrigatório: 55+DDD+Número */
  telefone1?: string
  genero?: string
  raca?: string
}
