/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Cidadão - Pref.Rio (System API)
 * API de integração para validação de identidade via Keycloak e sincronização de Person Account no Salesforce.
 * OpenAPI spec version: 1.0.3
 */
import type { StatusAnonimizacaoResponseStatus } from './statusAnonimizacaoResponseStatus'

/**
 * Resposta da consulta de status de anonimização.
 */
export interface StatusAnonimizacaoResponse {
  /** Número único da solicitação de anonimização. */
  numeroSolicitacao?: string
  /**
   * Status atual da solicitação:
   * - enfileirado: aguardando processamento
   * - concluido: anonimização concluída com sucesso (irreversível)
   * - falhou: falha no processamento
   * - cancelado: solicitação cancelada
   */
  status?: StatusAnonimizacaoResponseStatus
  /** Data e hora de criação da solicitação (ISO 8601). */
  dataSolicitacao?: string
  /**
   * Data e hora da conclusão (presente apenas quando status for "concluido").
   * @nullable
   */
  dataConclusao?: string | null
}
