/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  EmpregabilidadeCandidaturaBloqueio,
  GetApiV1EmpregabilidadeCandidaturaBloqueios200,
  GetApiV1EmpregabilidadeCandidaturaBloqueios400,
  GetApiV1EmpregabilidadeCandidaturaBloqueios500,
  GetApiV1EmpregabilidadeCandidaturaBloqueiosParams,
  PostApiV1EmpregabilidadeCandidaturaBloqueios400,
  PostApiV1EmpregabilidadeCandidaturaBloqueios500,
} from '../models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna lista paginada de bloqueios de candidatura, com filtros opcionais. Restrito a administradores.
 * @summary Listar bloqueios de candidatura (admin)
 */
export type getApiV1EmpregabilidadeCandidaturaBloqueiosResponse200 = {
  data: GetApiV1EmpregabilidadeCandidaturaBloqueios200
  status: 200
}

export type getApiV1EmpregabilidadeCandidaturaBloqueiosResponse400 = {
  data: GetApiV1EmpregabilidadeCandidaturaBloqueios400
  status: 400
}

export type getApiV1EmpregabilidadeCandidaturaBloqueiosResponse500 = {
  data: GetApiV1EmpregabilidadeCandidaturaBloqueios500
  status: 500
}

export type getApiV1EmpregabilidadeCandidaturaBloqueiosResponseSuccess =
  getApiV1EmpregabilidadeCandidaturaBloqueiosResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeCandidaturaBloqueiosResponseError = (
  | getApiV1EmpregabilidadeCandidaturaBloqueiosResponse400
  | getApiV1EmpregabilidadeCandidaturaBloqueiosResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeCandidaturaBloqueiosResponse =
  | getApiV1EmpregabilidadeCandidaturaBloqueiosResponseSuccess
  | getApiV1EmpregabilidadeCandidaturaBloqueiosResponseError

export const getGetApiV1EmpregabilidadeCandidaturaBloqueiosUrl = (
  params?: GetApiV1EmpregabilidadeCandidaturaBloqueiosParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/candidatura-bloqueios?${stringifiedParams}`
    : `/api/v1/empregabilidade/candidatura-bloqueios`
}

export const getApiV1EmpregabilidadeCandidaturaBloqueios = async (
  params?: GetApiV1EmpregabilidadeCandidaturaBloqueiosParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCandidaturaBloqueiosResponse> => {
  return customFetch<getApiV1EmpregabilidadeCandidaturaBloqueiosResponse>(
    getGetApiV1EmpregabilidadeCandidaturaBloqueiosUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Registra a tentativa de candidatura de um CPF a uma vaga que foi bloqueada por não atender critérios de elegibilidade
 * @summary Registrar bloqueio de candidatura
 */
export type postApiV1EmpregabilidadeCandidaturaBloqueiosResponse201 = {
  data: EmpregabilidadeCandidaturaBloqueio
  status: 201
}

export type postApiV1EmpregabilidadeCandidaturaBloqueiosResponse400 = {
  data: PostApiV1EmpregabilidadeCandidaturaBloqueios400
  status: 400
}

export type postApiV1EmpregabilidadeCandidaturaBloqueiosResponse500 = {
  data: PostApiV1EmpregabilidadeCandidaturaBloqueios500
  status: 500
}

export type postApiV1EmpregabilidadeCandidaturaBloqueiosResponseSuccess =
  postApiV1EmpregabilidadeCandidaturaBloqueiosResponse201 & {
    headers: Headers
  }
export type postApiV1EmpregabilidadeCandidaturaBloqueiosResponseError = (
  | postApiV1EmpregabilidadeCandidaturaBloqueiosResponse400
  | postApiV1EmpregabilidadeCandidaturaBloqueiosResponse500
) & {
  headers: Headers
}

export type postApiV1EmpregabilidadeCandidaturaBloqueiosResponse =
  | postApiV1EmpregabilidadeCandidaturaBloqueiosResponseSuccess
  | postApiV1EmpregabilidadeCandidaturaBloqueiosResponseError

export const getPostApiV1EmpregabilidadeCandidaturaBloqueiosUrl = () => {
  return `/api/v1/empregabilidade/candidatura-bloqueios`
}

export const postApiV1EmpregabilidadeCandidaturaBloqueios = async (
  empregabilidadeCandidaturaBloqueio: EmpregabilidadeCandidaturaBloqueio,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeCandidaturaBloqueiosResponse> => {
  return customFetch<postApiV1EmpregabilidadeCandidaturaBloqueiosResponse>(
    getPostApiV1EmpregabilidadeCandidaturaBloqueiosUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeCandidaturaBloqueio),
    }
  )
}
