/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type { HandlersErrorResponse, ModelsLegalEntity } from '../models'

import { customFetch } from '../../../custom-fetch'

export type getLegalEntityCnpjResponse200 = {
  data: ModelsLegalEntity
  status: 200
}

export type getLegalEntityCnpjResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getLegalEntityCnpjResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getLegalEntityCnpjResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getLegalEntityCnpjResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type getLegalEntityCnpjResponse429 = {
  data: HandlersErrorResponse
  status: 429
}

export type getLegalEntityCnpjResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getLegalEntityCnpjResponseSuccess =
  getLegalEntityCnpjResponse200 & {
    headers: Headers
  }
export type getLegalEntityCnpjResponseError = (
  | getLegalEntityCnpjResponse400
  | getLegalEntityCnpjResponse401
  | getLegalEntityCnpjResponse403
  | getLegalEntityCnpjResponse404
  | getLegalEntityCnpjResponse429
  | getLegalEntityCnpjResponse500
) & {
  headers: Headers
}

export type getLegalEntityCnpjResponse =
  | getLegalEntityCnpjResponseSuccess
  | getLegalEntityCnpjResponseError

export const getGetLegalEntityCnpjUrl = (cnpj: string) => {
  return `/legal-entity/${cnpj}`
}

/**
 * Recupera informações detalhadas de uma entidade jurídica (pessoa jurídica) pelo CNPJ. O acesso é permitido para administradores ou se o CPF do JWT estiver como responsável ou sócio da entidade.
 * @summary Obter informações de uma entidade jurídica por CNPJ
 */
export const getLegalEntityCnpj = async (
  cnpj: string,
  options?: RequestInit
): Promise<getLegalEntityCnpjResponse> => {
  return customFetch<getLegalEntityCnpjResponse>(
    getGetLegalEntityCnpjUrl(cnpj),
    {
      ...options,
      method: 'GET',
    }
  )
}
