/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API Dívida Ativa Imobiliária - Pref.Rio (CONTRATO PROVISÓRIO)
 * Contrato **provisório** para os serviços de dívida ativa imobiliária do portal do cidadão:
 * cadastro de imóveis, consulta de débitos/CDAs, simulação de parcelamento, abertura de
 * requerimento e acompanhamento.
 *
 * ATENÇÃO: este documento **não** foi ratificado pela equipe da API (Quarkus). Foi escrito
 * unilateralmente pelo time de front para permitir desenvolvimento em paralelo ao back-end
 * (decisões D8 e D13 do plano do módulo). Cada campo, formato e código de erro aqui é uma
 * premissa registrada em `docs/divida-ativa.md`, e será reconciliado com o contrato oficial
 * na fase de integração.
 *
 * As regras fiscais continuam nos sistemas corporativos (DAM/PGM). Esta API é camada de
 * integração; o front apenas reflete os estados e erros que ela devolve.
 *
 * Identidade: o cidadão é derivado do Bearer token (Keycloak) pela própria API. Nenhum
 * endpoint recebe CPF por path, query ou body.
 *
 * OpenAPI spec version: 0.1.0-provisorio
 */
import type {
  DebitoListResponse,
  GetDebitosImovelParams,
  InternalErrorResponse,
  NotFoundErrorResponse,
  UnauthorizedErrorResponse,
} from '../models'

import { customFetchDividaAtiva } from '../../../custom-fetch-divida-ativa'

export type getDebitosImovelResponse200 = {
  data: DebitoListResponse
  status: 200
}

export type getDebitosImovelResponse401 = {
  data: UnauthorizedErrorResponse
  status: 401
}

export type getDebitosImovelResponse404 = {
  data: NotFoundErrorResponse
  status: 404
}

export type getDebitosImovelResponse500 = {
  data: InternalErrorResponse
  status: 500
}

export type getDebitosImovelResponseSuccess = getDebitosImovelResponse200 & {
  headers: Headers
}
export type getDebitosImovelResponseError = (
  | getDebitosImovelResponse401
  | getDebitosImovelResponse404
  | getDebitosImovelResponse500
) & {
  headers: Headers
}

export type getDebitosImovelResponse =
  | getDebitosImovelResponseSuccess
  | getDebitosImovelResponseError

export const getGetDebitosImovelUrl = (
  inscricaoImobiliaria: string,
  params?: GetDebitosImovelParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/v1/imoveis/${inscricaoImobiliaria}/debitos?${stringifiedParams}`
    : `/v1/imoveis/${inscricaoImobiliaria}/debitos`
}

/**
 * A elegibilidade de cada CDA para parcelamento vem no campo `parcelavel`, calculado
 * pela API a partir das regras do DAM/PGM. O front nunca recalcula.
 * @summary Lista os débitos em dívida ativa (CDAs) de um imóvel.
 */
export const getDebitosImovel = async (
  inscricaoImobiliaria: string,
  params?: GetDebitosImovelParams,
  options?: RequestInit
): Promise<getDebitosImovelResponse> => {
  return customFetchDividaAtiva<getDebitosImovelResponse>(
    getGetDebitosImovelUrl(inscricaoImobiliaria, params),
    {
      ...options,
      method: 'GET',
    }
  )
}
