/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AdminTombamentosByOldServiceParams = {
  /**
   * Origem (1746_v2_llm ou carioca-digital_v2_llm)
   */
  origem: string
  /**
   * ID do serviço antigo
   */
  id_servico_antigo: string
}
