/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type GetApiV2SearchParams = {
  /**
   * Texto da busca
   */
  q: string
  /**
   * Tipo de busca: keyword, semantic, hybrid
   */
  type: string
  /**
   * Número da página (mínimo: 1)
   */
  page?: number
  /**
   * Resultados por página (máximo: 100)
   */
  per_page?: number
  /**
   * Incluir documentos inativos (aplica-se apenas a coleções com filtro de status)
   */
  include_inactive?: boolean
  /**
   * Alpha para busca hybrid (0-1). Alpha=0.3 significa 30% texto + 70% vetor.
   */
  alpha?: number
  /**
   * Score mínimo para busca keyword (0-1, filtra text_match normalizado)
   */
  threshold_keyword?: number
  /**
   * Score mínimo para busca semantic (0-1, filtra por similaridade vetorial)
   */
  threshold_semantic?: number
  /**
   * Score mínimo para busca hybrid (0-1, filtra score híbrido)
   */
  threshold_hybrid?: number
}
