/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type GetApiV1SubcategoriesSubcategoryServicesParams = {
  /**
   * Nome da categoria pai para desambiguar subcategorias com nomes iguais (ex: Documentos, Educação)
   */
  category?: string
  /**
   * Número da página (mínimo: 1)
   * @minimum 1
   */
  page?: number
  /**
   * Quantidade de serviços por página (máximo: 100)
   * @minimum 1
   * @maximum 100
   */
  per_page?: number
  /**
   * Incluir serviços inativos/rascunhos (status != 1)
   */
  include_inactive?: boolean
}
