/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type ModelsMigrationStatus =
  (typeof ModelsMigrationStatus)[keyof typeof ModelsMigrationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsMigrationStatus = {
  MigrationStatusIdle: 'idle',
  MigrationStatusInProgress: 'in_progress',
  MigrationStatusCompleted: 'completed',
  MigrationStatusFailed: 'failed',
  MigrationStatusRollback: 'rollback',
} as const
