/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsMigrationStatus } from './modelsMigrationStatus'

export interface ModelsMigrationStatusResponse {
  backup_collection?: string
  completed_at?: number
  error_message?: string
  is_locked?: boolean
  migrated_documents?: number
  progress?: number
  schema_version?: string
  source_collection?: string
  started_at?: number
  started_by?: string
  status?: ModelsMigrationStatus
  target_collection?: string
  total_documents?: number
}
