import type { ModelsSearchType } from './modelsSearchType'
import type { ModelsUnifiedDocument } from './modelsUnifiedDocument'
/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsUnifiedSearchResponseMetadata } from './modelsUnifiedSearchResponseMetadata'

export interface ModelsUnifiedSearchResponse {
  /** Which collections were searched */
  collections?: string[]
  /** Após aplicar thresholds */
  filtered_count?: number
  /** Para AI search */
  metadata?: ModelsUnifiedSearchResponseMetadata
  page?: number
  per_page?: number
  results?: ModelsUnifiedDocument[]
  search_type?: ModelsSearchType
  /** Total original do Typesense (across all collections) */
  total_count?: number
}
