/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsAgentsConfig } from './modelsAgentsConfig'
import type { ModelsButton } from './modelsButton'
import type { ModelsPrefRioServiceRequestExtraFields } from './modelsPrefRioServiceRequestExtraFields'

export interface ModelsPrefRioServiceRequest {
  agents?: ModelsAgentsConfig
  awaiting_approval?: boolean
  buttons?: ModelsButton[]
  canais_digitais?: string[]
  canais_presenciais?: string[]
  /** @maxLength 20000 */
  custo_servico?: string
  /** @maxLength 20000 */
  descricao_completa?: string
  documentos_necessarios?: string[]
  extra_fields?: ModelsPrefRioServiceRequestExtraFields
  fixar_destaque?: boolean
  /** @maxLength 20000 */
  instrucoes_solicitante?: string
  is_free?: boolean
  legislacao_relacionada?: string[]
  /** @maxLength 20000 */
  nome_servico: string
  /** @minItems 1 */
  orgao_gestor: string[]
  /** @minItems 1 */
  publico_especifico: string[]
  published_at?: number
  /** @maxLength 20000 */
  resultado_solicitacao?: string
  /** @maxLength 20000 */
  resumo: string
  /** @maxLength 20000 */
  servico_nao_cobre?: string
  /**
   * @minimum 0
   * @maximum 1
   */
  status?: number
  /** @maxLength 20000 */
  tema_geral: string
  /** @maxLength 20000 */
  tempo_atendimento?: string
}
