/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export interface ModelsScoreInfo {
  /** Score final após aplicar recency boost */
  final_score?: number
  /** Score híbrido combinado 0-1 */
  hybrid_score?: number
  /** Se passou no threshold */
  passed_threshold?: boolean
  /** Fator de recência aplicado (1.0 = recente, decai com o tempo) */
  recency_factor?: number
  /** Score normalizado 0-1 do text_match */
  text_match_normalized?: number
  /** Tipo de threshold aplicado: "keyword", "semantic", "hybrid", "none" */
  threshold_applied?: string
  /** Valor do threshold aplicado */
  threshold_value?: number
  /** Similaridade vetorial 0-1 (1 = idêntico) */
  vector_similarity?: number
}
