/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsAgentsConfig } from './modelsAgentsConfig'
import type { ModelsButton } from './modelsButton'
import type { ModelsPrefRioServiceExtraFields } from './modelsPrefRioServiceExtraFields'

export interface ModelsPrefRioService {
  agents?: ModelsAgentsConfig
  /** @maxLength 20000 */
  autor: string
  awaiting_approval?: boolean
  buttons?: ModelsButton[]
  canais_digitais?: string[]
  canais_presenciais?: string[]
  created_at?: number
  /** @maxLength 20000 */
  custo_servico: string
  /** @maxLength 20000 */
  descricao_completa: string
  documentos_necessarios?: string[]
  embedding?: number[]
  extra_fields?: ModelsPrefRioServiceExtraFields
  fixar_destaque?: boolean
  id?: string
  /** @maxLength 20000 */
  instrucoes_solicitante?: string
  is_free?: boolean
  last_update?: number
  legislacao_relacionada?: string[]
  /** @maxLength 20000 */
  nome_servico: string
  /** @minItems 1 */
  orgao_gestor: string[]
  publico_especifico?: string[]
  published_at?: number
  /** @maxLength 20000 */
  resultado_solicitacao: string
  /** @maxLength 20000 */
  resumo: string
  search_content?: string
  /** @maxLength 20000 */
  servico_nao_cobre?: string
  /**
   * 0=Draft, 1=Published
   * @minimum 0
   * @maximum 1
   */
  status?: number
  /** @maxLength 20000 */
  tema_geral: string
  /** @maxLength 20000 */
  tempo_atendimento: string
}
