/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  GetApiV1EnrollmentsUserCpf200,
  GetApiV1EnrollmentsUserCpfParams,
  ModelsErrorResponse,
  ModelsInscricao,
  ModelsScheduleChangeRequest,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna lista paginada de inscrições realizadas por um usuário (identificado pelo CPF), incluindo certificate_url
 * @summary Listar inscrições de um usuário específico
 */
export type getApiV1EnrollmentsUserCpfResponse200 = {
  data: GetApiV1EnrollmentsUserCpf200
  status: 200
}

export type getApiV1EnrollmentsUserCpfResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type getApiV1EnrollmentsUserCpfResponse403 = {
  data: ModelsErrorResponse
  status: 403
}

export type getApiV1EnrollmentsUserCpfResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type getApiV1EnrollmentsUserCpfResponseComposite =
  | getApiV1EnrollmentsUserCpfResponse200
  | getApiV1EnrollmentsUserCpfResponse400
  | getApiV1EnrollmentsUserCpfResponse403
  | getApiV1EnrollmentsUserCpfResponse500

export type getApiV1EnrollmentsUserCpfResponse =
  getApiV1EnrollmentsUserCpfResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EnrollmentsUserCpfUrl = (
  cpf: string,
  params?: GetApiV1EnrollmentsUserCpfParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/enrollments/user/${cpf}?${stringifiedParams}`
    : `/api/v1/enrollments/user/${cpf}`
}

export const getApiV1EnrollmentsUserCpf = async (
  cpf: string,
  params?: GetApiV1EnrollmentsUserCpfParams,
  options?: RequestInit
): Promise<getApiV1EnrollmentsUserCpfResponse> => {
  return customFetch<getApiV1EnrollmentsUserCpfResponse>(
    getGetApiV1EnrollmentsUserCpfUrl(cpf, params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Permite ao cidadão trocar de turma em uma inscrição existente. Deve ser feito com pelo menos 72h de antecedência do início da aula. Se a inscrição estava aprovada, volta para status pendente.
 * @summary Trocar turma/horário de inscrição
 */
export type putApiV1EnrollmentsEnrollmentIdScheduleResponse200 = {
  data: ModelsInscricao
  status: 200
}

export type putApiV1EnrollmentsEnrollmentIdScheduleResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type putApiV1EnrollmentsEnrollmentIdScheduleResponse403 = {
  data: ModelsErrorResponse
  status: 403
}

export type putApiV1EnrollmentsEnrollmentIdScheduleResponse404 = {
  data: ModelsErrorResponse
  status: 404
}

export type putApiV1EnrollmentsEnrollmentIdScheduleResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type putApiV1EnrollmentsEnrollmentIdScheduleResponseComposite =
  | putApiV1EnrollmentsEnrollmentIdScheduleResponse200
  | putApiV1EnrollmentsEnrollmentIdScheduleResponse400
  | putApiV1EnrollmentsEnrollmentIdScheduleResponse403
  | putApiV1EnrollmentsEnrollmentIdScheduleResponse404
  | putApiV1EnrollmentsEnrollmentIdScheduleResponse500

export type putApiV1EnrollmentsEnrollmentIdScheduleResponse =
  putApiV1EnrollmentsEnrollmentIdScheduleResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EnrollmentsEnrollmentIdScheduleUrl = (
  enrollmentId: string
) => {
  return `/api/v1/enrollments/${enrollmentId}/schedule`
}

export const putApiV1EnrollmentsEnrollmentIdSchedule = async (
  enrollmentId: string,
  modelsScheduleChangeRequest: ModelsScheduleChangeRequest,
  options?: RequestInit
): Promise<putApiV1EnrollmentsEnrollmentIdScheduleResponse> => {
  return customFetch<putApiV1EnrollmentsEnrollmentIdScheduleResponse>(
    getPutApiV1EnrollmentsEnrollmentIdScheduleUrl(enrollmentId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsScheduleChangeRequest),
    }
  )
}
