/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeEmpresasCnpj200,
  DeleteApiV1EmpregabilidadeEmpresasCnpj500,
  EmpregabilidadeEmpresa,
  EmpregabilidadeEmpresaBody,
  GetApiV1EmpregabilidadeEmpresas200,
  GetApiV1EmpregabilidadeEmpresas500,
  GetApiV1EmpregabilidadeEmpresasCnpj404,
  GetApiV1EmpregabilidadeEmpresasCnpj500,
  GetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj400,
  GetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj404,
  GetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj500,
  GetApiV1EmpregabilidadeEmpresasParams,
  ModelsLegalEntityConsultaResponse,
  PostApiV1EmpregabilidadeEmpresas400,
  PostApiV1EmpregabilidadeEmpresas500,
  PutApiV1EmpregabilidadeEmpresasCnpj400,
  PutApiV1EmpregabilidadeEmpresasCnpj500,
} from '.././models'

import { customFetch } from '../../../custom-fetch-course'

/**
 * Retorna lista paginada de empresas
 * @summary Listar empresas
 */
export type getApiV1EmpregabilidadeEmpresasResponse200 = {
  data: GetApiV1EmpregabilidadeEmpresas200
  status: 200
}

export type getApiV1EmpregabilidadeEmpresasResponse500 = {
  data: GetApiV1EmpregabilidadeEmpresas500
  status: 500
}

export type getApiV1EmpregabilidadeEmpresasResponseComposite =
  | getApiV1EmpregabilidadeEmpresasResponse200
  | getApiV1EmpregabilidadeEmpresasResponse500

export type getApiV1EmpregabilidadeEmpresasResponse =
  getApiV1EmpregabilidadeEmpresasResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeEmpresasUrl = (
  params?: GetApiV1EmpregabilidadeEmpresasParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/empresas?${stringifiedParams}`
    : `/api/v1/empregabilidade/empresas`
}

export const getApiV1EmpregabilidadeEmpresas = async (
  params?: GetApiV1EmpregabilidadeEmpresasParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeEmpresasResponse> => {
  return customFetch<getApiV1EmpregabilidadeEmpresasResponse>(
    getGetApiV1EmpregabilidadeEmpresasUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma nova empresa
 * @summary Criar empresa
 */
export type postApiV1EmpregabilidadeEmpresasResponse201 = {
  data: EmpregabilidadeEmpresa
  status: 201
}

export type postApiV1EmpregabilidadeEmpresasResponse400 = {
  data: PostApiV1EmpregabilidadeEmpresas400
  status: 400
}

export type postApiV1EmpregabilidadeEmpresasResponse500 = {
  data: PostApiV1EmpregabilidadeEmpresas500
  status: 500
}

export type postApiV1EmpregabilidadeEmpresasResponseComposite =
  | postApiV1EmpregabilidadeEmpresasResponse201
  | postApiV1EmpregabilidadeEmpresasResponse400
  | postApiV1EmpregabilidadeEmpresasResponse500

export type postApiV1EmpregabilidadeEmpresasResponse =
  postApiV1EmpregabilidadeEmpresasResponseComposite & {
    headers: Headers
  }

export const getPostApiV1EmpregabilidadeEmpresasUrl = () => {
  return `/api/v1/empregabilidade/empresas`
}

export const postApiV1EmpregabilidadeEmpresas = async (
  empregabilidadeEmpresaBody: EmpregabilidadeEmpresaBody,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeEmpresasResponse> => {
  return customFetch<postApiV1EmpregabilidadeEmpresasResponse>(
    getPostApiV1EmpregabilidadeEmpresasUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEmpresaBody),
    }
  )
}

/**
 * Consulta dados de uma empresa pelo CNPJ no RMI (Registro Mercantil Integrado)
 * @summary Consultar CNPJ
 */
export type getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse200 = {
  data: ModelsLegalEntityConsultaResponse
  status: 200
}

export type getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse400 = {
  data: GetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj400
  status: 400
}

export type getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse404 = {
  data: GetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj404
  status: 404
}

export type getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse500 = {
  data: GetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj500
  status: 500
}

export type getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponseComposite =
  | getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse200
  | getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse400
  | getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse404
  | getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse500

export type getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse =
  getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjUrl = (
  cnpj: string
) => {
  return `/api/v1/empregabilidade/empresas/consulta-cnpj/${cnpj}`
}

export const getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpj = async (
  cnpj: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse> => {
  return customFetch<getApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjResponse>(
    getGetApiV1EmpregabilidadeEmpresasConsultaCnpjCnpjUrl(cnpj),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Retorna uma empresa pelo CNPJ
 * @summary Buscar empresa
 */
export type getApiV1EmpregabilidadeEmpresasCnpjResponse200 = {
  data: EmpregabilidadeEmpresa
  status: 200
}

export type getApiV1EmpregabilidadeEmpresasCnpjResponse404 = {
  data: GetApiV1EmpregabilidadeEmpresasCnpj404
  status: 404
}

export type getApiV1EmpregabilidadeEmpresasCnpjResponse500 = {
  data: GetApiV1EmpregabilidadeEmpresasCnpj500
  status: 500
}

export type getApiV1EmpregabilidadeEmpresasCnpjResponseComposite =
  | getApiV1EmpregabilidadeEmpresasCnpjResponse200
  | getApiV1EmpregabilidadeEmpresasCnpjResponse404
  | getApiV1EmpregabilidadeEmpresasCnpjResponse500

export type getApiV1EmpregabilidadeEmpresasCnpjResponse =
  getApiV1EmpregabilidadeEmpresasCnpjResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeEmpresasCnpjUrl = (cnpj: string) => {
  return `/api/v1/empregabilidade/empresas/${cnpj}`
}

export const getApiV1EmpregabilidadeEmpresasCnpj = async (
  cnpj: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeEmpresasCnpjResponse> => {
  return customFetch<getApiV1EmpregabilidadeEmpresasCnpjResponse>(
    getGetApiV1EmpregabilidadeEmpresasCnpjUrl(cnpj),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma empresa existente
 * @summary Atualizar empresa
 */
export type putApiV1EmpregabilidadeEmpresasCnpjResponse200 = {
  data: EmpregabilidadeEmpresa
  status: 200
}

export type putApiV1EmpregabilidadeEmpresasCnpjResponse400 = {
  data: PutApiV1EmpregabilidadeEmpresasCnpj400
  status: 400
}

export type putApiV1EmpregabilidadeEmpresasCnpjResponse500 = {
  data: PutApiV1EmpregabilidadeEmpresasCnpj500
  status: 500
}

export type putApiV1EmpregabilidadeEmpresasCnpjResponseComposite =
  | putApiV1EmpregabilidadeEmpresasCnpjResponse200
  | putApiV1EmpregabilidadeEmpresasCnpjResponse400
  | putApiV1EmpregabilidadeEmpresasCnpjResponse500

export type putApiV1EmpregabilidadeEmpresasCnpjResponse =
  putApiV1EmpregabilidadeEmpresasCnpjResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeEmpresasCnpjUrl = (cnpj: string) => {
  return `/api/v1/empregabilidade/empresas/${cnpj}`
}

export const putApiV1EmpregabilidadeEmpresasCnpj = async (
  cnpj: string,
  empregabilidadeEmpresaBody: EmpregabilidadeEmpresaBody,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeEmpresasCnpjResponse> => {
  return customFetch<putApiV1EmpregabilidadeEmpresasCnpjResponse>(
    getPutApiV1EmpregabilidadeEmpresasCnpjUrl(cnpj),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEmpresaBody),
    }
  )
}

/**
 * Remove uma empresa pelo CNPJ
 * @summary Excluir empresa
 */
export type deleteApiV1EmpregabilidadeEmpresasCnpjResponse200 = {
  data: DeleteApiV1EmpregabilidadeEmpresasCnpj200
  status: 200
}

export type deleteApiV1EmpregabilidadeEmpresasCnpjResponse500 = {
  data: DeleteApiV1EmpregabilidadeEmpresasCnpj500
  status: 500
}

export type deleteApiV1EmpregabilidadeEmpresasCnpjResponseComposite =
  | deleteApiV1EmpregabilidadeEmpresasCnpjResponse200
  | deleteApiV1EmpregabilidadeEmpresasCnpjResponse500

export type deleteApiV1EmpregabilidadeEmpresasCnpjResponse =
  deleteApiV1EmpregabilidadeEmpresasCnpjResponseComposite & {
    headers: Headers
  }

export const getDeleteApiV1EmpregabilidadeEmpresasCnpjUrl = (cnpj: string) => {
  return `/api/v1/empregabilidade/empresas/${cnpj}`
}

export const deleteApiV1EmpregabilidadeEmpresasCnpj = async (
  cnpj: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeEmpresasCnpjResponse> => {
  return customFetch<deleteApiV1EmpregabilidadeEmpresasCnpjResponse>(
    getDeleteApiV1EmpregabilidadeEmpresasCnpjUrl(cnpj),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
