name: Quality Gate

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality-gate:
    uses: prefeitura-rio/actions/.github/workflows/quality-gate.yml@quality-gate-latest
    with:
      project-name: superapp
      working-directory: .